using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcArpReport0503317
    {
        public DcArpReport0503317()
        {
            FsBeTabr2317List = new HashSet<FsBeTabr2317List>();
            FsBrTabr1317List = new HashSet<FsBrTabr1317List>();
            FsKrTab4317List = new HashSet<FsKrTab4317List>();
            FsSfTab3a317List = new HashSet<FsSfTab3a317List>();
            FsSfTab3b317List = new HashSet<FsSfTab3b317List>();
            FsSfTab3c317List = new HashSet<FsSfTab3c317List>();
            FsSfTab3d317List = new HashSet<FsSfTab3d317List>();
        }

        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string Ord { get; set; }
        public string PfnLeader { get; set; }
        public string PfnChiefAcc { get; set; }
        public string PfnLeaderOfFes { get; set; }
        public string PfnPostLeader { get; set; }
        public string PfnPostChiefAcc { get; set; }
        public string PfnPostLeaderOf { get; set; }
        public string PfnExecutor { get; set; }
        public string PfnPostExecutor { get; set; }
        public string PfnPhone { get; set; }
        public string BrC2R010 { get; set; }
        public string BrC3aR010 { get; set; }
        public string BrC3bR010 { get; set; }
        public decimal? BrC4R010 { get; set; }
        public decimal? BrC5R010 { get; set; }
        public decimal? BrC6R010 { get; set; }
        public decimal? BrC7R010 { get; set; }
        public decimal? BrC8R010 { get; set; }
        public decimal? BrC9R010 { get; set; }
        public decimal? BrC10R010 { get; set; }
        public decimal? BrC11R010 { get; set; }
        public decimal? BrC12R010 { get; set; }
        public decimal? BrC13R010 { get; set; }
        public decimal? BrC14R010 { get; set; }
        public decimal? BrC15R010 { get; set; }
        public decimal? BrC16R010 { get; set; }
        public decimal? BrC17R010 { get; set; }
        public decimal? BrC18R010 { get; set; }
        public decimal? BrC19R010 { get; set; }
        public decimal? BrC20R010 { get; set; }
        public decimal? BrC21R010 { get; set; }
        public decimal? BrC22R010 { get; set; }
        public decimal? BrC23R010 { get; set; }
        public decimal? BrC24R010 { get; set; }
        public decimal? BrC25R010 { get; set; }
        public decimal? BrC26R010 { get; set; }
        public decimal? BrC27R010 { get; set; }
        public decimal? BrC28R010 { get; set; }
        public decimal? BrC29R010 { get; set; }
        public string BeC3bR200 { get; set; }
        public string BeC3cR200 { get; set; }
        public string BeC3dR200 { get; set; }
        public decimal? BeC4R200 { get; set; }
        public decimal? BeC5R200 { get; set; }
        public decimal? BeC6R200 { get; set; }
        public decimal? BeC7R200 { get; set; }
        public decimal? BeC8R200 { get; set; }
        public decimal? BeC9R200 { get; set; }
        public decimal? BeC10R200 { get; set; }
        public decimal? BeC11R200 { get; set; }
        public decimal? BeC12R200 { get; set; }
        public decimal? BeC13R200 { get; set; }
        public decimal? BeC14R200 { get; set; }
        public decimal? BeC15R200 { get; set; }
        public decimal? BeC16R200 { get; set; }
        public decimal? BeC17R200 { get; set; }
        public decimal? BeC18R200 { get; set; }
        public decimal? BeC19R200 { get; set; }
        public decimal? BeC20R200 { get; set; }
        public decimal? BeC21R200 { get; set; }
        public decimal? BeC22R200 { get; set; }
        public decimal? BeC23R200 { get; set; }
        public decimal? BeC24R200 { get; set; }
        public decimal? BeC25R200 { get; set; }
        public decimal? BeC26R200 { get; set; }
        public decimal? BeC27R200 { get; set; }
        public decimal? BeC28R200 { get; set; }
        public decimal? BeC29R200 { get; set; }
        public string BeC3bR450 { get; set; }
        public string BeC3cR450 { get; set; }
        public string BeC3dR450 { get; set; }
        public decimal? BeC4R450 { get; set; }
        public decimal? BeC5R450 { get; set; }
        public decimal? BeC6R450 { get; set; }
        public decimal? BeC7R450 { get; set; }
        public decimal? BeC8R450 { get; set; }
        public decimal? BeC9R450 { get; set; }
        public decimal? BeC10R450 { get; set; }
        public decimal? BeC11R450 { get; set; }
        public decimal? BeC12R450 { get; set; }
        public decimal? BeC13R450 { get; set; }
        public decimal? BeC14R450 { get; set; }
        public decimal? BeC15R450 { get; set; }
        public decimal? BeC16R450 { get; set; }
        public decimal? BeC17R450 { get; set; }
        public decimal? BeC18R450 { get; set; }
        public decimal? BeC19R450 { get; set; }
        public decimal? BeC20R450 { get; set; }
        public decimal? BeC21R450 { get; set; }
        public decimal? BeC22R450 { get; set; }
        public decimal? BeC23R450 { get; set; }
        public decimal? BeC24R450 { get; set; }
        public decimal? BeC25R450 { get; set; }
        public decimal? BeC26R450 { get; set; }
        public decimal? BeC27R450 { get; set; }
        public decimal? BeC28R450 { get; set; }
        public decimal? BeC29R450 { get; set; }
        public string SfC3bR500 { get; set; }
        public decimal? SfC4R500 { get; set; }
        public decimal? SfC5R500 { get; set; }
        public decimal? SfC6R500 { get; set; }
        public decimal? SfC7R500 { get; set; }
        public decimal? SfC8R500 { get; set; }
        public decimal? SfC9R500 { get; set; }
        public decimal? SfC10R500 { get; set; }
        public decimal? SfC11R500 { get; set; }
        public decimal? SfC12R500 { get; set; }
        public decimal? SfC13R500 { get; set; }
        public decimal? SfC14R500 { get; set; }
        public decimal? SfC15R500 { get; set; }
        public decimal? SfC16R500 { get; set; }
        public decimal? SfC17R500 { get; set; }
        public decimal? SfC18R500 { get; set; }
        public decimal? SfC19R500 { get; set; }
        public decimal? SfC20R500 { get; set; }
        public decimal? SfC21R500 { get; set; }
        public decimal? SfC22R500 { get; set; }
        public decimal? SfC23R500 { get; set; }
        public decimal? SfC24R500 { get; set; }
        public decimal? SfC25R500 { get; set; }
        public decimal? SfC26R500 { get; set; }
        public decimal? SfC27R500 { get; set; }
        public decimal? SfC28R500 { get; set; }
        public decimal? SfC29R500 { get; set; }
        public string SfC2R520 { get; set; }
        public string SfC3bR520 { get; set; }
        public decimal? SfC4R520 { get; set; }
        public decimal? SfC5R520 { get; set; }
        public decimal? SfC6R520 { get; set; }
        public decimal? SfC7R520 { get; set; }
        public decimal? SfC8R520 { get; set; }
        public decimal? SfC9R520 { get; set; }
        public decimal? SfC10R520 { get; set; }
        public decimal? SfC11R520 { get; set; }
        public decimal? SfC12R520 { get; set; }
        public decimal? SfC13R520 { get; set; }
        public decimal? SfC14R520 { get; set; }
        public decimal? SfC15R520 { get; set; }
        public decimal? SfC16R520 { get; set; }
        public decimal? SfC17R520 { get; set; }
        public decimal? SfC18R520 { get; set; }
        public decimal? SfC19R520 { get; set; }
        public decimal? SfC20R520 { get; set; }
        public decimal? SfC21R520 { get; set; }
        public decimal? SfC22R520 { get; set; }
        public decimal? SfC23R520 { get; set; }
        public decimal? SfC24R520 { get; set; }
        public decimal? SfC25R520 { get; set; }
        public decimal? SfC26R520 { get; set; }
        public decimal? SfC27R520 { get; set; }
        public decimal? SfC28R520 { get; set; }
        public decimal? SfC29R520 { get; set; }
        public string SfC2R620 { get; set; }
        public string SfC3bR620 { get; set; }
        public decimal? SfC4R620 { get; set; }
        public decimal? SfC5R620 { get; set; }
        public decimal? SfC6R620 { get; set; }
        public decimal? SfC7R620 { get; set; }
        public decimal? SfC8R620 { get; set; }
        public decimal? SfC9R620 { get; set; }
        public decimal? SfC10R620 { get; set; }
        public decimal? SfC11R620 { get; set; }
        public decimal? SfC12R620 { get; set; }
        public decimal? SfC13R620 { get; set; }
        public decimal? SfC14R620 { get; set; }
        public decimal? SfC15R620 { get; set; }
        public decimal? SfC16R620 { get; set; }
        public decimal? SfC17R620 { get; set; }
        public decimal? SfC18R620 { get; set; }
        public decimal? SfC19R620 { get; set; }
        public decimal? SfC20R620 { get; set; }
        public decimal? SfC21R620 { get; set; }
        public decimal? SfC22R620 { get; set; }
        public decimal? SfC23R620 { get; set; }
        public decimal? SfC24R620 { get; set; }
        public decimal? SfC25R620 { get; set; }
        public decimal? SfC26R620 { get; set; }
        public decimal? SfC27R620 { get; set; }
        public decimal? SfC28R620 { get; set; }
        public decimal? SfC29R620 { get; set; }
        public string SfC3bR700 { get; set; }
        public decimal? SfC4R700 { get; set; }
        public decimal? SfC5R700 { get; set; }
        public decimal? SfC6R700 { get; set; }
        public decimal? SfC7R700 { get; set; }
        public decimal? SfC8R700 { get; set; }
        public decimal? SfC9R700 { get; set; }
        public decimal? SfC10R700 { get; set; }
        public decimal? SfC11R700 { get; set; }
        public decimal? SfC12R700 { get; set; }
        public decimal? SfC13R700 { get; set; }
        public decimal? SfC14R700 { get; set; }
        public decimal? SfC15R700 { get; set; }
        public decimal? SfC16R700 { get; set; }
        public decimal? SfC17R700 { get; set; }
        public decimal? SfC18R700 { get; set; }
        public decimal? SfC19R700 { get; set; }
        public decimal? SfC20R700 { get; set; }
        public decimal? SfC21R700 { get; set; }
        public decimal? SfC22R700 { get; set; }
        public decimal? SfC23R700 { get; set; }
        public decimal? SfC24R700 { get; set; }
        public decimal? SfC25R700 { get; set; }
        public decimal? SfC26R700 { get; set; }
        public decimal? SfC27R700 { get; set; }
        public decimal? SfC28R700 { get; set; }
        public decimal? SfC29R700 { get; set; }
        public string SfC2R710 { get; set; }
        public decimal? SfC4R710 { get; set; }
        public decimal? SfC5R710 { get; set; }
        public decimal? SfC6R710 { get; set; }
        public decimal? SfC7R710 { get; set; }
        public decimal? SfC8R710 { get; set; }
        public decimal? SfC9R710 { get; set; }
        public decimal? SfC10R710 { get; set; }
        public decimal? SfC11R710 { get; set; }
        public decimal? SfC12R710 { get; set; }
        public decimal? SfC13R710 { get; set; }
        public decimal? SfC14R710 { get; set; }
        public decimal? SfC15R710 { get; set; }
        public decimal? SfC16R710 { get; set; }
        public decimal? SfC17R710 { get; set; }
        public decimal? SfC18R710 { get; set; }
        public decimal? SfC19R710 { get; set; }
        public decimal? SfC20R710 { get; set; }
        public decimal? SfC21R710 { get; set; }
        public decimal? SfC22R710 { get; set; }
        public decimal? SfC23R710 { get; set; }
        public decimal? SfC24R710 { get; set; }
        public decimal? SfC25R710 { get; set; }
        public decimal? SfC26R710 { get; set; }
        public decimal? SfC27R710 { get; set; }
        public decimal? SfC28R710 { get; set; }
        public decimal? SfC29R710 { get; set; }
        public string SfC2R720 { get; set; }
        public decimal? SfC4R720 { get; set; }
        public decimal? SfC5R720 { get; set; }
        public decimal? SfC6R720 { get; set; }
        public decimal? SfC7R720 { get; set; }
        public decimal? SfC8R720 { get; set; }
        public decimal? SfC9R720 { get; set; }
        public decimal? SfC10R720 { get; set; }
        public decimal? SfC11R720 { get; set; }
        public decimal? SfC12R720 { get; set; }
        public decimal? SfC13R720 { get; set; }
        public decimal? SfC14R720 { get; set; }
        public decimal? SfC15R720 { get; set; }
        public decimal? SfC16R720 { get; set; }
        public decimal? SfC17R720 { get; set; }
        public decimal? SfC18R720 { get; set; }
        public decimal? SfC19R720 { get; set; }
        public decimal? SfC20R720 { get; set; }
        public decimal? SfC21R720 { get; set; }
        public decimal? SfC22R720 { get; set; }
        public decimal? SfC23R720 { get; set; }
        public decimal? SfC24R720 { get; set; }
        public decimal? SfC25R720 { get; set; }
        public decimal? SfC26R720 { get; set; }
        public decimal? SfC27R720 { get; set; }
        public decimal? SfC28R720 { get; set; }
        public decimal? SfC29R720 { get; set; }
        public string SfC3bR7001 { get; set; }
        public decimal? SfC4R7001 { get; set; }
        public decimal? SfC5R7001 { get; set; }
        public decimal? SfC6R7001 { get; set; }
        public decimal? SfC7R7001 { get; set; }
        public decimal? SfC8R7001 { get; set; }
        public decimal? SfC9R7001 { get; set; }
        public decimal? SfC10R7001 { get; set; }
        public decimal? SfC11R7001 { get; set; }
        public decimal? SfC12R7001 { get; set; }
        public decimal? SfC13R7001 { get; set; }
        public decimal? SfC14R7001 { get; set; }
        public decimal? SfC15R7001 { get; set; }
        public decimal? SfC16R7001 { get; set; }
        public decimal? SfC17R7001 { get; set; }
        public decimal? SfC18R7001 { get; set; }
        public decimal? SfC19R7001 { get; set; }
        public decimal? SfC20R7001 { get; set; }
        public decimal? SfC21R7001 { get; set; }
        public decimal? SfC22R7001 { get; set; }
        public decimal? SfC23R7001 { get; set; }
        public decimal? SfC24R7001 { get; set; }
        public decimal? SfC25R7001 { get; set; }
        public decimal? SfC26R7001 { get; set; }
        public decimal? SfC27R7001 { get; set; }
        public decimal? SfC28R7001 { get; set; }
        public decimal? SfC29R7001 { get; set; }
        public string SfC3bR7002 { get; set; }
        public decimal? SfC4R7002 { get; set; }
        public decimal? SfC5R7002 { get; set; }
        public decimal? SfC6R7002 { get; set; }
        public decimal? SfC7R7002 { get; set; }
        public decimal? SfC8R7002 { get; set; }
        public decimal? SfC9R7002 { get; set; }
        public decimal? SfC10R7002 { get; set; }
        public decimal? SfC11R7002 { get; set; }
        public decimal? SfC12R7002 { get; set; }
        public decimal? SfC13R7002 { get; set; }
        public decimal? SfC14R7002 { get; set; }
        public decimal? SfC15R7002 { get; set; }
        public decimal? SfC16R7002 { get; set; }
        public decimal? SfC17R7002 { get; set; }
        public decimal? SfC18R7002 { get; set; }
        public decimal? SfC19R7002 { get; set; }
        public decimal? SfC20R7002 { get; set; }
        public decimal? SfC21R7002 { get; set; }
        public decimal? SfC22R7002 { get; set; }
        public decimal? SfC23R7002 { get; set; }
        public decimal? SfC24R7002 { get; set; }
        public decimal? SfC25R7002 { get; set; }
        public decimal? SfC26R7002 { get; set; }
        public decimal? SfC27R7002 { get; set; }
        public decimal? SfC28R7002 { get; set; }
        public decimal? SfC29R7002 { get; set; }
        public string SfC3bR710 { get; set; }
        public string SfC3bR720 { get; set; }
        public string Guid317 { get; set; }
        public string TelIsp { get; set; }

        public virtual ICollection<FsBeTabr2317List> FsBeTabr2317List { get; set; }
        public virtual ICollection<FsBrTabr1317List> FsBrTabr1317List { get; set; }
        public virtual ICollection<FsKrTab4317List> FsKrTab4317List { get; set; }
        public virtual ICollection<FsSfTab3a317List> FsSfTab3a317List { get; set; }
        public virtual ICollection<FsSfTab3b317List> FsSfTab3b317List { get; set; }
        public virtual ICollection<FsSfTab3c317List> FsSfTab3c317List { get; set; }
        public virtual ICollection<FsSfTab3d317List> FsSfTab3d317List { get; set; }
    }
}
