using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcArpinformnonfina0503168
    {
        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public decimal? InfmovaccC4R4501 { get; set; }
        public decimal? InfmovaccC4R451 { get; set; }
        public decimal? InfmovaccC4R480 { get; set; }
        public decimal? InfmovaccC4R481 { get; set; }
        public decimal? InfmovaccC4R483 { get; set; }
        public decimal? InfmovaccC4R520 { get; set; }
        public decimal? InfmovaccC4R521 { get; set; }
        public decimal? InfmovaccC4R523 { get; set; }
        public decimal? InfmovaccC4R540 { get; set; }
        public decimal? InfmovaccC4R542 { get; set; }
        public decimal? InfmovaccC4R550 { get; set; }
        public decimal? InfmovaccC4R552 { get; set; }
        public decimal? InfmovaccC4R560 { get; set; }
        public decimal? InfmovaccC4R562 { get; set; }
        public decimal? InfmovaccC5R4501 { get; set; }
        public decimal? InfmovaccC5R451 { get; set; }
        public decimal? InfmovaccC5R480 { get; set; }
        public decimal? InfmovaccC5R481 { get; set; }
        public decimal? InfmovaccC5R483 { get; set; }
        public decimal? InfmovaccC5R520 { get; set; }
        public decimal? InfmovaccC5R521 { get; set; }
        public decimal? InfmovaccC5R523 { get; set; }
        public decimal? InfmovaccC5R540 { get; set; }
        public decimal? InfmovaccC5R542 { get; set; }
        public decimal? InfmovaccC5R550 { get; set; }
        public decimal? InfmovaccC5R552 { get; set; }
        public decimal? InfmovaccC5R560 { get; set; }
        public decimal? InfmovaccC5R562 { get; set; }
        public decimal? InfmovaccC6R4501 { get; set; }
        public decimal? InfmovaccC6R451 { get; set; }
        public decimal? InfmovaccC6R480 { get; set; }
        public decimal? InfmovaccC6R481 { get; set; }
        public decimal? InfmovaccC6R483 { get; set; }
        public decimal? InfmovaccC6R520 { get; set; }
        public decimal? InfmovaccC6R521 { get; set; }
        public decimal? InfmovaccC6R523 { get; set; }
        public decimal? InfmovaccC6R540 { get; set; }
        public decimal? InfmovaccC6R542 { get; set; }
        public decimal? InfmovaccC6R550 { get; set; }
        public decimal? InfmovaccC6R552 { get; set; }
        public decimal? InfmovaccC6R560 { get; set; }
        public decimal? InfmovaccC6R562 { get; set; }
        public decimal? InfmovaccC7R4501 { get; set; }
        public decimal? InfmovaccC7R451 { get; set; }
        public decimal? InfmovaccC7R480 { get; set; }
        public decimal? InfmovaccC7R481 { get; set; }
        public decimal? InfmovaccC7R483 { get; set; }
        public decimal? InfmovaccC7R520 { get; set; }
        public decimal? InfmovaccC7R521 { get; set; }
        public decimal? InfmovaccC7R523 { get; set; }
        public decimal? InfmovaccC7R540 { get; set; }
        public decimal? InfmovaccC7R542 { get; set; }
        public decimal? InfmovaccC7R550 { get; set; }
        public decimal? InfmovaccC7R552 { get; set; }
        public decimal? InfmovaccC7R560 { get; set; }
        public decimal? InfmovaccC7R562 { get; set; }
        public decimal? InfasstreasuryC4R320 { get; set; }
        public decimal? InfasstreasuryC4R330 { get; set; }
        public decimal? InfasstreasuryC4R360 { get; set; }
        public decimal? InfasstreasuryC4R370 { get; set; }
        public decimal? InfasstreasuryC4R380 { get; set; }
        public decimal? InfasstreasuryC5R320 { get; set; }
        public decimal? InfasstreasuryC6R320 { get; set; }
        public decimal? InfasstreasuryC6R330 { get; set; }
        public decimal? InfasstreasuryC7R320 { get; set; }
        public decimal? InfasstreasuryC7R330 { get; set; }
        public decimal? InfasstreasuryC5R360 { get; set; }
        public decimal? InfasstreasuryC5R380 { get; set; }
        public decimal? InfasstreasuryC6R360 { get; set; }
        public decimal? InfasstreasuryC6R370 { get; set; }
        public decimal? InfasstreasuryC6R380 { get; set; }
        public decimal? InfasstreasuryC7R360 { get; set; }
        public decimal? InfasstreasuryC7R370 { get; set; }
        public decimal? InfasstreasuryC7R380 { get; set; }
        public decimal? InfasstreasuryC4R420 { get; set; }
        public decimal? InfasstreasuryC4R430 { get; set; }
        public decimal? InfasstreasuryC4R440 { get; set; }
        public decimal? InfasstreasuryC4R450 { get; set; }
        public decimal? InfasstreasuryC5R420 { get; set; }
        public decimal? InfasstreasuryC5R440 { get; set; }
        public decimal? InfasstreasuryC5R450 { get; set; }
        public decimal? InfasstreasuryC6R420 { get; set; }
        public decimal? InfasstreasuryC6R430 { get; set; }
        public decimal? InfasstreasuryC6R440 { get; set; }
        public decimal? InfasstreasuryC6R450 { get; set; }
        public decimal? InfasstreasuryC7R420 { get; set; }
        public decimal? InfasstreasuryC7R430 { get; set; }
        public decimal? InfasstreasuryC7R440 { get; set; }
        public decimal? InfasstreasuryC7R450 { get; set; }
        public decimal? InfnonfinassetsC4R010 { get; set; }
        public decimal? InfnonfinassetsC5R010 { get; set; }
        public decimal? InfnonfinassetsC6R010 { get; set; }
        public decimal? InfnonfinassetsC7R010 { get; set; }
        public decimal? InfnonfinassetsC4R011 { get; set; }
        public decimal? InfnonfinassetsC4R012 { get; set; }
        public decimal? InfnonfinassetsC4R013 { get; set; }
        public decimal? InfnonfinassetsC4R014 { get; set; }
        public decimal? InfnonfinassetsC4R015 { get; set; }
        public decimal? InfnonfinassetsC4R016 { get; set; }
        public decimal? InfnonfinassetsC4R017 { get; set; }
        public decimal? InfnonfinassetsC4R018 { get; set; }
        public decimal? InfnonfinassetsC4R050 { get; set; }
        public decimal? InfnonfinassetsC4R051 { get; set; }
        public decimal? InfnonfinassetsC4R052 { get; set; }
        public decimal? InfnonfinassetsC4R053 { get; set; }
        public decimal? InfnonfinassetsC4R054 { get; set; }
        public decimal? InfnonfinassetsC4R055 { get; set; }
        public decimal? InfnonfinassetsC4R056 { get; set; }
        public decimal? InfnonfinassetsC4R057 { get; set; }
        public decimal? InfnonfinassetsC4R058 { get; set; }
        public decimal? InfnonfinassetsC4R070 { get; set; }
        public decimal? InfnonfinassetsC4R080 { get; set; }
        public decimal? InfnonfinassetsC4R110 { get; set; }
        public decimal? InfnonfinassetsC4R120 { get; set; }
        public decimal? InfnonfinassetsC4R130 { get; set; }
        public decimal? InfnonfinassetsC4R150 { get; set; }
        public decimal? InfnonfinassetsC4R151 { get; set; }
        public decimal? InfnonfinassetsC4R152 { get; set; }
        public decimal? InfnonfinassetsC4R153 { get; set; }
        public decimal? InfnonfinassetsC4R170 { get; set; }
        public decimal? InfnonfinassetsC4R190 { get; set; }
        public decimal? InfnonfinassetsC4R230 { get; set; }
        public decimal? InfnonfinassetsC4R250 { get; set; }
        public decimal? InfnonfinassetsC5R011 { get; set; }
        public decimal? InfnonfinassetsC5R012 { get; set; }
        public decimal? InfnonfinassetsC5R013 { get; set; }
        public decimal? InfnonfinassetsC5R014 { get; set; }
        public decimal? InfnonfinassetsC5R015 { get; set; }
        public decimal? InfnonfinassetsC5R016 { get; set; }
        public decimal? InfnonfinassetsC5R017 { get; set; }
        public decimal? InfnonfinassetsC5R018 { get; set; }
        public decimal? InfnonfinassetsC5R070 { get; set; }
        public decimal? InfnonfinassetsC5R080 { get; set; }
        public decimal? InfnonfinassetsC5R110 { get; set; }
        public decimal? InfnonfinassetsC5R130 { get; set; }
        public decimal? InfnonfinassetsC5R150 { get; set; }
        public decimal? InfnonfinassetsC5R151 { get; set; }
        public decimal? InfnonfinassetsC5R152 { get; set; }
        public decimal? InfnonfinassetsC5R153 { get; set; }
        public decimal? InfnonfinassetsC5R170 { get; set; }
        public decimal? InfnonfinassetsC5R190 { get; set; }
        public decimal? InfnonfinassetsC5R230 { get; set; }
        public decimal? InfnonfinassetsC5R250 { get; set; }
        public decimal? InfnonfinassetsC6R011 { get; set; }
        public decimal? InfnonfinassetsC6R012 { get; set; }
        public decimal? InfnonfinassetsC6R013 { get; set; }
        public decimal? InfnonfinassetsC6R014 { get; set; }
        public decimal? InfnonfinassetsC6R015 { get; set; }
        public decimal? InfnonfinassetsC6R016 { get; set; }
        public decimal? InfnonfinassetsC6R017 { get; set; }
        public decimal? InfnonfinassetsC6R018 { get; set; }
        public decimal? InfnonfinassetsC6R050 { get; set; }
        public decimal? InfnonfinassetsC6R051 { get; set; }
        public decimal? InfnonfinassetsC6R052 { get; set; }
        public decimal? InfnonfinassetsC6R053 { get; set; }
        public decimal? InfnonfinassetsC6R054 { get; set; }
        public decimal? InfnonfinassetsC6R055 { get; set; }
        public decimal? InfnonfinassetsC6R056 { get; set; }
        public decimal? InfnonfinassetsC6R057 { get; set; }
        public decimal? InfnonfinassetsC6R058 { get; set; }
        public decimal? InfnonfinassetsC6R070 { get; set; }
        public decimal? InfnonfinassetsC6R080 { get; set; }
        public decimal? InfnonfinassetsC6R110 { get; set; }
        public decimal? InfnonfinassetsC6R120 { get; set; }
        public decimal? InfnonfinassetsC6R130 { get; set; }
        public decimal? InfnonfinassetsC6R150 { get; set; }
        public decimal? InfnonfinassetsC6R151 { get; set; }
        public decimal? InfnonfinassetsC6R152 { get; set; }
        public decimal? InfnonfinassetsC6R153 { get; set; }
        public decimal? InfnonfinassetsC6R170 { get; set; }
        public decimal? InfnonfinassetsC6R190 { get; set; }
        public decimal? InfnonfinassetsC6R230 { get; set; }
        public decimal? InfnonfinassetsC6R250 { get; set; }
        public decimal? InfnonfinassetsC7R011 { get; set; }
        public decimal? InfnonfinassetsC7R012 { get; set; }
        public decimal? InfnonfinassetsC7R013 { get; set; }
        public decimal? InfnonfinassetsC7R014 { get; set; }
        public decimal? InfnonfinassetsC7R015 { get; set; }
        public decimal? InfnonfinassetsC7R016 { get; set; }
        public decimal? InfnonfinassetsC7R017 { get; set; }
        public decimal? InfnonfinassetsC7R018 { get; set; }
        public decimal? InfnonfinassetsC7R050 { get; set; }
        public decimal? InfnonfinassetsC7R051 { get; set; }
        public decimal? InfnonfinassetsC7R052 { get; set; }
        public decimal? InfnonfinassetsC7R053 { get; set; }
        public decimal? InfnonfinassetsC7R054 { get; set; }
        public decimal? InfnonfinassetsC7R055 { get; set; }
        public decimal? InfnonfinassetsC7R056 { get; set; }
        public decimal? InfnonfinassetsC7R057 { get; set; }
        public decimal? InfnonfinassetsC7R058 { get; set; }
        public decimal? InfnonfinassetsC7R070 { get; set; }
        public decimal? InfnonfinassetsC7R080 { get; set; }
        public decimal? InfnonfinassetsC7R110 { get; set; }
        public decimal? InfnonfinassetsC7R120 { get; set; }
        public decimal? InfnonfinassetsC7R130 { get; set; }
        public decimal? InfnonfinassetsC7R150 { get; set; }
        public decimal? InfnonfinassetsC7R151 { get; set; }
        public decimal? InfnonfinassetsC7R152 { get; set; }
        public decimal? InfnonfinassetsC7R153 { get; set; }
        public decimal? InfnonfinassetsC7R170 { get; set; }
        public decimal? InfnonfinassetsC7R190 { get; set; }
        public decimal? InfnonfinassetsC7R230 { get; set; }
        public decimal? InfnonfinassetsC7R250 { get; set; }
        public string CodeKvfo { get; set; }
        public string Kindactivity { get; set; }
        public string Surrogat { get; set; }
        public string Namtip { get; set; }
        public string Ord { get; set; }
        public string Subotch { get; set; }
        public string SignLeader { get; set; }
        public string SignChiefAcc { get; set; }
        public string SignLeaderOfFes { get; set; }
        public string SignPostLeader { get; set; }
        public string SignPostChiefAcc { get; set; }
        public string SignPostLeaderOf { get; set; }
        public string SignExecutor { get; set; }
        public string SignPostExecutor { get; set; }
        public string SignPhone { get; set; }
        public string CaCode { get; set; }
        public string CaName { get; set; }
        public string CaOgrn { get; set; }
        public string CaInn { get; set; }
        public string CaKpp { get; set; }
        public string CaCaLeader { get; set; }
        public string CaCaExecutor { get; set; }
        public string CaPostCaLeader { get; set; }
        public string CaPostCaExecutor { get; set; }
        public string CaCaExecutorMail { get; set; }
    }
}
