using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcArpbalance0503130
    {
        public DcArpbalance0503130()
        {
            FsBaT10503130List = new HashSet<FsBaT10503130List>();
            FsBaT20503130List = new HashSet<FsBaT20503130List>();
            FsBaT30503130List = new HashSet<FsBaT30503130List>();
            FsBaT40503130List = new HashSet<FsBaT40503130List>();
            FsBaT50503130List = new HashSet<FsBaT50503130List>();
            FsBaT60503130List = new HashSet<FsBaT60503130List>();
            FsBaT70503130List = new HashSet<FsBaT70503130List>();
            FsBaT80503130List = new HashSet<FsBaT80503130List>();
        }

        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string Surrogat { get; set; }
        public decimal? AssetC3R010 { get; set; }
        public decimal? AssetC4R010 { get; set; }
        public decimal? AssetC5R010 { get; set; }
        public decimal? AssetC6R010 { get; set; }
        public decimal? AssetC7R010 { get; set; }
        public decimal? AssetC8R010 { get; set; }
        public decimal? AssetC3R011 { get; set; }
        public decimal? AssetC4R011 { get; set; }
        public decimal? AssetC5R011 { get; set; }
        public decimal? AssetC6R011 { get; set; }
        public decimal? AssetC7R011 { get; set; }
        public decimal? AssetC8R011 { get; set; }
        public decimal? AssetC3R013 { get; set; }
        public decimal? AssetC4R013 { get; set; }
        public decimal? AssetC5R013 { get; set; }
        public decimal? AssetC6R013 { get; set; }
        public decimal? AssetC7R013 { get; set; }
        public decimal? AssetC8R013 { get; set; }
        public decimal? AssetC3R014 { get; set; }
        public decimal? AssetC4R014 { get; set; }
        public decimal? AssetC5R014 { get; set; }
        public decimal? AssetC6R014 { get; set; }
        public decimal? AssetC7R014 { get; set; }
        public decimal? AssetC8R014 { get; set; }
        public decimal? AssetC3R020 { get; set; }
        public decimal? AssetC4R020 { get; set; }
        public decimal? AssetC5R020 { get; set; }
        public decimal? AssetC6R020 { get; set; }
        public decimal? AssetC7R020 { get; set; }
        public decimal? AssetC8R020 { get; set; }
        public decimal? AssetC3R021 { get; set; }
        public decimal? AssetC4R021 { get; set; }
        public decimal? AssetC5R021 { get; set; }
        public decimal? AssetC6R021 { get; set; }
        public decimal? AssetC7R021 { get; set; }
        public decimal? AssetC8R021 { get; set; }
        public decimal? AssetC3R023 { get; set; }
        public decimal? AssetC4R023 { get; set; }
        public decimal? AssetC5R023 { get; set; }
        public decimal? AssetC6R023 { get; set; }
        public decimal? AssetC7R023 { get; set; }
        public decimal? AssetC8R023 { get; set; }
        public decimal? AssetC3R024 { get; set; }
        public decimal? AssetC4R024 { get; set; }
        public decimal? AssetC5R024 { get; set; }
        public decimal? AssetC6R024 { get; set; }
        public decimal? AssetC7R024 { get; set; }
        public decimal? AssetC8R024 { get; set; }
        public decimal? AssetC3R030 { get; set; }
        public decimal? AssetC4R030 { get; set; }
        public decimal? AssetC5R030 { get; set; }
        public decimal? AssetC6R030 { get; set; }
        public decimal? AssetC7R030 { get; set; }
        public decimal? AssetC8R030 { get; set; }
        public decimal? AssetC3R031 { get; set; }
        public decimal? AssetC4R031 { get; set; }
        public decimal? AssetC5R031 { get; set; }
        public decimal? AssetC6R031 { get; set; }
        public decimal? AssetC7R031 { get; set; }
        public decimal? AssetC8R031 { get; set; }
        public decimal? AssetC3R033 { get; set; }
        public decimal? AssetC4R033 { get; set; }
        public decimal? AssetC5R033 { get; set; }
        public decimal? AssetC6R033 { get; set; }
        public decimal? AssetC7R033 { get; set; }
        public decimal? AssetC8R033 { get; set; }
        public decimal? AssetC3R034 { get; set; }
        public decimal? AssetC4R034 { get; set; }
        public decimal? AssetC5R034 { get; set; }
        public decimal? AssetC6R034 { get; set; }
        public decimal? AssetC7R034 { get; set; }
        public decimal? AssetC8R034 { get; set; }
        public decimal? AssetC3R040 { get; set; }
        public decimal? AssetC4R040 { get; set; }
        public decimal? AssetC5R040 { get; set; }
        public decimal? AssetC6R040 { get; set; }
        public decimal? AssetC7R040 { get; set; }
        public decimal? AssetC8R040 { get; set; }
        public decimal? AssetC3R042 { get; set; }
        public decimal? AssetC4R042 { get; set; }
        public decimal? AssetC5R042 { get; set; }
        public decimal? AssetC6R042 { get; set; }
        public decimal? AssetC7R042 { get; set; }
        public decimal? AssetC8R042 { get; set; }
        public decimal? AssetC3R043 { get; set; }
        public decimal? AssetC4R043 { get; set; }
        public decimal? AssetC5R043 { get; set; }
        public decimal? AssetC6R043 { get; set; }
        public decimal? AssetC7R043 { get; set; }
        public decimal? AssetC8R043 { get; set; }
        public decimal? AssetC3R050 { get; set; }
        public decimal? AssetC4R050 { get; set; }
        public decimal? AssetC5R050 { get; set; }
        public decimal? AssetC6R050 { get; set; }
        public decimal? AssetC7R050 { get; set; }
        public decimal? AssetC8R050 { get; set; }
        public decimal? AssetC3R052 { get; set; }
        public decimal? AssetC4R052 { get; set; }
        public decimal? AssetC5R052 { get; set; }
        public decimal? AssetC6R052 { get; set; }
        public decimal? AssetC7R052 { get; set; }
        public decimal? AssetC8R052 { get; set; }
        public decimal? AssetC3R053 { get; set; }
        public decimal? AssetC4R053 { get; set; }
        public decimal? AssetC5R053 { get; set; }
        public decimal? AssetC6R053 { get; set; }
        public decimal? AssetC7R053 { get; set; }
        public decimal? AssetC8R053 { get; set; }
        public decimal? AssetC3R060 { get; set; }
        public decimal? AssetC4R060 { get; set; }
        public decimal? AssetC5R060 { get; set; }
        public decimal? AssetC6R060 { get; set; }
        public decimal? AssetC7R060 { get; set; }
        public decimal? AssetC8R060 { get; set; }
        public decimal? AssetC3R062 { get; set; }
        public decimal? AssetC4R062 { get; set; }
        public decimal? AssetC5R062 { get; set; }
        public decimal? AssetC6R062 { get; set; }
        public decimal? AssetC7R062 { get; set; }
        public decimal? AssetC8R062 { get; set; }
        public decimal? AssetC3R063 { get; set; }
        public decimal? AssetC4R063 { get; set; }
        public decimal? AssetC5R063 { get; set; }
        public decimal? AssetC6R063 { get; set; }
        public decimal? AssetC7R063 { get; set; }
        public decimal? AssetC8R063 { get; set; }
        public decimal? AssetC3R070 { get; set; }
        public decimal? AssetC4R070 { get; set; }
        public decimal? AssetC5R070 { get; set; }
        public decimal? AssetC6R070 { get; set; }
        public decimal? AssetC7R070 { get; set; }
        public decimal? AssetC8R070 { get; set; }
        public decimal? AssetC3R080 { get; set; }
        public decimal? AssetC4R080 { get; set; }
        public decimal? AssetC5R080 { get; set; }
        public decimal? AssetC6R080 { get; set; }
        public decimal? AssetC7R080 { get; set; }
        public decimal? AssetC8R080 { get; set; }
        public decimal? AssetC3R090 { get; set; }
        public decimal? AssetC4R090 { get; set; }
        public decimal? AssetC5R090 { get; set; }
        public decimal? AssetC6R090 { get; set; }
        public decimal? AssetC7R090 { get; set; }
        public decimal? AssetC8R090 { get; set; }
        public decimal? AssetC3R091 { get; set; }
        public decimal? AssetC4R091 { get; set; }
        public decimal? AssetC5R091 { get; set; }
        public decimal? AssetC6R091 { get; set; }
        public decimal? AssetC7R091 { get; set; }
        public decimal? AssetC8R091 { get; set; }
        public decimal? AssetC3R093 { get; set; }
        public decimal? AssetC4R093 { get; set; }
        public decimal? AssetC5R093 { get; set; }
        public decimal? AssetC6R093 { get; set; }
        public decimal? AssetC7R093 { get; set; }
        public decimal? AssetC8R093 { get; set; }
        public decimal? AssetC3R094 { get; set; }
        public decimal? AssetC4R094 { get; set; }
        public decimal? AssetC5R094 { get; set; }
        public decimal? AssetC6R094 { get; set; }
        public decimal? AssetC7R094 { get; set; }
        public decimal? AssetC8R094 { get; set; }
        public decimal? AssetC3R100 { get; set; }
        public decimal? AssetC4R100 { get; set; }
        public decimal? AssetC5R100 { get; set; }
        public decimal? AssetC6R100 { get; set; }
        public decimal? AssetC7R100 { get; set; }
        public decimal? AssetC8R100 { get; set; }
        public decimal? AssetC3R101 { get; set; }
        public decimal? AssetC4R101 { get; set; }
        public decimal? AssetC5R101 { get; set; }
        public decimal? AssetC6R101 { get; set; }
        public decimal? AssetC7R101 { get; set; }
        public decimal? AssetC8R101 { get; set; }
        public decimal? AssetC3R103 { get; set; }
        public decimal? AssetC4R103 { get; set; }
        public decimal? AssetC5R103 { get; set; }
        public decimal? AssetC6R103 { get; set; }
        public decimal? AssetC7R103 { get; set; }
        public decimal? AssetC8R103 { get; set; }
        public decimal? AssetC3R104 { get; set; }
        public decimal? AssetC4R104 { get; set; }
        public decimal? AssetC5R104 { get; set; }
        public decimal? AssetC6R104 { get; set; }
        public decimal? AssetC7R104 { get; set; }
        public decimal? AssetC8R104 { get; set; }
        public decimal? AssetC3R110 { get; set; }
        public decimal? AssetC4R110 { get; set; }
        public decimal? AssetC5R110 { get; set; }
        public decimal? AssetC6R110 { get; set; }
        public decimal? AssetC7R110 { get; set; }
        public decimal? AssetC8R110 { get; set; }
        public decimal? AssetC3R120 { get; set; }
        public decimal? AssetC4R120 { get; set; }
        public decimal? AssetC5R120 { get; set; }
        public decimal? AssetC6R120 { get; set; }
        public decimal? AssetC7R120 { get; set; }
        public decimal? AssetC8R120 { get; set; }
        public decimal? AssetC3R130 { get; set; }
        public decimal? AssetC4R130 { get; set; }
        public decimal? AssetC5R130 { get; set; }
        public decimal? AssetC6R130 { get; set; }
        public decimal? AssetC7R130 { get; set; }
        public decimal? AssetC8R130 { get; set; }
        public decimal? AssetC3R140 { get; set; }
        public decimal? AssetC4R140 { get; set; }
        public decimal? AssetC5R140 { get; set; }
        public decimal? AssetC6R140 { get; set; }
        public decimal? AssetC7R140 { get; set; }
        public decimal? AssetC8R140 { get; set; }
        public decimal? AssetC3R150 { get; set; }
        public decimal? AssetC4R150 { get; set; }
        public decimal? AssetC5R150 { get; set; }
        public decimal? AssetC6R150 { get; set; }
        public decimal? AssetC7R150 { get; set; }
        public decimal? AssetC8R150 { get; set; }
        public decimal? AssetC3R170 { get; set; }
        public decimal? AssetC4R170 { get; set; }
        public decimal? AssetC5R170 { get; set; }
        public decimal? AssetC6R170 { get; set; }
        public decimal? AssetC7R170 { get; set; }
        public decimal? AssetC8R170 { get; set; }
        public decimal? AssetC3R171 { get; set; }
        public decimal? AssetC4R171 { get; set; }
        public decimal? AssetC5R171 { get; set; }
        public decimal? AssetC6R171 { get; set; }
        public decimal? AssetC7R171 { get; set; }
        public decimal? AssetC8R171 { get; set; }
        public decimal? AssetC3R172 { get; set; }
        public decimal? AssetC4R172 { get; set; }
        public decimal? AssetC5R172 { get; set; }
        public decimal? AssetC6R172 { get; set; }
        public decimal? AssetC7R172 { get; set; }
        public decimal? AssetC8R172 { get; set; }
        public decimal? AssetC3R173 { get; set; }
        public decimal? AssetC4R173 { get; set; }
        public decimal? AssetC5R173 { get; set; }
        public decimal? AssetC6R173 { get; set; }
        public decimal? AssetC7R173 { get; set; }
        public decimal? AssetC8R173 { get; set; }
        public decimal? AssetC3R174 { get; set; }
        public decimal? AssetC4R174 { get; set; }
        public decimal? AssetC5R174 { get; set; }
        public decimal? AssetC6R174 { get; set; }
        public decimal? AssetC7R174 { get; set; }
        public decimal? AssetC8R174 { get; set; }
        public decimal? AssetC3R175 { get; set; }
        public decimal? AssetC4R175 { get; set; }
        public decimal? AssetC5R175 { get; set; }
        public decimal? AssetC6R175 { get; set; }
        public decimal? AssetC7R175 { get; set; }
        public decimal? AssetC8R175 { get; set; }
        public decimal? AssetC3R176 { get; set; }
        public decimal? AssetC4R176 { get; set; }
        public decimal? AssetC5R176 { get; set; }
        public decimal? AssetC6R176 { get; set; }
        public decimal? AssetC7R176 { get; set; }
        public decimal? AssetC8R176 { get; set; }
        public decimal? AssetC3R177 { get; set; }
        public decimal? AssetC4R177 { get; set; }
        public decimal? AssetC5R177 { get; set; }
        public decimal? AssetC6R177 { get; set; }
        public decimal? AssetC7R177 { get; set; }
        public decimal? AssetC8R177 { get; set; }
        public decimal? AssetC3R178 { get; set; }
        public decimal? AssetC4R178 { get; set; }
        public decimal? AssetC5R178 { get; set; }
        public decimal? AssetC6R178 { get; set; }
        public decimal? AssetC7R178 { get; set; }
        public decimal? AssetC8R178 { get; set; }
        public decimal? AssetC3R179 { get; set; }
        public decimal? AssetC4R179 { get; set; }
        public decimal? AssetC5R179 { get; set; }
        public decimal? AssetC6R179 { get; set; }
        public decimal? AssetC7R179 { get; set; }
        public decimal? AssetC8R179 { get; set; }
        public decimal? AssetC3R210 { get; set; }
        public decimal? AssetC4R210 { get; set; }
        public decimal? AssetC5R210 { get; set; }
        public decimal? AssetC6R210 { get; set; }
        public decimal? AssetC7R210 { get; set; }
        public decimal? AssetC8R210 { get; set; }
        public decimal? AssetC3R211 { get; set; }
        public decimal? AssetC4R211 { get; set; }
        public decimal? AssetC5R211 { get; set; }
        public decimal? AssetC6R211 { get; set; }
        public decimal? AssetC7R211 { get; set; }
        public decimal? AssetC8R211 { get; set; }
        public decimal? AssetC3R212 { get; set; }
        public decimal? AssetC4R212 { get; set; }
        public decimal? AssetC5R212 { get; set; }
        public decimal? AssetC6R212 { get; set; }
        public decimal? AssetC7R212 { get; set; }
        public decimal? AssetC8R212 { get; set; }
        public decimal? AssetC3R213 { get; set; }
        public decimal? AssetC4R213 { get; set; }
        public decimal? AssetC5R213 { get; set; }
        public decimal? AssetC6R213 { get; set; }
        public decimal? AssetC7R213 { get; set; }
        public decimal? AssetC8R213 { get; set; }
        public decimal? AssetC3R230 { get; set; }
        public decimal? AssetC4R230 { get; set; }
        public decimal? AssetC5R230 { get; set; }
        public decimal? AssetC6R230 { get; set; }
        public decimal? AssetC7R230 { get; set; }
        public decimal? AssetC8R230 { get; set; }
        public decimal? AssetC3R260 { get; set; }
        public decimal? AssetC4R260 { get; set; }
        public decimal? AssetC5R260 { get; set; }
        public decimal? AssetC6R260 { get; set; }
        public decimal? AssetC7R260 { get; set; }
        public decimal? AssetC8R260 { get; set; }
        public decimal? AssetC3R290 { get; set; }
        public decimal? AssetC4R290 { get; set; }
        public decimal? AssetC5R290 { get; set; }
        public decimal? AssetC6R290 { get; set; }
        public decimal? AssetC7R290 { get; set; }
        public decimal? AssetC8R290 { get; set; }
        public decimal? AssetC3R291 { get; set; }
        public decimal? AssetC4R291 { get; set; }
        public decimal? AssetC5R291 { get; set; }
        public decimal? AssetC6R291 { get; set; }
        public decimal? AssetC7R291 { get; set; }
        public decimal? AssetC8R291 { get; set; }
        public decimal? AssetC3R292 { get; set; }
        public decimal? AssetC4R292 { get; set; }
        public decimal? AssetC5R292 { get; set; }
        public decimal? AssetC6R292 { get; set; }
        public decimal? AssetC7R292 { get; set; }
        public decimal? AssetC8R292 { get; set; }
        public decimal? AssetC3R293 { get; set; }
        public decimal? AssetC4R293 { get; set; }
        public decimal? AssetC5R293 { get; set; }
        public decimal? AssetC6R293 { get; set; }
        public decimal? AssetC7R293 { get; set; }
        public decimal? AssetC8R293 { get; set; }
        public decimal? AssetC3R310 { get; set; }
        public decimal? AssetC4R310 { get; set; }
        public decimal? AssetC5R310 { get; set; }
        public decimal? AssetC6R310 { get; set; }
        public decimal? AssetC7R310 { get; set; }
        public decimal? AssetC8R310 { get; set; }
        public decimal? AssetC3R320 { get; set; }
        public decimal? AssetC4R320 { get; set; }
        public decimal? AssetC5R320 { get; set; }
        public decimal? AssetC6R320 { get; set; }
        public decimal? AssetC7R320 { get; set; }
        public decimal? AssetC8R320 { get; set; }
        public decimal? AssetC3R330 { get; set; }
        public decimal? AssetC4R330 { get; set; }
        public decimal? AssetC5R330 { get; set; }
        public decimal? AssetC6R330 { get; set; }
        public decimal? AssetC7R330 { get; set; }
        public decimal? AssetC8R330 { get; set; }
        public decimal? AssetC3R331 { get; set; }
        public decimal? AssetC4R331 { get; set; }
        public decimal? AssetC5R331 { get; set; }
        public decimal? AssetC6R331 { get; set; }
        public decimal? AssetC7R331 { get; set; }
        public decimal? AssetC8R331 { get; set; }
        public decimal? AssetC3R333 { get; set; }
        public decimal? AssetC4R333 { get; set; }
        public decimal? AssetC5R333 { get; set; }
        public decimal? AssetC6R333 { get; set; }
        public decimal? AssetC7R333 { get; set; }
        public decimal? AssetC8R333 { get; set; }
        public decimal? AssetC3R370 { get; set; }
        public decimal? AssetC4R370 { get; set; }
        public decimal? AssetC5R370 { get; set; }
        public decimal? AssetC6R370 { get; set; }
        public decimal? AssetC7R370 { get; set; }
        public decimal? AssetC8R370 { get; set; }
        public decimal? AssetC3R371 { get; set; }
        public decimal? AssetC4R371 { get; set; }
        public decimal? AssetC5R371 { get; set; }
        public decimal? AssetC6R371 { get; set; }
        public decimal? AssetC7R371 { get; set; }
        public decimal? AssetC8R371 { get; set; }
        public decimal? AssetC3R372 { get; set; }
        public decimal? AssetC4R372 { get; set; }
        public decimal? AssetC5R372 { get; set; }
        public decimal? AssetC6R372 { get; set; }
        public decimal? AssetC7R372 { get; set; }
        public decimal? AssetC8R372 { get; set; }
        public decimal? AssetC3R373 { get; set; }
        public decimal? AssetC4R373 { get; set; }
        public decimal? AssetC5R373 { get; set; }
        public decimal? AssetC6R373 { get; set; }
        public decimal? AssetC7R373 { get; set; }
        public decimal? AssetC8R373 { get; set; }
        public decimal? AssetC3R400 { get; set; }
        public decimal? AssetC4R400 { get; set; }
        public decimal? AssetC5R400 { get; set; }
        public decimal? AssetC6R400 { get; set; }
        public decimal? AssetC7R400 { get; set; }
        public decimal? AssetC8R400 { get; set; }
        public decimal? AssetC3R410 { get; set; }
        public decimal? AssetC4R410 { get; set; }
        public decimal? AssetC5R410 { get; set; }
        public decimal? AssetC6R410 { get; set; }
        public decimal? AssetC7R410 { get; set; }
        public decimal? AssetC8R410 { get; set; }
        public decimal? LiabilityC3R470 { get; set; }
        public decimal? LiabilityC4R470 { get; set; }
        public decimal? LiabilityC5R470 { get; set; }
        public decimal? LiabilityC6R470 { get; set; }
        public decimal? LiabilityC7R470 { get; set; }
        public decimal? LiabilityC8R470 { get; set; }
        public decimal? LiabilityC3R471 { get; set; }
        public decimal? LiabilityC4R471 { get; set; }
        public decimal? LiabilityC5R471 { get; set; }
        public decimal? LiabilityC6R471 { get; set; }
        public decimal? LiabilityC7R471 { get; set; }
        public decimal? LiabilityC8R471 { get; set; }
        public decimal? LiabilityC3R472 { get; set; }
        public decimal? LiabilityC4R472 { get; set; }
        public decimal? LiabilityC5R472 { get; set; }
        public decimal? LiabilityC6R472 { get; set; }
        public decimal? LiabilityC7R472 { get; set; }
        public decimal? LiabilityC8R472 { get; set; }
        public decimal? LiabilityC3R473 { get; set; }
        public decimal? LiabilityC4R473 { get; set; }
        public decimal? LiabilityC5R473 { get; set; }
        public decimal? LiabilityC6R473 { get; set; }
        public decimal? LiabilityC7R473 { get; set; }
        public decimal? LiabilityC8R473 { get; set; }
        public decimal? LiabilityC3R474 { get; set; }
        public decimal? LiabilityC4R474 { get; set; }
        public decimal? LiabilityC5R474 { get; set; }
        public decimal? LiabilityC6R474 { get; set; }
        public decimal? LiabilityC7R474 { get; set; }
        public decimal? LiabilityC8R474 { get; set; }
        public decimal? LiabilityC3R490 { get; set; }
        public decimal? LiabilityC4R490 { get; set; }
        public decimal? LiabilityC5R490 { get; set; }
        public decimal? LiabilityC6R490 { get; set; }
        public decimal? LiabilityC7R490 { get; set; }
        public decimal? LiabilityC8R490 { get; set; }
        public decimal? LiabilityC3R510 { get; set; }
        public decimal? LiabilityC4R510 { get; set; }
        public decimal? LiabilityC5R510 { get; set; }
        public decimal? LiabilityC6R510 { get; set; }
        public decimal? LiabilityC7R510 { get; set; }
        public decimal? LiabilityC8R510 { get; set; }
        public decimal? LiabilityC3R511 { get; set; }
        public decimal? LiabilityC4R511 { get; set; }
        public decimal? LiabilityC5R511 { get; set; }
        public decimal? LiabilityC6R511 { get; set; }
        public decimal? LiabilityC7R511 { get; set; }
        public decimal? LiabilityC8R511 { get; set; }
        public decimal? LiabilityC3R512 { get; set; }
        public decimal? LiabilityC4R512 { get; set; }
        public decimal? LiabilityC5R512 { get; set; }
        public decimal? LiabilityC6R512 { get; set; }
        public decimal? LiabilityC7R512 { get; set; }
        public decimal? LiabilityC8R512 { get; set; }
        public decimal? LiabilityC3R513 { get; set; }
        public decimal? LiabilityC4R513 { get; set; }
        public decimal? LiabilityC5R513 { get; set; }
        public decimal? LiabilityC6R513 { get; set; }
        public decimal? LiabilityC7R513 { get; set; }
        public decimal? LiabilityC8R513 { get; set; }
        public decimal? LiabilityC3R514 { get; set; }
        public decimal? LiabilityC4R514 { get; set; }
        public decimal? LiabilityC5R514 { get; set; }
        public decimal? LiabilityC6R514 { get; set; }
        public decimal? LiabilityC7R514 { get; set; }
        public decimal? LiabilityC8R514 { get; set; }
        public decimal? LiabilityC3R515 { get; set; }
        public decimal? LiabilityC4R515 { get; set; }
        public decimal? LiabilityC5R515 { get; set; }
        public decimal? LiabilityC6R515 { get; set; }
        public decimal? LiabilityC7R515 { get; set; }
        public decimal? LiabilityC8R515 { get; set; }
        public decimal? LiabilityC3R516 { get; set; }
        public decimal? LiabilityC4R516 { get; set; }
        public decimal? LiabilityC5R516 { get; set; }
        public decimal? LiabilityC6R516 { get; set; }
        public decimal? LiabilityC7R516 { get; set; }
        public decimal? LiabilityC8R516 { get; set; }
        public decimal? LiabilityC3R530 { get; set; }
        public decimal? LiabilityC4R530 { get; set; }
        public decimal? LiabilityC5R530 { get; set; }
        public decimal? LiabilityC6R530 { get; set; }
        public decimal? LiabilityC7R530 { get; set; }
        public decimal? LiabilityC8R530 { get; set; }
        public decimal? LiabilityC4R531 { get; set; }
        public decimal? LiabilityC5R531 { get; set; }
        public decimal? LiabilityC7R531 { get; set; }
        public decimal? LiabilityC8R531 { get; set; }
        public decimal? LiabilityC3R532 { get; set; }
        public decimal? LiabilityC4R532 { get; set; }
        public decimal? LiabilityC5R532 { get; set; }
        public decimal? LiabilityC6R532 { get; set; }
        public decimal? LiabilityC7R532 { get; set; }
        public decimal? LiabilityC8R532 { get; set; }
        public decimal? LiabilityC3R533 { get; set; }
        public decimal? LiabilityC4R533 { get; set; }
        public decimal? LiabilityC5R533 { get; set; }
        public decimal? LiabilityC6R533 { get; set; }
        public decimal? LiabilityC7R533 { get; set; }
        public decimal? LiabilityC8R533 { get; set; }
        public decimal? LiabilityC3R534 { get; set; }
        public decimal? LiabilityC4R534 { get; set; }
        public decimal? LiabilityC5R534 { get; set; }
        public decimal? LiabilityC6R534 { get; set; }
        public decimal? LiabilityC7R534 { get; set; }
        public decimal? LiabilityC8R534 { get; set; }
        public decimal? LiabilityC3R600 { get; set; }
        public decimal? LiabilityC4R600 { get; set; }
        public decimal? LiabilityC5R600 { get; set; }
        public decimal? LiabilityC6R600 { get; set; }
        public decimal? LiabilityC7R600 { get; set; }
        public decimal? LiabilityC8R600 { get; set; }
        public decimal? LiabilityC3R620 { get; set; }
        public decimal? LiabilityC4R620 { get; set; }
        public decimal? LiabilityC5R620 { get; set; }
        public decimal? LiabilityC6R620 { get; set; }
        public decimal? LiabilityC7R620 { get; set; }
        public decimal? LiabilityC8R620 { get; set; }
        public decimal? LiabilityC3R623 { get; set; }
        public decimal? LiabilityC4R623 { get; set; }
        public decimal? LiabilityC5R623 { get; set; }
        public decimal? LiabilityC6R623 { get; set; }
        public decimal? LiabilityC7R623 { get; set; }
        public decimal? LiabilityC8R623 { get; set; }
        public decimal? LiabilityC3R624 { get; set; }
        public decimal? LiabilityC4R624 { get; set; }
        public decimal? LiabilityC5R624 { get; set; }
        public decimal? LiabilityC6R624 { get; set; }
        public decimal? LiabilityC7R624 { get; set; }
        public decimal? LiabilityC8R624 { get; set; }
        public decimal? LiabilityC3R625 { get; set; }
        public decimal? LiabilityC4R625 { get; set; }
        public decimal? LiabilityC5R625 { get; set; }
        public decimal? LiabilityC6R625 { get; set; }
        public decimal? LiabilityC7R625 { get; set; }
        public decimal? LiabilityC8R625 { get; set; }
        public decimal? LiabilityC3R900 { get; set; }
        public decimal? LiabilityC4R900 { get; set; }
        public decimal? LiabilityC5R900 { get; set; }
        public decimal? LiabilityC6R900 { get; set; }
        public decimal? LiabilityC7R900 { get; set; }
        public decimal? LiabilityC8R900 { get; set; }
        public decimal? BaC4R010 { get; set; }
        public decimal? BaC5R010 { get; set; }
        public decimal? BaC4R011 { get; set; }
        public decimal? BaC5R011 { get; set; }
        public decimal? BaC4R012 { get; set; }
        public decimal? BaC5R012 { get; set; }
        public decimal? BaC4R015 { get; set; }
        public decimal? BaC5R015 { get; set; }
        public decimal? BaC4R016 { get; set; }
        public decimal? BaC5R016 { get; set; }
        public decimal? BaC4R020 { get; set; }
        public decimal? BaC5R020 { get; set; }
        public decimal? BaC4R030 { get; set; }
        public decimal? BaC5R030 { get; set; }
        public decimal? BaC4R040 { get; set; }
        public decimal? BaC5R040 { get; set; }
        public decimal? BaC4R050 { get; set; }
        public decimal? BaC5R050 { get; set; }
        public decimal? BaC4R051 { get; set; }
        public decimal? BaC5R051 { get; set; }
        public decimal? BaC4R054 { get; set; }
        public decimal? BaC5R054 { get; set; }
        public decimal? BaC4R060 { get; set; }
        public decimal? BaC5R060 { get; set; }
        public decimal? BaC4R070 { get; set; }
        public decimal? BaC5R070 { get; set; }
        public decimal? BaC4R071 { get; set; }
        public decimal? BaC5R071 { get; set; }
        public decimal? BaC4R072 { get; set; }
        public decimal? BaC5R072 { get; set; }
        public decimal? BaC4R080 { get; set; }
        public decimal? BaC5R080 { get; set; }
        public decimal? BaC4R090 { get; set; }
        public decimal? BaC5R090 { get; set; }
        public decimal? BaC4R100 { get; set; }
        public decimal? BaC5R100 { get; set; }
        public decimal? BaC4R101 { get; set; }
        public decimal? BaC5R101 { get; set; }
        public decimal? BaC4R102 { get; set; }
        public decimal? BaC5R102 { get; set; }
        public decimal? BaC4R103 { get; set; }
        public decimal? BaC5R103 { get; set; }
        public decimal? BaC4R104 { get; set; }
        public decimal? BaC5R104 { get; set; }
        public decimal? BaC4R105 { get; set; }
        public decimal? BaC5R105 { get; set; }
        public decimal? BaC4R110 { get; set; }
        public decimal? BaC5R110 { get; set; }
        public decimal? BaC4R111 { get; set; }
        public decimal? BaC5R111 { get; set; }
        public decimal? BaC4R112 { get; set; }
        public decimal? BaC5R112 { get; set; }
        public decimal? BaC4R120 { get; set; }
        public decimal? BaC5R120 { get; set; }
        public decimal? BaC4R130 { get; set; }
        public decimal? BaC5R130 { get; set; }
        public decimal? BaC4R140 { get; set; }
        public decimal? BaC5R140 { get; set; }
        public decimal? BaC4R150 { get; set; }
        public decimal? BaC5R150 { get; set; }
        public decimal? BaC4R160 { get; set; }
        public decimal? BaC5R160 { get; set; }
        public decimal? BaC5R170 { get; set; }
        public decimal? BaC5R171 { get; set; }
        public decimal? BaC5R172 { get; set; }
        public decimal? BaC5R173 { get; set; }
        public decimal? BaC5R180 { get; set; }
        public decimal? BaC5R181 { get; set; }
        public decimal? BaC5R182 { get; set; }
        public decimal? BaC4R190 { get; set; }
        public decimal? BaC5R190 { get; set; }
        public decimal? BaC4R200 { get; set; }
        public decimal? BaC5R200 { get; set; }
        public decimal? BaC4R210 { get; set; }
        public decimal? BaC5R210 { get; set; }
        public decimal? BaC4R220 { get; set; }
        public decimal? BaC5R220 { get; set; }
        public decimal? BaC4R221 { get; set; }
        public decimal? BaC5R221 { get; set; }
        public decimal? BaC4R224 { get; set; }
        public decimal? BaC5R224 { get; set; }
        public decimal? BaC4R230 { get; set; }
        public decimal? BaC5R230 { get; set; }
        public decimal? BaC4R240 { get; set; }
        public decimal? BaC5R240 { get; set; }
        public decimal? BaC4R241 { get; set; }
        public decimal? BaC5R241 { get; set; }
        public decimal? BaC4R242 { get; set; }
        public decimal? BaC5R242 { get; set; }
        public decimal? BaC4R244 { get; set; }
        public decimal? BaC5R244 { get; set; }
        public decimal? BaC4R246 { get; set; }
        public decimal? BaC5R246 { get; set; }
        public decimal? BaC4R248 { get; set; }
        public decimal? BaC5R248 { get; set; }
        public decimal? BaC4R249 { get; set; }
        public decimal? BaC5R249 { get; set; }
        public decimal? BaC4R250 { get; set; }
        public decimal? BaC5R250 { get; set; }
        public decimal? BaC4R251 { get; set; }
        public decimal? BaC5R251 { get; set; }
        public decimal? BaC4R252 { get; set; }
        public decimal? BaC5R252 { get; set; }
        public decimal? BaC4R254 { get; set; }
        public decimal? BaC5R254 { get; set; }
        public decimal? BaC4R256 { get; set; }
        public decimal? BaC5R256 { get; set; }
        public decimal? BaC4R258 { get; set; }
        public decimal? BaC5R258 { get; set; }
        public decimal? BaC4R260 { get; set; }
        public decimal? BaC5R260 { get; set; }
        public decimal? BaC4R261 { get; set; }
        public decimal? BaC5R261 { get; set; }
        public decimal? BaC4R262 { get; set; }
        public decimal? BaC5R262 { get; set; }
        public decimal? BaC4R264 { get; set; }
        public decimal? BaC5R264 { get; set; }
        public decimal? BaC4R266 { get; set; }
        public decimal? BaC5R266 { get; set; }
        public decimal? BaC4R268 { get; set; }
        public decimal? BaC5R268 { get; set; }
        public decimal? BaC4R270 { get; set; }
        public decimal? BaC5R270 { get; set; }
        public decimal? BaC4R280 { get; set; }
        public decimal? BaC5R280 { get; set; }
        public decimal? BaC4R290 { get; set; }
        public decimal? BaC5R290 { get; set; }
        public decimal? BaC4R300 { get; set; }
        public decimal? BaC5R300 { get; set; }
        public decimal? BaC4R310 { get; set; }
        public decimal? BaC5R310 { get; set; }
        public string PfnLeader { get; set; }
        public string PfnChiefAcc { get; set; }
        public string PfnLeaderOfFes { get; set; }
        public string PfnPostLeader { get; set; }
        public string PfnPostChiefAcc { get; set; }
        public string PfnPostLeaderOf { get; set; }
        public string PfnExecutor { get; set; }
        public string PfnPostExecutor { get; set; }
        public string PfnPhone { get; set; }
        public string HrNamtip { get; set; }
        public string HrSubotch { get; set; }
        public string Ord { get; set; }

        public virtual ICollection<FsBaT10503130List> FsBaT10503130List { get; set; }
        public virtual ICollection<FsBaT20503130List> FsBaT20503130List { get; set; }
        public virtual ICollection<FsBaT30503130List> FsBaT30503130List { get; set; }
        public virtual ICollection<FsBaT40503130List> FsBaT40503130List { get; set; }
        public virtual ICollection<FsBaT50503130List> FsBaT50503130List { get; set; }
        public virtual ICollection<FsBaT60503130List> FsBaT60503130List { get; set; }
        public virtual ICollection<FsBaT70503130List> FsBaT70503130List { get; set; }
        public virtual ICollection<FsBaT80503130List> FsBaT80503130List { get; set; }
    }
}
