using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcArprep0503730
    {
        public DcArprep0503730()
        {
            FsClClList = new HashSet<FsClClList>();
            FsFaFaList = new HashSet<FsFaFaList>();
            FsFrFrList = new HashSet<FsFrFrList>();
            FsInfoFixas730List = new HashSet<FsInfoFixas730List>();
            FsInfoFrst730List = new HashSet<FsInfoFrst730List>();
            FsInfoInsdeb730List = new HashSet<FsInfoInsdeb730List>();
            FsInfoInskr730List = new HashSet<FsInfoInskr730List>();
            FsInfoMatval730List = new HashSet<FsInfoMatval730List>();
            FsInfoProprent730List = new HashSet<FsInfoProprent730List>();
            FsInfoPropuse730List = new HashSet<FsInfoPropuse730List>();
            FsInfoProtran730List = new HashSet<FsInfoProtran730List>();
            FsInfoSpeq730List = new HashSet<FsInfoSpeq730List>();
            FsInfoTabper730List = new HashSet<FsInfoTabper730List>();
            FsInfoTangaas730List = new HashSet<FsInfoTangaas730List>();
            FsInfoWealob730List = new HashSet<FsInfoWealob730List>();
            FsNfaTNfaList = new HashSet<FsNfaTNfaList>();
        }

        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string HrNameseparatedivision { get; set; }
        public string HrCodeseparatedivision { get; set; }
        public string HrNamefounder { get; set; }
        public string HrCodefounder { get; set; }
        public string HrNamebodyactingfounder { get; set; }
        public string HrCodebodyactingfounder { get; set; }
        public string HrOrd { get; set; }
        public string HrNamtip { get; set; }
        public string HrSubotch { get; set; }
        public string HrOkpo1 { get; set; }
        public string HrInn1 { get; set; }
        public bool? HrFoundercheck { get; set; }
        public string InfoC1R01 { get; set; }
        public decimal? InfoC4R010 { get; set; }
        public decimal? InfoC5R010 { get; set; }
        public decimal? InfoC6R010 { get; set; }
        public decimal? InfoC7R010 { get; set; }
        public decimal? InfoC8R010 { get; set; }
        public decimal? InfoC9R010 { get; set; }
        public decimal? InfoC4R011 { get; set; }
        public decimal? InfoC5R011 { get; set; }
        public decimal? InfoC6R011 { get; set; }
        public decimal? InfoC7R011 { get; set; }
        public decimal? InfoC8R011 { get; set; }
        public decimal? InfoC9R011 { get; set; }
        public decimal? InfoC4R012 { get; set; }
        public decimal? InfoC5R012 { get; set; }
        public decimal? InfoC6R012 { get; set; }
        public decimal? InfoC7R012 { get; set; }
        public decimal? InfoC8R012 { get; set; }
        public decimal? InfoC9R012 { get; set; }
        public decimal? InfoC4R015 { get; set; }
        public decimal? InfoC5R015 { get; set; }
        public decimal? InfoC6R015 { get; set; }
        public decimal? InfoC7R015 { get; set; }
        public decimal? InfoC8R015 { get; set; }
        public decimal? InfoC9R015 { get; set; }
        public decimal? InfoC4R016 { get; set; }
        public decimal? InfoC5R016 { get; set; }
        public decimal? InfoC6R016 { get; set; }
        public decimal? InfoC7R016 { get; set; }
        public decimal? InfoC8R016 { get; set; }
        public decimal? InfoC9R016 { get; set; }
        public string InfoC1R02 { get; set; }
        public decimal? InfoC4R020 { get; set; }
        public decimal? InfoC5R020 { get; set; }
        public decimal? InfoC6R020 { get; set; }
        public decimal? InfoC7R020 { get; set; }
        public decimal? InfoC8R020 { get; set; }
        public decimal? InfoC9R020 { get; set; }
        public DateTime? InfoC1R020Num { get; set; }
        public string InfoC1R03 { get; set; }
        public decimal? InfoC4R030 { get; set; }
        public decimal? InfoC5R030 { get; set; }
        public decimal? InfoC6R030 { get; set; }
        public decimal? InfoC7R030 { get; set; }
        public decimal? InfoC8R030 { get; set; }
        public decimal? InfoC9R030 { get; set; }
        public DateTime? InfoC1R030Num { get; set; }
        public string InfoC1R04 { get; set; }
        public decimal? InfoC4R040 { get; set; }
        public decimal? InfoC5R040 { get; set; }
        public decimal? InfoC6R040 { get; set; }
        public decimal? InfoC7R040 { get; set; }
        public decimal? InfoC8R040 { get; set; }
        public decimal? InfoC9R040 { get; set; }
        public DateTime? InfoC1R040Num { get; set; }
        public string InfoC1R05 { get; set; }
        public decimal? InfoC4R050 { get; set; }
        public decimal? InfoC5R050 { get; set; }
        public decimal? InfoC6R050 { get; set; }
        public decimal? InfoC7R050 { get; set; }
        public decimal? InfoC8R050 { get; set; }
        public decimal? InfoC9R050 { get; set; }
        public decimal? InfoC4R051 { get; set; }
        public decimal? InfoC5R051 { get; set; }
        public decimal? InfoC6R051 { get; set; }
        public decimal? InfoC7R051 { get; set; }
        public decimal? InfoC8R051 { get; set; }
        public decimal? InfoC9R051 { get; set; }
        public decimal? InfoC4R052 { get; set; }
        public decimal? InfoC5R052 { get; set; }
        public decimal? InfoC6R052 { get; set; }
        public decimal? InfoC7R052 { get; set; }
        public decimal? InfoC8R052 { get; set; }
        public decimal? InfoC9R052 { get; set; }
        public decimal? InfoC4R054 { get; set; }
        public decimal? InfoC5R054 { get; set; }
        public decimal? InfoC6R054 { get; set; }
        public decimal? InfoC7R054 { get; set; }
        public decimal? InfoC8R054 { get; set; }
        public decimal? InfoC9R054 { get; set; }
        public decimal? InfoC4R055 { get; set; }
        public decimal? InfoC5R055 { get; set; }
        public decimal? InfoC6R055 { get; set; }
        public decimal? InfoC7R055 { get; set; }
        public decimal? InfoC8R055 { get; set; }
        public decimal? InfoC9R055 { get; set; }
        public string InfoC1R06 { get; set; }
        public decimal? InfoC4R060 { get; set; }
        public decimal? InfoC5R060 { get; set; }
        public decimal? InfoC6R060 { get; set; }
        public decimal? InfoC7R060 { get; set; }
        public decimal? InfoC8R060 { get; set; }
        public decimal? InfoC9R060 { get; set; }
        public string InfoC1R07 { get; set; }
        public decimal? InfoC4R070 { get; set; }
        public decimal? InfoC5R070 { get; set; }
        public decimal? InfoC6R070 { get; set; }
        public decimal? InfoC7R070 { get; set; }
        public decimal? InfoC8R070 { get; set; }
        public decimal? InfoC9R070 { get; set; }
        public decimal? InfoC4R071 { get; set; }
        public decimal? InfoC5R071 { get; set; }
        public decimal? InfoC6R071 { get; set; }
        public decimal? InfoC7R071 { get; set; }
        public decimal? InfoC8R071 { get; set; }
        public decimal? InfoC9R071 { get; set; }
        public decimal? InfoC4R072 { get; set; }
        public decimal? InfoC5R072 { get; set; }
        public decimal? InfoC6R072 { get; set; }
        public decimal? InfoC7R072 { get; set; }
        public decimal? InfoC8R072 { get; set; }
        public decimal? InfoC9R072 { get; set; }
        public string InfoC1R08 { get; set; }
        public decimal? InfoC4R080 { get; set; }
        public decimal? InfoC5R080 { get; set; }
        public decimal? InfoC6R080 { get; set; }
        public decimal? InfoC7R080 { get; set; }
        public decimal? InfoC8R080 { get; set; }
        public decimal? InfoC9R080 { get; set; }
        public string InfoC1R09 { get; set; }
        public decimal? InfoC4R090 { get; set; }
        public decimal? InfoC5R090 { get; set; }
        public decimal? InfoC6R090 { get; set; }
        public decimal? InfoC7R090 { get; set; }
        public decimal? InfoC8R090 { get; set; }
        public decimal? InfoC9R090 { get; set; }
        public string InfoC1R10 { get; set; }
        public decimal? InfoC4R100 { get; set; }
        public decimal? InfoC5R100 { get; set; }
        public decimal? InfoC6R100 { get; set; }
        public decimal? InfoC7R100 { get; set; }
        public decimal? InfoC8R100 { get; set; }
        public decimal? InfoC9R100 { get; set; }
        public decimal? InfoC4R101 { get; set; }
        public decimal? InfoC5R101 { get; set; }
        public decimal? InfoC6R101 { get; set; }
        public decimal? InfoC7R101 { get; set; }
        public decimal? InfoC8R101 { get; set; }
        public decimal? InfoC9R101 { get; set; }
        public decimal? InfoC4R102 { get; set; }
        public decimal? InfoC5R102 { get; set; }
        public decimal? InfoC6R102 { get; set; }
        public decimal? InfoC7R102 { get; set; }
        public decimal? InfoC8R102 { get; set; }
        public decimal? InfoC9R102 { get; set; }
        public decimal? InfoC4R103 { get; set; }
        public decimal? InfoC5R103 { get; set; }
        public decimal? InfoC6R103 { get; set; }
        public decimal? InfoC7R103 { get; set; }
        public decimal? InfoC8R103 { get; set; }
        public decimal? InfoC9R103 { get; set; }
        public decimal? InfoC4R104 { get; set; }
        public decimal? InfoC5R104 { get; set; }
        public decimal? InfoC6R104 { get; set; }
        public decimal? InfoC7R104 { get; set; }
        public decimal? InfoC8R104 { get; set; }
        public decimal? InfoC9R104 { get; set; }
        public decimal? InfoC4R105 { get; set; }
        public decimal? InfoC5R105 { get; set; }
        public decimal? InfoC6R105 { get; set; }
        public decimal? InfoC7R105 { get; set; }
        public decimal? InfoC8R105 { get; set; }
        public decimal? InfoC9R105 { get; set; }
        public string InfoC1R12 { get; set; }
        public decimal? InfoC4R120 { get; set; }
        public decimal? InfoC5R120 { get; set; }
        public decimal? InfoC6R120 { get; set; }
        public decimal? InfoC7R120 { get; set; }
        public decimal? InfoC8R120 { get; set; }
        public decimal? InfoC9R120 { get; set; }
        public DateTime? InfoC1R120Num { get; set; }
        public string InfoC1R13 { get; set; }
        public decimal? InfoC4R130 { get; set; }
        public decimal? InfoC5R130 { get; set; }
        public decimal? InfoC6R130 { get; set; }
        public decimal? InfoC7R130 { get; set; }
        public decimal? InfoC8R130 { get; set; }
        public decimal? InfoC9R130 { get; set; }
        public string InfoC1R15 { get; set; }
        public decimal? InfoC4R150 { get; set; }
        public decimal? InfoC5R150 { get; set; }
        public decimal? InfoC6R150 { get; set; }
        public decimal? InfoC7R150 { get; set; }
        public decimal? InfoC8R150 { get; set; }
        public decimal? InfoC9R150 { get; set; }
        public string InfoC1R16 { get; set; }
        public decimal? InfoC4R160 { get; set; }
        public decimal? InfoC5R160 { get; set; }
        public decimal? InfoC6R160 { get; set; }
        public decimal? InfoC7R160 { get; set; }
        public decimal? InfoC8R160 { get; set; }
        public decimal? InfoC9R160 { get; set; }
        public string InfoC1R17 { get; set; }
        public decimal? InfoC4R170 { get; set; }
        public decimal? InfoC5R170 { get; set; }
        public decimal? InfoC6R170 { get; set; }
        public decimal? InfoC7R170 { get; set; }
        public decimal? InfoC8R170 { get; set; }
        public decimal? InfoC9R170 { get; set; }
        public decimal? InfoC4R171 { get; set; }
        public decimal? InfoC5R171 { get; set; }
        public decimal? InfoC6R171 { get; set; }
        public decimal? InfoC7R171 { get; set; }
        public decimal? InfoC8R171 { get; set; }
        public decimal? InfoC9R171 { get; set; }
        public decimal? InfoC4R172 { get; set; }
        public decimal? InfoC5R172 { get; set; }
        public decimal? InfoC6R172 { get; set; }
        public decimal? InfoC7R172 { get; set; }
        public decimal? InfoC8R172 { get; set; }
        public decimal? InfoC9R172 { get; set; }
        public decimal? InfoC4R173 { get; set; }
        public decimal? InfoC5R173 { get; set; }
        public decimal? InfoC6R173 { get; set; }
        public decimal? InfoC7R173 { get; set; }
        public decimal? InfoC8R173 { get; set; }
        public decimal? InfoC9R173 { get; set; }
        public string InfoC1R18 { get; set; }
        public decimal? InfoC4R180 { get; set; }
        public decimal? InfoC5R180 { get; set; }
        public decimal? InfoC6R180 { get; set; }
        public decimal? InfoC7R180 { get; set; }
        public decimal? InfoC8R180 { get; set; }
        public decimal? InfoC9R180 { get; set; }
        public decimal? InfoC4R181 { get; set; }
        public decimal? InfoC5R181 { get; set; }
        public decimal? InfoC6R181 { get; set; }
        public decimal? InfoC7R181 { get; set; }
        public decimal? InfoC8R181 { get; set; }
        public decimal? InfoC9R181 { get; set; }
        public decimal? InfoC4R182 { get; set; }
        public decimal? InfoC5R182 { get; set; }
        public decimal? InfoC6R182 { get; set; }
        public decimal? InfoC7R182 { get; set; }
        public decimal? InfoC8R182 { get; set; }
        public decimal? InfoC9R182 { get; set; }
        public decimal? InfoC4R183 { get; set; }
        public decimal? InfoC5R183 { get; set; }
        public decimal? InfoC6R183 { get; set; }
        public decimal? InfoC7R183 { get; set; }
        public decimal? InfoC8R183 { get; set; }
        public decimal? InfoC9R183 { get; set; }
        public string InfoC1R20 { get; set; }
        public decimal? InfoC4R200 { get; set; }
        public decimal? InfoC5R200 { get; set; }
        public decimal? InfoC6R200 { get; set; }
        public decimal? InfoC7R200 { get; set; }
        public decimal? InfoC8R200 { get; set; }
        public decimal? InfoC9R200 { get; set; }
        public DateTime? InfoC1R200Num { get; set; }
        public string InfoC1R21 { get; set; }
        public decimal? InfoC4R210 { get; set; }
        public decimal? InfoC5R210 { get; set; }
        public decimal? InfoC6R210 { get; set; }
        public decimal? InfoC7R210 { get; set; }
        public decimal? InfoC8R210 { get; set; }
        public decimal? InfoC9R210 { get; set; }
        public decimal? InfoC4R211 { get; set; }
        public decimal? InfoC5R211 { get; set; }
        public decimal? InfoC6R211 { get; set; }
        public decimal? InfoC7R211 { get; set; }
        public decimal? InfoC8R211 { get; set; }
        public decimal? InfoC9R211 { get; set; }
        public decimal? InfoC4R212 { get; set; }
        public decimal? InfoC5R212 { get; set; }
        public decimal? InfoC6R212 { get; set; }
        public decimal? InfoC7R212 { get; set; }
        public decimal? InfoC8R212 { get; set; }
        public decimal? InfoC9R212 { get; set; }
        public string InfoC1R22 { get; set; }
        public decimal? InfoC4R220 { get; set; }
        public decimal? InfoC5R220 { get; set; }
        public decimal? InfoC6R220 { get; set; }
        public decimal? InfoC7R220 { get; set; }
        public decimal? InfoC8R220 { get; set; }
        public decimal? InfoC9R220 { get; set; }
        public decimal? InfoC4R221 { get; set; }
        public decimal? InfoC5R221 { get; set; }
        public decimal? InfoC6R221 { get; set; }
        public decimal? InfoC7R221 { get; set; }
        public decimal? InfoC8R221 { get; set; }
        public decimal? InfoC9R221 { get; set; }
        public decimal? InfoC4R222 { get; set; }
        public decimal? InfoC5R222 { get; set; }
        public decimal? InfoC6R222 { get; set; }
        public decimal? InfoC7R222 { get; set; }
        public decimal? InfoC8R222 { get; set; }
        public decimal? InfoC9R222 { get; set; }
        public decimal? InfoC4R224 { get; set; }
        public decimal? InfoC5R224 { get; set; }
        public decimal? InfoC6R224 { get; set; }
        public decimal? InfoC7R224 { get; set; }
        public decimal? InfoC8R224 { get; set; }
        public decimal? InfoC9R224 { get; set; }
        public decimal? InfoC4R225 { get; set; }
        public decimal? InfoC5R225 { get; set; }
        public decimal? InfoC6R225 { get; set; }
        public decimal? InfoC7R225 { get; set; }
        public decimal? InfoC8R225 { get; set; }
        public decimal? InfoC9R225 { get; set; }
        public string InfoC1R23 { get; set; }
        public decimal? InfoC4R230 { get; set; }
        public decimal? InfoC5R230 { get; set; }
        public decimal? InfoC6R230 { get; set; }
        public decimal? InfoC7R230 { get; set; }
        public decimal? InfoC8R230 { get; set; }
        public decimal? InfoC9R230 { get; set; }
        public DateTime? InfoC1R230Num { get; set; }
        public string InfoC1R24 { get; set; }
        public decimal? InfoC4R240 { get; set; }
        public decimal? InfoC5R240 { get; set; }
        public decimal? InfoC6R240 { get; set; }
        public decimal? InfoC7R240 { get; set; }
        public decimal? InfoC8R240 { get; set; }
        public decimal? InfoC9R240 { get; set; }
        public decimal? InfoC4R241 { get; set; }
        public decimal? InfoC5R241 { get; set; }
        public decimal? InfoC6R241 { get; set; }
        public decimal? InfoC7R241 { get; set; }
        public decimal? InfoC8R241 { get; set; }
        public decimal? InfoC9R241 { get; set; }
        public decimal? InfoC4R242 { get; set; }
        public decimal? InfoC5R242 { get; set; }
        public decimal? InfoC6R242 { get; set; }
        public decimal? InfoC7R242 { get; set; }
        public decimal? InfoC8R242 { get; set; }
        public decimal? InfoC9R242 { get; set; }
        public decimal? InfoC4R243 { get; set; }
        public decimal? InfoC5R243 { get; set; }
        public decimal? InfoC6R243 { get; set; }
        public decimal? InfoC7R243 { get; set; }
        public decimal? InfoC8R243 { get; set; }
        public decimal? InfoC9R243 { get; set; }
        public decimal? InfoC4R244 { get; set; }
        public decimal? InfoC5R244 { get; set; }
        public decimal? InfoC6R244 { get; set; }
        public decimal? InfoC7R244 { get; set; }
        public decimal? InfoC8R244 { get; set; }
        public decimal? InfoC9R244 { get; set; }
        public decimal? InfoC4R245 { get; set; }
        public decimal? InfoC5R245 { get; set; }
        public decimal? InfoC6R245 { get; set; }
        public decimal? InfoC7R245 { get; set; }
        public decimal? InfoC8R245 { get; set; }
        public decimal? InfoC9R245 { get; set; }
        public decimal? InfoC4R246 { get; set; }
        public decimal? InfoC5R246 { get; set; }
        public decimal? InfoC6R246 { get; set; }
        public decimal? InfoC7R246 { get; set; }
        public decimal? InfoC8R246 { get; set; }
        public decimal? InfoC9R246 { get; set; }
        public decimal? InfoC4R247 { get; set; }
        public decimal? InfoC5R247 { get; set; }
        public decimal? InfoC6R247 { get; set; }
        public decimal? InfoC7R247 { get; set; }
        public decimal? InfoC8R247 { get; set; }
        public decimal? InfoC9R247 { get; set; }
        public decimal? InfoC4R248 { get; set; }
        public decimal? InfoC5R248 { get; set; }
        public decimal? InfoC6R248 { get; set; }
        public decimal? InfoC7R248 { get; set; }
        public decimal? InfoC8R248 { get; set; }
        public decimal? InfoC9R248 { get; set; }
        public decimal? InfoC4R249 { get; set; }
        public decimal? InfoC5R249 { get; set; }
        public decimal? InfoC6R249 { get; set; }
        public decimal? InfoC7R249 { get; set; }
        public decimal? InfoC8R249 { get; set; }
        public decimal? InfoC9R249 { get; set; }
        public string InfoC1R25 { get; set; }
        public decimal? InfoC4R250 { get; set; }
        public decimal? InfoC5R250 { get; set; }
        public decimal? InfoC6R250 { get; set; }
        public decimal? InfoC7R250 { get; set; }
        public decimal? InfoC8R250 { get; set; }
        public decimal? InfoC9R250 { get; set; }
        public decimal? InfoC4R251 { get; set; }
        public decimal? InfoC5R251 { get; set; }
        public decimal? InfoC6R251 { get; set; }
        public decimal? InfoC7R251 { get; set; }
        public decimal? InfoC8R251 { get; set; }
        public decimal? InfoC9R251 { get; set; }
        public decimal? InfoC4R252 { get; set; }
        public decimal? InfoC5R252 { get; set; }
        public decimal? InfoC6R252 { get; set; }
        public decimal? InfoC7R252 { get; set; }
        public decimal? InfoC8R252 { get; set; }
        public decimal? InfoC9R252 { get; set; }
        public decimal? InfoC4R253 { get; set; }
        public decimal? InfoC5R253 { get; set; }
        public decimal? InfoC6R253 { get; set; }
        public decimal? InfoC7R253 { get; set; }
        public decimal? InfoC8R253 { get; set; }
        public decimal? InfoC9R253 { get; set; }
        public decimal? InfoC4R254 { get; set; }
        public decimal? InfoC5R254 { get; set; }
        public decimal? InfoC6R254 { get; set; }
        public decimal? InfoC7R254 { get; set; }
        public decimal? InfoC8R254 { get; set; }
        public decimal? InfoC9R254 { get; set; }
        public decimal? InfoC4R255 { get; set; }
        public decimal? InfoC5R255 { get; set; }
        public decimal? InfoC6R255 { get; set; }
        public decimal? InfoC7R255 { get; set; }
        public decimal? InfoC8R255 { get; set; }
        public decimal? InfoC9R255 { get; set; }
        public decimal? InfoC4R256 { get; set; }
        public decimal? InfoC5R256 { get; set; }
        public decimal? InfoC6R256 { get; set; }
        public decimal? InfoC7R256 { get; set; }
        public decimal? InfoC8R256 { get; set; }
        public decimal? InfoC9R256 { get; set; }
        public decimal? InfoC4R257 { get; set; }
        public decimal? InfoC5R257 { get; set; }
        public decimal? InfoC6R257 { get; set; }
        public decimal? InfoC7R257 { get; set; }
        public decimal? InfoC8R257 { get; set; }
        public decimal? InfoC9R257 { get; set; }
        public decimal? InfoC4R258 { get; set; }
        public decimal? InfoC5R258 { get; set; }
        public decimal? InfoC6R258 { get; set; }
        public decimal? InfoC7R258 { get; set; }
        public decimal? InfoC8R258 { get; set; }
        public decimal? InfoC9R258 { get; set; }
        public string InfoC1R26 { get; set; }
        public decimal? InfoC4R260 { get; set; }
        public decimal? InfoC5R260 { get; set; }
        public decimal? InfoC6R260 { get; set; }
        public decimal? InfoC7R260 { get; set; }
        public decimal? InfoC8R260 { get; set; }
        public decimal? InfoC9R260 { get; set; }
        public decimal? InfoC4R261 { get; set; }
        public decimal? InfoC5R261 { get; set; }
        public decimal? InfoC6R261 { get; set; }
        public decimal? InfoC7R261 { get; set; }
        public decimal? InfoC8R261 { get; set; }
        public decimal? InfoC9R261 { get; set; }
        public decimal? InfoC4R262 { get; set; }
        public decimal? InfoC5R262 { get; set; }
        public decimal? InfoC6R262 { get; set; }
        public decimal? InfoC7R262 { get; set; }
        public decimal? InfoC8R262 { get; set; }
        public decimal? InfoC9R262 { get; set; }
        public decimal? InfoC4R263 { get; set; }
        public decimal? InfoC5R263 { get; set; }
        public decimal? InfoC6R263 { get; set; }
        public decimal? InfoC7R263 { get; set; }
        public decimal? InfoC8R263 { get; set; }
        public decimal? InfoC9R263 { get; set; }
        public decimal? InfoC4R264 { get; set; }
        public decimal? InfoC5R264 { get; set; }
        public decimal? InfoC6R264 { get; set; }
        public decimal? InfoC7R264 { get; set; }
        public decimal? InfoC8R264 { get; set; }
        public decimal? InfoC9R264 { get; set; }
        public decimal? InfoC4R265 { get; set; }
        public decimal? InfoC5R265 { get; set; }
        public decimal? InfoC6R265 { get; set; }
        public decimal? InfoC7R265 { get; set; }
        public decimal? InfoC8R265 { get; set; }
        public decimal? InfoC9R265 { get; set; }
        public decimal? InfoC4R266 { get; set; }
        public decimal? InfoC5R266 { get; set; }
        public decimal? InfoC6R266 { get; set; }
        public decimal? InfoC7R266 { get; set; }
        public decimal? InfoC8R266 { get; set; }
        public decimal? InfoC9R266 { get; set; }
        public decimal? InfoC4R267 { get; set; }
        public decimal? InfoC5R267 { get; set; }
        public decimal? InfoC6R267 { get; set; }
        public decimal? InfoC7R267 { get; set; }
        public decimal? InfoC8R267 { get; set; }
        public decimal? InfoC9R267 { get; set; }
        public decimal? InfoC4R268 { get; set; }
        public decimal? InfoC5R268 { get; set; }
        public decimal? InfoC6R268 { get; set; }
        public decimal? InfoC7R268 { get; set; }
        public decimal? InfoC8R268 { get; set; }
        public decimal? InfoC9R268 { get; set; }
        public decimal? InfoC4R270 { get; set; }
        public decimal? InfoC5R270 { get; set; }
        public decimal? InfoC6R270 { get; set; }
        public decimal? InfoC7R270 { get; set; }
        public decimal? InfoC8R270 { get; set; }
        public decimal? InfoC9R270 { get; set; }
        public decimal? InfoC4R280 { get; set; }
        public decimal? InfoC5R280 { get; set; }
        public decimal? InfoC6R280 { get; set; }
        public decimal? InfoC7R280 { get; set; }
        public decimal? InfoC8R280 { get; set; }
        public decimal? InfoC9R280 { get; set; }
        public decimal? InfoC4R290 { get; set; }
        public decimal? InfoC5R290 { get; set; }
        public decimal? InfoC6R290 { get; set; }
        public decimal? InfoC7R290 { get; set; }
        public decimal? InfoC8R290 { get; set; }
        public decimal? InfoC9R290 { get; set; }
        public string InfoC1R40 { get; set; }
        public decimal? InfoC4R300 { get; set; }
        public decimal? InfoC5R300 { get; set; }
        public decimal? InfoC6R300 { get; set; }
        public decimal? InfoC7R300 { get; set; }
        public decimal? InfoC8R300 { get; set; }
        public decimal? InfoC9R300 { get; set; }
        public decimal? InfoC51R010 { get; set; }
        public decimal? InfoC51R011 { get; set; }
        public decimal? InfoC51R012 { get; set; }
        public decimal? InfoC51R015 { get; set; }
        public decimal? InfoC51R016 { get; set; }
        public decimal? InfoC51R020 { get; set; }
        public decimal? InfoC51R030 { get; set; }
        public decimal? InfoC51R040 { get; set; }
        public decimal? InfoC51R050 { get; set; }
        public decimal? InfoC51R051 { get; set; }
        public decimal? InfoC51R052 { get; set; }
        public decimal? InfoC51R054 { get; set; }
        public decimal? InfoC51R055 { get; set; }
        public decimal? InfoC51R060 { get; set; }
        public decimal? InfoC51R070 { get; set; }
        public decimal? InfoC51R071 { get; set; }
        public decimal? InfoC51R072 { get; set; }
        public decimal? InfoC51R080 { get; set; }
        public decimal? InfoC51R090 { get; set; }
        public decimal? InfoC51R100 { get; set; }
        public decimal? InfoC51R101 { get; set; }
        public decimal? InfoC51R102 { get; set; }
        public decimal? InfoC51R103 { get; set; }
        public decimal? InfoC51R104 { get; set; }
        public decimal? InfoC51R105 { get; set; }
        public decimal? InfoC51R120 { get; set; }
        public decimal? InfoC51R130 { get; set; }
        public decimal? InfoC51R150 { get; set; }
        public decimal? InfoC51R160 { get; set; }
        public decimal? InfoC51R170 { get; set; }
        public decimal? InfoC51R171 { get; set; }
        public decimal? InfoC51R172 { get; set; }
        public decimal? InfoC51R173 { get; set; }
        public decimal? InfoC51R180 { get; set; }
        public decimal? InfoC51R181 { get; set; }
        public decimal? InfoC51R182 { get; set; }
        public decimal? InfoC51R183 { get; set; }
        public decimal? InfoC51R200 { get; set; }
        public decimal? InfoC51R210 { get; set; }
        public decimal? InfoC51R211 { get; set; }
        public decimal? InfoC51R212 { get; set; }
        public decimal? InfoC51R220 { get; set; }
        public decimal? InfoC51R221 { get; set; }
        public decimal? InfoC51R222 { get; set; }
        public decimal? InfoC51R224 { get; set; }
        public decimal? InfoC51R225 { get; set; }
        public decimal? InfoC51R230 { get; set; }
        public decimal? InfoC51R240 { get; set; }
        public decimal? InfoC51R241 { get; set; }
        public decimal? InfoC51R242 { get; set; }
        public decimal? InfoC51R243 { get; set; }
        public decimal? InfoC51R244 { get; set; }
        public decimal? InfoC51R245 { get; set; }
        public decimal? InfoC51R246 { get; set; }
        public decimal? InfoC51R247 { get; set; }
        public decimal? InfoC51R248 { get; set; }
        public decimal? InfoC51R249 { get; set; }
        public decimal? InfoC51R250 { get; set; }
        public decimal? InfoC51R251 { get; set; }
        public decimal? InfoC51R252 { get; set; }
        public decimal? InfoC51R253 { get; set; }
        public decimal? InfoC51R254 { get; set; }
        public decimal? InfoC51R255 { get; set; }
        public decimal? InfoC51R256 { get; set; }
        public decimal? InfoC51R257 { get; set; }
        public decimal? InfoC51R258 { get; set; }
        public decimal? InfoC51R260 { get; set; }
        public decimal? InfoC51R261 { get; set; }
        public decimal? InfoC51R262 { get; set; }
        public decimal? InfoC51R263 { get; set; }
        public decimal? InfoC51R264 { get; set; }
        public decimal? InfoC51R265 { get; set; }
        public decimal? InfoC51R266 { get; set; }
        public decimal? InfoC51R267 { get; set; }
        public decimal? InfoC51R268 { get; set; }
        public decimal? InfoC51R270 { get; set; }
        public decimal? InfoC51R280 { get; set; }
        public decimal? InfoC51R290 { get; set; }
        public decimal? InfoC51R300 { get; set; }
        public decimal? InfoC81R010 { get; set; }
        public decimal? InfoC81R011 { get; set; }
        public decimal? InfoC81R012 { get; set; }
        public decimal? InfoC81R015 { get; set; }
        public decimal? InfoC81R016 { get; set; }
        public decimal? InfoC81R020 { get; set; }
        public decimal? InfoC81R030 { get; set; }
        public decimal? InfoC81R040 { get; set; }
        public decimal? InfoC81R050 { get; set; }
        public decimal? InfoC81R051 { get; set; }
        public decimal? InfoC81R052 { get; set; }
        public decimal? InfoC81R054 { get; set; }
        public decimal? InfoC81R055 { get; set; }
        public decimal? InfoC81R060 { get; set; }
        public decimal? InfoC81R070 { get; set; }
        public decimal? InfoC81R071 { get; set; }
        public decimal? InfoC81R072 { get; set; }
        public decimal? InfoC81R080 { get; set; }
        public decimal? InfoC81R090 { get; set; }
        public decimal? InfoC81R100 { get; set; }
        public decimal? InfoC81R101 { get; set; }
        public decimal? InfoC81R102 { get; set; }
        public decimal? InfoC81R103 { get; set; }
        public decimal? InfoC81R104 { get; set; }
        public decimal? InfoC81R105 { get; set; }
        public decimal? InfoC81R120 { get; set; }
        public decimal? InfoC81R130 { get; set; }
        public decimal? InfoC81R150 { get; set; }
        public decimal? InfoC81R160 { get; set; }
        public decimal? InfoC81R170 { get; set; }
        public decimal? InfoC81R171 { get; set; }
        public decimal? InfoC81R172 { get; set; }
        public decimal? InfoC81R173 { get; set; }
        public decimal? InfoC81R180 { get; set; }
        public decimal? InfoC81R181 { get; set; }
        public decimal? InfoC81R182 { get; set; }
        public decimal? InfoC81R183 { get; set; }
        public decimal? InfoC81R200 { get; set; }
        public decimal? InfoC81R210 { get; set; }
        public decimal? InfoC81R211 { get; set; }
        public decimal? InfoC81R212 { get; set; }
        public decimal? InfoC81R220 { get; set; }
        public decimal? InfoC81R221 { get; set; }
        public decimal? InfoC81R222 { get; set; }
        public decimal? InfoC81R224 { get; set; }
        public decimal? InfoC81R225 { get; set; }
        public decimal? InfoC81R230 { get; set; }
        public decimal? InfoC81R240 { get; set; }
        public decimal? InfoC81R241 { get; set; }
        public decimal? InfoC81R242 { get; set; }
        public decimal? InfoC81R243 { get; set; }
        public decimal? InfoC81R244 { get; set; }
        public decimal? InfoC81R245 { get; set; }
        public decimal? InfoC81R246 { get; set; }
        public decimal? InfoC81R247 { get; set; }
        public decimal? InfoC81R248 { get; set; }
        public decimal? InfoC81R249 { get; set; }
        public decimal? InfoC81R250 { get; set; }
        public decimal? InfoC81R251 { get; set; }
        public decimal? InfoC81R252 { get; set; }
        public decimal? InfoC81R253 { get; set; }
        public decimal? InfoC81R254 { get; set; }
        public decimal? InfoC81R255 { get; set; }
        public decimal? InfoC81R256 { get; set; }
        public decimal? InfoC81R257 { get; set; }
        public decimal? InfoC81R258 { get; set; }
        public decimal? InfoC81R260 { get; set; }
        public decimal? InfoC81R261 { get; set; }
        public decimal? InfoC81R262 { get; set; }
        public decimal? InfoC81R263 { get; set; }
        public decimal? InfoC81R264 { get; set; }
        public decimal? InfoC81R265 { get; set; }
        public decimal? InfoC81R266 { get; set; }
        public decimal? InfoC81R267 { get; set; }
        public decimal? InfoC81R268 { get; set; }
        public decimal? InfoC81R270 { get; set; }
        public decimal? InfoC81R280 { get; set; }
        public decimal? InfoC81R290 { get; set; }
        public decimal? InfoC81R300 { get; set; }
        public decimal? InfoC4R0101 { get; set; }
        public decimal? InfoC5R0101 { get; set; }
        public decimal? InfoC51R0101 { get; set; }
        public decimal? InfoC6R0101 { get; set; }
        public decimal? InfoC7R0101 { get; set; }
        public decimal? InfoC8R0101 { get; set; }
        public decimal? InfoC81R0101 { get; set; }
        public decimal? InfoC9R0101 { get; set; }
        public decimal? InfoC4R0501 { get; set; }
        public decimal? InfoC5R0501 { get; set; }
        public decimal? InfoC51R0501 { get; set; }
        public decimal? InfoC6R0501 { get; set; }
        public decimal? InfoC7R0501 { get; set; }
        public decimal? InfoC8R0501 { get; set; }
        public decimal? InfoC81R0501 { get; set; }
        public decimal? InfoC9R0501 { get; set; }
        public decimal? InfoC4R2201 { get; set; }
        public decimal? InfoC5R2201 { get; set; }
        public decimal? InfoC51R2201 { get; set; }
        public decimal? InfoC6R2201 { get; set; }
        public decimal? InfoC7R2201 { get; set; }
        public decimal? InfoC8R2201 { get; set; }
        public decimal? InfoC81R2201 { get; set; }
        public decimal? InfoC9R2201 { get; set; }
        public string PenLeader { get; set; }
        public string PenChiefAcc { get; set; }
        public string PenLeaderOfFes { get; set; }
        public string PenPostLeader { get; set; }
        public string PenPostChiefAcc { get; set; }
        public string PenPostLeaderOf { get; set; }
        public string PenExecutor { get; set; }
        public string PenPostExecutor { get; set; }
        public string PenPhone { get; set; }
        public string CaCode { get; set; }
        public string CaName { get; set; }
        public string CaOgrn { get; set; }
        public string CaInn { get; set; }
        public string CaKpp { get; set; }
        public string CaCaLeader { get; set; }
        public string CaCaExecutor { get; set; }
        public string CaCaExecutMail { get; set; }
        public string CaCaLeader1 { get; set; }
        public string CaCaExecutor1 { get; set; }
        public string CaAddress { get; set; }

        public virtual ICollection<FsClClList> FsClClList { get; set; }
        public virtual ICollection<FsFaFaList> FsFaFaList { get; set; }
        public virtual ICollection<FsFrFrList> FsFrFrList { get; set; }
        public virtual ICollection<FsInfoFixas730List> FsInfoFixas730List { get; set; }
        public virtual ICollection<FsInfoFrst730List> FsInfoFrst730List { get; set; }
        public virtual ICollection<FsInfoInsdeb730List> FsInfoInsdeb730List { get; set; }
        public virtual ICollection<FsInfoInskr730List> FsInfoInskr730List { get; set; }
        public virtual ICollection<FsInfoMatval730List> FsInfoMatval730List { get; set; }
        public virtual ICollection<FsInfoProprent730List> FsInfoProprent730List { get; set; }
        public virtual ICollection<FsInfoPropuse730List> FsInfoPropuse730List { get; set; }
        public virtual ICollection<FsInfoProtran730List> FsInfoProtran730List { get; set; }
        public virtual ICollection<FsInfoSpeq730List> FsInfoSpeq730List { get; set; }
        public virtual ICollection<FsInfoTabper730List> FsInfoTabper730List { get; set; }
        public virtual ICollection<FsInfoTangaas730List> FsInfoTangaas730List { get; set; }
        public virtual ICollection<FsInfoWealob730List> FsInfoWealob730List { get; set; }
        public virtual ICollection<FsNfaTNfaList> FsNfaTNfaList { get; set; }
    }
}
