using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcDbdLimitsbudgetobligat
    {
        public DcDbdLimitsbudgetobligat()
        {
            FsLaAgreer052List = new HashSet<FsLaAgreer052List>();
            FsLaApprove052List = new HashSet<FsLaApprove052List>();
            FsLaExecutor052List = new HashSet<FsLaExecutor052List>();
            FsLboLbo052List = new HashSet<FsLboLbo052List>();
        }

        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string InfDoctype { get; set; }
        public string InfSecrecy { get; set; }
        public string InfCircmf { get; set; }
        public string InfNamefo { get; set; }
        public string InfNote { get; set; }
        public string InfItemlist { get; set; }
        public DateTime? InfDateregfk { get; set; }
        public DateTime? InfDateofacc { get; set; }
        public string InfSource { get; set; }
        public string InfOkud { get; set; }
        public string InfPlperiodYear { get; set; }
        public string InfPlperiodYear1 { get; set; }
        public string InfPlperiodYear2 { get; set; }
        public DateTime? InfPerioddbdPfrom { get; set; }
        public DateTime? InfPerioddbdPto { get; set; }
        public string InfUnitOkei { get; set; }
        public string InfUnitName { get; set; }
        public string InfDocnumber { get; set; }
        public DateTime? InfDocdate { get; set; }
        public string InfRegnumb { get; set; }
        public string InfBudgetCode { get; set; }
        public string InfBudgetName { get; set; }
        public DateTime? InfDateapp { get; set; }
        public DateTime? InfDateoper { get; set; }
        public string InfTofkName { get; set; }
        public string InfTofkCode { get; set; }
        public DateTime? InfDttmcrt { get; set; }
        public string InfSigninfo { get; set; }
        public string InfNamesigninfo { get; set; }
        public string InfChangecode { get; set; }
        public string InfChangename { get; set; }
        public DateTime? InfControlBaLbo { get; set; }
        public string InfBudgetcontrol { get; set; }
        public DateTime? InfSignlowcontrol { get; set; }
        public string InfBasislowcontrol { get; set; }
        public decimal? LboTsyYear { get; set; }
        public decimal? LboTsyYear1 { get; set; }
        public decimal? LboTsyYear2 { get; set; }
        public decimal? LboTsyzYear { get; set; }
        public decimal? LboTsyzYear1 { get; set; }
        public decimal? LboTsyzYear2 { get; set; }
        public decimal? LboTsydYear { get; set; }
        public decimal? LboTsydYear1 { get; set; }
        public decimal? LboTsydYear2 { get; set; }
        public DateTime? SgnDatesign { get; set; }
        public string SgnSignmf { get; set; }
        public DateTime? SgnDatesignmf { get; set; }
        public string SgnSgnfkSgnexct { get; set; }
        public string SgnSgnfkPstexct { get; set; }
        public string SgnSgnfkPhn { get; set; }
        public string SiLampgroupftas { get; set; }
        public string SiLampgroupfk { get; set; }
        public string SiLampgrouppuio { get; set; }
        public string SiLampgrouptn { get; set; }
        public string SiLampgroupregtn { get; set; }
        public string SiTfGuid { get; set; }
        public string SiTfOrgsysname { get; set; }
        public string SiTfTransferstate { get; set; }
        public string SiTfTransfererror { get; set; }
        public string SiTfClientstate { get; set; }
        public string SiTfBodid { get; set; }
        public string SiTfAsfkstate { get; set; }
        public DateTime? DtfkControldatetofk { get; set; }
        public string DtfkControlflagtofk { get; set; }
        public string SiPuioNmaccrec { get; set; }
        public string SiPuioNmaccrec1 { get; set; }
        public string SiSrtSerialnumber { get; set; }
        public DateTime? SiSrtStartdate { get; set; }
        public DateTime? SiSrtEnddate { get; set; }
        public DateTime? SiSrtSigndate { get; set; }
        public string SiSrtSignerfio { get; set; }
        public string SiProtocolguid { get; set; }
        public DateTime? SiProtocoldate { get; set; }
        public string SiProtocolnum { get; set; }
        public string SiAllowExceedingLbo { get; set; }
        public bool? LaSkipappr { get; set; }
        public decimal? LaAmountrowexecutor { get; set; }
        public decimal? LaAmountrowagreer { get; set; }
        public decimal? LaAmountrowapprover { get; set; }
        public string P1Surrogat { get; set; }
        public string P1ReportNum { get; set; }
        public string P1Codereportform { get; set; }
        public string P1HrErNameOfEntity { get; set; }
        public string P1HrErCodeOfEntity { get; set; }
        public string P1HrErOkpo { get; set; }
        public string P1HrErOktmo { get; set; }
        public string P1HrErGlavaBk { get; set; }
        public string P1HrErSubotch { get; set; }
        public string P1HrErInn { get; set; }
        public string P1HrErCdofentalt { get; set; }
        public string P1HrErPrcdofent { get; set; }
        public string P1HrErPrnmofent { get; set; }
        public string P1HrPeriodType { get; set; }
        public DateTime? P1HrReportDate { get; set; }
        public string P1HrInstitutionCode { get; set; }
        public string P1HrAccountcode { get; set; }
        public bool? P1HrUsersing { get; set; }
        public string P1HrAiCode { get; set; }
        public string P1HrAiName { get; set; }
        public string P1HrNamtip { get; set; }
        public string P1HrTypeactivityname { get; set; }
        public string P1HrTypeactivitycode { get; set; }
        public string P1HrBtCodeOfBudget { get; set; }
        public string P1HrBtNameOfBudget { get; set; }
        public string P1HrBtCodeOfType { get; set; }
        public string P1HrTofkcode { get; set; }
        public string P1HrUbpcode { get; set; }
        public DateTime? P1HrDataStartactive { get; set; }
        public DateTime? P1HrDataEndactive { get; set; }
        public string P1HrCdrf { get; set; }
        public string P1HrIndicators { get; set; }
        public string P1HrCodf { get; set; }
        public string P1HrOffice { get; set; }
        public string P1HrReorg { get; set; }
        public string P1HrGlavaReorg { get; set; }
        public string P1HrOktmoReorg { get; set; }
        public string P1HrCodeReorg { get; set; }
        public string P1HrReorgTex { get; set; }
        public bool? P1HrCheckreorg { get; set; }
        public string P1StatctrlsStateidc { get; set; }
        public string P1StatctrlsStatebdc { get; set; }
        public string P1StatctrlsStateflc { get; set; }
        public string P1StatctrlsStateexc { get; set; }
        public string P1StatctrlsGuidflc { get; set; }
        public string P1StatctrlsGuididc { get; set; }
        public string P1StatctrlsGuidbdc { get; set; }
        public string P1StatctrlsGuidexc { get; set; }
        public string P1StatctrlsGuidprimeexc { get; set; }
        public string P1Currentapprover { get; set; }
        public string P1Nextapprover { get; set; }
        public string P1Fullyapproved { get; set; }
        public string P1Approvalstate { get; set; }
        public string P1Typeagreement { get; set; }
        public string P1Namereportform { get; set; }
        public string P1Reporttype { get; set; }
        public string P1Filename { get; set; }
        public DateTime? P1Importdatetime { get; set; }
        public string P1ComplectCode { get; set; }
        public string P1PeriodCode { get; set; }
        public string P1ImportedWErrors { get; set; }
        public DateTime? P1TimeSubmit { get; set; }
        public string P1Reasons { get; set; }
        public string P1Reporttypemou { get; set; }
        public string P1Lastreport { get; set; }
        public string P1Guidconsolid { get; set; }
        public DateTime? P1Datestatusupdates { get; set; }
        public string P1Guidprimary { get; set; }
        public string P1Guidconsolidated { get; set; }
        public string P1Fksegmentcode { get; set; }
        public string P1Fksystem { get; set; }
        public string P1Stateasfk { get; set; }
        public string P1Asfkdocguid { get; set; }
        public string P1Printname { get; set; }
        public string P1FgSo { get; set; }
        public string P1FgPo { get; set; }
        public string P1ApLoginGb { get; set; }
        public string P1ApLoginRfes { get; set; }
        public string P1ApLoginR { get; set; }
        public string P1ApLoginOip { get; set; }
        public string P1ApFioGb { get; set; }
        public string P1ApFioRfes { get; set; }
        public string P1ApFioR { get; set; }
        public string P1ApFioOip { get; set; }
        public string P1ApDepartmentGb { get; set; }
        public string P1ApDepartmentRfes { get; set; }
        public string P1ApDepartmentR { get; set; }
        public string P1ApDepartmentOip { get; set; }
        public string P1ApPostfieldR { get; set; }
        public string P1ApPostfieldRfes { get; set; }
        public string P1ApPostfieldGb { get; set; }
        public string P1ApPostfieldOip { get; set; }
        public bool? P1ApScipsoglas { get; set; }
        public string P1ApSoglasGb { get; set; }
        public string P1ApSoglasRfes { get; set; }
        public string P1ApSoglasR { get; set; }
        public string P1ApSoglasOip { get; set; }
        public string P1ApNoteGb { get; set; }
        public string P1ApNoteRfes { get; set; }
        public string P1ApNoteR { get; set; }
        public string P1ApNoteOip { get; set; }
        public string P1ApSoglasCnb { get; set; }
        public string P1ApNoteCnb { get; set; }
        public string P1SignLeader { get; set; }
        public string P1SignChiefAcc { get; set; }
        public string P1SignLeaderOfFes { get; set; }
        public string P1SignPostLeader { get; set; }
        public string P1SignPostChiefAcc { get; set; }
        public string P1SignPostLeaderOf { get; set; }
        public string P1SignExecutor { get; set; }
        public string P1SignPostExecutor { get; set; }
        public string P1SignPhone { get; set; }
        public string P1SignFioOip { get; set; }
        public string P1SignPostfieldOip { get; set; }
        public string P1SignLdrFlg { get; set; }
        public string P1SignChfFlg { get; set; }
        public string P1SignLdrFesFlg { get; set; }
        public string P1SignOipFlg { get; set; }
        public string P1SignLdrCaFlg { get; set; }
        public bool? P1SignReorgSogl { get; set; }
        public string P1SignReorgAssign { get; set; }
        public string P1SignReorgNote { get; set; }
        public string P1Reqstate { get; set; }
        public DateTime? P1VnkFormationDate { get; set; }
        public bool? P1CheckBlockerFlk { get; set; }
        public bool? P1CheckBlockerVdk { get; set; }
        public bool? P1CheckBlockerMdk { get; set; }
        public string P1AgreedReorg { get; set; }
        public string P1StateEpbs { get; set; }
        public string P1Guidticket { get; set; }
        public string P1Guidreceipt { get; set; }
        public string P1CnbCode { get; set; }
        public string P1CnbName { get; set; }
        public string P1CnbOgrn { get; set; }
        public string P1CnbInn { get; set; }
        public string P1CnbKpp { get; set; }
        public string P1CnbCaLeader { get; set; }
        public string P1CnbCaExecutor { get; set; }
        public string P1CnbPostCaLeader { get; set; }
        public string P1CnbPostCaExecutor { get; set; }
        public string P1CnbCaExecutorMail { get; set; }
        public string P1CaExecutorMail { get; set; }
        public string P1Location { get; set; }
        public string P1AllPrint { get; set; }
        public bool? P1SubDiv { get; set; }
        public string P1Okved { get; set; }
        public string P1ImportSystem { get; set; }
        public string P1FahFormed { get; set; }
        public string P1GuidReportTech { get; set; }
        public string P1StatusFah { get; set; }
        public string P1PhaseFah { get; set; }
        public string P1TextFah { get; set; }
        public string P1RplReportNum { get; set; }
        public string P1RplErNameOfEntity { get; set; }
        public string P1RplErCodeOfEntity { get; set; }
        public string P1RplErOkpo { get; set; }
        public string P1RplErOktmo { get; set; }
        public string P1RplErGlavaBk { get; set; }
        public string P1RplErSubotch { get; set; }
        public string P1RplErInn { get; set; }
        public string P1RplErCdofentalt { get; set; }
        public string P1RplErPrcdofent { get; set; }
        public string P1RplErPrnmofent { get; set; }
        public string P1RplReasons1 { get; set; }
        public string P1RplReasons2 { get; set; }
        public string P1RplStateRpl { get; set; }
        public string P1RplGuidrpl { get; set; }
        public string P1RplNameOfBudget { get; set; }
        public bool? P1RplFlg { get; set; }
        public string P1SrcCons { get; set; }
        public string P1DocsToUpdate { get; set; }
        public string P1StatePiao { get; set; }
        public string P1ImpSecuritylevel { get; set; }
        public string P1ImpSecurlvcode { get; set; }
        public string P1ImpCommentinfo { get; set; }
        public string P1ImpVersionname { get; set; }
        public string InfTranscodeinform { get; set; }

        public virtual ICollection<FsLaAgreer052List> FsLaAgreer052List { get; set; }
        public virtual ICollection<FsLaApprove052List> FsLaApprove052List { get; set; }
        public virtual ICollection<FsLaExecutor052List> FsLaExecutor052List { get; set; }
        public virtual ICollection<FsLboLbo052List> FsLboLbo052List { get; set; }
    }
}
