using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcReport0503721
    {
        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string Surrogat { get; set; }
        public string BrC2R010 { get; set; }
        public string BrC3R010 { get; set; }
        public decimal? BrC4R010 { get; set; }
        public decimal? BrC5R010 { get; set; }
        public decimal? BrC6R010 { get; set; }
        public decimal? BrC7R010 { get; set; }
        public string BrC2R030 { get; set; }
        public string BrC3R030 { get; set; }
        public decimal? BrC4R030 { get; set; }
        public decimal? BrC5R030 { get; set; }
        public decimal? BrC6R030 { get; set; }
        public decimal? BrC7R030 { get; set; }
        public string BrC2R040 { get; set; }
        public string BrC3R040 { get; set; }
        public decimal? BrC4R040 { get; set; }
        public decimal? BrC5R040 { get; set; }
        public decimal? BrC6R040 { get; set; }
        public decimal? BrC7R040 { get; set; }
        public string BrC2R050 { get; set; }
        public string BrC3R050 { get; set; }
        public decimal? BrC4R050 { get; set; }
        public decimal? BrC5R050 { get; set; }
        public decimal? BrC6R050 { get; set; }
        public decimal? BrC7R050 { get; set; }
        public string BrC2R060 { get; set; }
        public string BrC3R060 { get; set; }
        public decimal? BrC4R060 { get; set; }
        public decimal? BrC5R060 { get; set; }
        public decimal? BrC6R060 { get; set; }
        public decimal? BrC7R060 { get; set; }
        public string BrC2R062 { get; set; }
        public string BrC3R062 { get; set; }
        public decimal? BrC4R062 { get; set; }
        public decimal? BrC5R062 { get; set; }
        public decimal? BrC6R062 { get; set; }
        public decimal? BrC7R062 { get; set; }
        public string BrC2R063 { get; set; }
        public string BrC3R063 { get; set; }
        public decimal? BrC4R063 { get; set; }
        public decimal? BrC5R063 { get; set; }
        public decimal? BrC6R063 { get; set; }
        public decimal? BrC7R063 { get; set; }
        public string BrC2R090 { get; set; }
        public string BrC3R090 { get; set; }
        public decimal? BrC4R090 { get; set; }
        public decimal? BrC5R090 { get; set; }
        public decimal? BrC6R090 { get; set; }
        public decimal? BrC7R090 { get; set; }
        public string BrC2R091 { get; set; }
        public string BrC3R091 { get; set; }
        public decimal? BrC4R091 { get; set; }
        public decimal? BrC5R091 { get; set; }
        public decimal? BrC6R091 { get; set; }
        public decimal? BrC7R091 { get; set; }
        public string BrC2R092 { get; set; }
        public string BrC3R092 { get; set; }
        public decimal? BrC4R092 { get; set; }
        public decimal? BrC5R092 { get; set; }
        public decimal? BrC6R092 { get; set; }
        public decimal? BrC7R092 { get; set; }
        public string BrC2R093 { get; set; }
        public string BrC3R093 { get; set; }
        public decimal? BrC4R093 { get; set; }
        public decimal? BrC5R093 { get; set; }
        public decimal? BrC6R093 { get; set; }
        public decimal? BrC7R093 { get; set; }
        public string BrC2R096 { get; set; }
        public string BrC3R096 { get; set; }
        public decimal? BrC4R096 { get; set; }
        public decimal? BrC5R096 { get; set; }
        public decimal? BrC6R096 { get; set; }
        public decimal? BrC7R096 { get; set; }
        public string BrC2R099 { get; set; }
        public string BrC3R099 { get; set; }
        public decimal? BrC4R099 { get; set; }
        public decimal? BrC5R099 { get; set; }
        public decimal? BrC6R099 { get; set; }
        public decimal? BrC7R099 { get; set; }
        public string BrC2R100 { get; set; }
        public string BrC3R100 { get; set; }
        public decimal? BrC4R100 { get; set; }
        public decimal? BrC5R100 { get; set; }
        public decimal? BrC6R100 { get; set; }
        public decimal? BrC7R100 { get; set; }
        public string BrC2R101 { get; set; }
        public string BrC3R101 { get; set; }
        public decimal? BrC4R101 { get; set; }
        public decimal? BrC5R101 { get; set; }
        public decimal? BrC6R101 { get; set; }
        public decimal? BrC7R101 { get; set; }
        public string BrC2R102 { get; set; }
        public string BrC3R102 { get; set; }
        public decimal? BrC4R102 { get; set; }
        public decimal? BrC5R102 { get; set; }
        public decimal? BrC6R102 { get; set; }
        public decimal? BrC7R102 { get; set; }
        public string BrC2R103 { get; set; }
        public string BrC3R103 { get; set; }
        public decimal? BrC4R103 { get; set; }
        public decimal? BrC5R103 { get; set; }
        public decimal? BrC6R103 { get; set; }
        public decimal? BrC7R103 { get; set; }
        public string BrC2R104 { get; set; }
        public string BrC3R104 { get; set; }
        public decimal? BrC4R104 { get; set; }
        public decimal? BrC5R104 { get; set; }
        public decimal? BrC6R104 { get; set; }
        public decimal? BrC7R104 { get; set; }
        public string BrC2R110 { get; set; }
        public string BrC3R110 { get; set; }
        public decimal? BrC4R110 { get; set; }
        public decimal? BrC5R110 { get; set; }
        public decimal? BrC6R110 { get; set; }
        public decimal? BrC7R110 { get; set; }
        public string BeC2R150 { get; set; }
        public string BeC3R150 { get; set; }
        public decimal? BeC4R150 { get; set; }
        public decimal? BeC5R150 { get; set; }
        public decimal? BeC6R150 { get; set; }
        public decimal? BeC7R150 { get; set; }
        public string BeC2R160 { get; set; }
        public string BeC3R160 { get; set; }
        public decimal? BeC4R160 { get; set; }
        public decimal? BeC5R160 { get; set; }
        public decimal? BeC6R160 { get; set; }
        public decimal? BeC7R160 { get; set; }
        public string BeC2R161 { get; set; }
        public string BeC3R161 { get; set; }
        public decimal? BeC4R161 { get; set; }
        public decimal? BeC5R161 { get; set; }
        public decimal? BeC6R161 { get; set; }
        public decimal? BeC7R161 { get; set; }
        public string BeC2R162 { get; set; }
        public string BeC3R162 { get; set; }
        public decimal? BeC4R162 { get; set; }
        public decimal? BeC5R162 { get; set; }
        public decimal? BeC6R162 { get; set; }
        public decimal? BeC7R162 { get; set; }
        public string BeC2R163 { get; set; }
        public string BeC3R163 { get; set; }
        public decimal? BeC4R163 { get; set; }
        public decimal? BeC5R163 { get; set; }
        public decimal? BeC6R163 { get; set; }
        public decimal? BeC7R163 { get; set; }
        public string BeC2R170 { get; set; }
        public string BeC3R170 { get; set; }
        public decimal? BeC4R170 { get; set; }
        public decimal? BeC5R170 { get; set; }
        public decimal? BeC6R170 { get; set; }
        public decimal? BeC7R170 { get; set; }
        public string BeC2R171 { get; set; }
        public string BeC3R171 { get; set; }
        public decimal? BeC4R171 { get; set; }
        public decimal? BeC5R171 { get; set; }
        public decimal? BeC6R171 { get; set; }
        public decimal? BeC7R171 { get; set; }
        public string BeC2R172 { get; set; }
        public string BeC3R172 { get; set; }
        public decimal? BeC4R172 { get; set; }
        public decimal? BeC5R172 { get; set; }
        public decimal? BeC6R172 { get; set; }
        public decimal? BeC7R172 { get; set; }
        public string BeC2R173 { get; set; }
        public string BeC3R173 { get; set; }
        public decimal? BeC4R173 { get; set; }
        public decimal? BeC5R173 { get; set; }
        public decimal? BeC6R173 { get; set; }
        public decimal? BeC7R173 { get; set; }
        public string BeC2R174 { get; set; }
        public string BeC3R174 { get; set; }
        public decimal? BeC4R174 { get; set; }
        public decimal? BeC5R174 { get; set; }
        public decimal? BeC6R174 { get; set; }
        public decimal? BeC7R174 { get; set; }
        public string BeC2R175 { get; set; }
        public string BeC3R175 { get; set; }
        public decimal? BeC4R175 { get; set; }
        public decimal? BeC5R175 { get; set; }
        public decimal? BeC6R175 { get; set; }
        public decimal? BeC7R175 { get; set; }
        public string BeC2R176 { get; set; }
        public string BeC3R176 { get; set; }
        public decimal? BeC4R176 { get; set; }
        public decimal? BeC5R176 { get; set; }
        public decimal? BeC6R176 { get; set; }
        public decimal? BeC7R176 { get; set; }
        public string BeC2R190 { get; set; }
        public string BeC3R190 { get; set; }
        public decimal? BeC4R190 { get; set; }
        public decimal? BeC5R190 { get; set; }
        public decimal? BeC6R190 { get; set; }
        public decimal? BeC7R190 { get; set; }
        public string BeC2R191 { get; set; }
        public string BeC3R191 { get; set; }
        public decimal? BeC4R191 { get; set; }
        public decimal? BeC5R191 { get; set; }
        public decimal? BeC6R191 { get; set; }
        public decimal? BeC7R191 { get; set; }
        public string BeC2R192 { get; set; }
        public string BeC3R192 { get; set; }
        public decimal? BeC4R192 { get; set; }
        public decimal? BeC5R192 { get; set; }
        public decimal? BeC6R192 { get; set; }
        public decimal? BeC7R192 { get; set; }
        public string BeC2R210 { get; set; }
        public string BeC3R210 { get; set; }
        public decimal? BeC4R210 { get; set; }
        public decimal? BeC5R210 { get; set; }
        public decimal? BeC6R210 { get; set; }
        public decimal? BeC7R210 { get; set; }
        public string BeC2R211 { get; set; }
        public string BeC3R211 { get; set; }
        public decimal? BeC4R211 { get; set; }
        public decimal? BeC5R211 { get; set; }
        public decimal? BeC6R211 { get; set; }
        public decimal? BeC7R211 { get; set; }
        public string BeC2R212 { get; set; }
        public string BeC3R212 { get; set; }
        public decimal? BeC4R212 { get; set; }
        public decimal? BeC5R212 { get; set; }
        public decimal? BeC6R212 { get; set; }
        public decimal? BeC7R212 { get; set; }
        public string BeC2R230 { get; set; }
        public string BeC3R230 { get; set; }
        public decimal? BeC4R230 { get; set; }
        public decimal? BeC5R230 { get; set; }
        public decimal? BeC6R230 { get; set; }
        public decimal? BeC7R230 { get; set; }
        public string BeC2R232 { get; set; }
        public string BeC3R232 { get; set; }
        public decimal? BeC4R232 { get; set; }
        public decimal? BeC5R232 { get; set; }
        public decimal? BeC6R232 { get; set; }
        public decimal? BeC7R232 { get; set; }
        public string BeC2R233 { get; set; }
        public string BeC3R233 { get; set; }
        public decimal? BeC4R233 { get; set; }
        public decimal? BeC5R233 { get; set; }
        public decimal? BeC6R233 { get; set; }
        public decimal? BeC7R233 { get; set; }
        public string BeC2R240 { get; set; }
        public string BeC3R240 { get; set; }
        public decimal? BeC4R240 { get; set; }
        public decimal? BeC5R240 { get; set; }
        public decimal? BeC6R240 { get; set; }
        public decimal? BeC7R240 { get; set; }
        public string BeC2R242 { get; set; }
        public string BeC3R242 { get; set; }
        public decimal? BeC4R242 { get; set; }
        public decimal? BeC5R242 { get; set; }
        public decimal? BeC6R242 { get; set; }
        public decimal? BeC7R242 { get; set; }
        public string BeC2R243 { get; set; }
        public string BeC3R243 { get; set; }
        public decimal? BeC4R243 { get; set; }
        public decimal? BeC5R243 { get; set; }
        public decimal? BeC6R243 { get; set; }
        public decimal? BeC7R243 { get; set; }
        public string BeC2R250 { get; set; }
        public string BeC3R250 { get; set; }
        public decimal? BeC4R250 { get; set; }
        public decimal? BeC5R250 { get; set; }
        public decimal? BeC6R250 { get; set; }
        public decimal? BeC7R250 { get; set; }
        public string BeC2R260 { get; set; }
        public string BeC3R260 { get; set; }
        public decimal? BeC4R260 { get; set; }
        public decimal? BeC5R260 { get; set; }
        public decimal? BeC6R260 { get; set; }
        public decimal? BeC7R260 { get; set; }
        public string BeC2R261 { get; set; }
        public string BeC3R261 { get; set; }
        public decimal? BeC4R261 { get; set; }
        public decimal? BeC5R261 { get; set; }
        public decimal? BeC6R261 { get; set; }
        public decimal? BeC7R261 { get; set; }
        public string BeC2R264 { get; set; }
        public string BeC3R264 { get; set; }
        public decimal? BeC4R264 { get; set; }
        public decimal? BeC5R264 { get; set; }
        public decimal? BeC6R264 { get; set; }
        public decimal? BeC7R264 { get; set; }
        public string BeC2R269 { get; set; }
        public string BeC3R269 { get; set; }
        public decimal? BeC4R269 { get; set; }
        public decimal? BeC5R269 { get; set; }
        public decimal? BeC6R269 { get; set; }
        public decimal? BeC7R269 { get; set; }
        public string BeC2R290 { get; set; }
        public string BeC3R290 { get; set; }
        public decimal? BeC4R290 { get; set; }
        public decimal? BeC5R290 { get; set; }
        public decimal? BeC6R290 { get; set; }
        public decimal? BeC7R290 { get; set; }
        public string BeC2R300 { get; set; }
        public string BeC3R300 { get; set; }
        public decimal? BeC4R300 { get; set; }
        public decimal? BeC5R300 { get; set; }
        public decimal? BeC6R300 { get; set; }
        public decimal? BeC7R300 { get; set; }
        public string BeC2R301 { get; set; }
        public string BeC3R301 { get; set; }
        public decimal? BeC4R301 { get; set; }
        public decimal? BeC5R301 { get; set; }
        public decimal? BeC6R301 { get; set; }
        public decimal? BeC7R301 { get; set; }
        public string BeC2R302 { get; set; }
        public string BeC3R302 { get; set; }
        public decimal? BeC4R302 { get; set; }
        public decimal? BeC5R302 { get; set; }
        public decimal? BeC6R302 { get; set; }
        public decimal? BeC7R302 { get; set; }
        public string BeC2R310 { get; set; }
        public string BeC3R310 { get; set; }
        public decimal? BeC4R310 { get; set; }
        public decimal? BeC5R310 { get; set; }
        public decimal? BeC6R310 { get; set; }
        public decimal? BeC7R310 { get; set; }
        public string BeC2R320 { get; set; }
        public string BeC3R320 { get; set; }
        public decimal? BeC4R320 { get; set; }
        public decimal? BeC5R320 { get; set; }
        public decimal? BeC6R320 { get; set; }
        public decimal? BeC7R320 { get; set; }
        public string BeC2R321 { get; set; }
        public string BeC3R321 { get; set; }
        public decimal? BeC4R321 { get; set; }
        public decimal? BeC5R321 { get; set; }
        public decimal? BeC6R321 { get; set; }
        public decimal? BeC7R321 { get; set; }
        public string BeC2R322 { get; set; }
        public string BeC3R322 { get; set; }
        public decimal? BeC4R322 { get; set; }
        public decimal? BeC5R322 { get; set; }
        public decimal? BeC6R322 { get; set; }
        public decimal? BeC7R322 { get; set; }
        public string BeC2R330 { get; set; }
        public string BeC3R330 { get; set; }
        public decimal? BeC4R330 { get; set; }
        public decimal? BeC5R330 { get; set; }
        public decimal? BeC6R330 { get; set; }
        public decimal? BeC7R330 { get; set; }
        public string BeC2R331 { get; set; }
        public string BeC3R331 { get; set; }
        public decimal? BeC4R331 { get; set; }
        public decimal? BeC5R331 { get; set; }
        public decimal? BeC6R331 { get; set; }
        public decimal? BeC7R331 { get; set; }
        public string BeC2R332 { get; set; }
        public string BeC3R332 { get; set; }
        public decimal? BeC4R332 { get; set; }
        public decimal? BeC5R332 { get; set; }
        public decimal? BeC6R332 { get; set; }
        public decimal? BeC7R332 { get; set; }
        public string BeC2R350 { get; set; }
        public string BeC3R350 { get; set; }
        public decimal? BeC4R350 { get; set; }
        public decimal? BeC5R350 { get; set; }
        public decimal? BeC6R350 { get; set; }
        public decimal? BeC7R350 { get; set; }
        public string BeC2R351 { get; set; }
        public string BeC3R351 { get; set; }
        public decimal? BeC4R351 { get; set; }
        public decimal? BeC5R351 { get; set; }
        public decimal? BeC6R351 { get; set; }
        public decimal? BeC7R351 { get; set; }
        public string BeC2R352 { get; set; }
        public string BeC3R352 { get; set; }
        public decimal? BeC4R352 { get; set; }
        public decimal? BeC5R352 { get; set; }
        public decimal? BeC6R352 { get; set; }
        public decimal? BeC7R352 { get; set; }
        public string BeC2R360 { get; set; }
        public string BeC3R360 { get; set; }
        public decimal? BeC4R360 { get; set; }
        public decimal? BeC5R360 { get; set; }
        public decimal? BeC6R360 { get; set; }
        public decimal? BeC7R360 { get; set; }
        public string BeC2R361 { get; set; }
        public string BeC3R361 { get; set; }
        public decimal? BeC4R361 { get; set; }
        public decimal? BeC5R361 { get; set; }
        public decimal? BeC6R361 { get; set; }
        public decimal? BeC7R361 { get; set; }
        public string BeC2R362 { get; set; }
        public string BeC3R362 { get; set; }
        public decimal? BeC4R362 { get; set; }
        public decimal? BeC5R362 { get; set; }
        public decimal? BeC6R362 { get; set; }
        public decimal? BeC7R362 { get; set; }
        public string BeC2R370 { get; set; }
        public string BeC3R370 { get; set; }
        public decimal? BeC4R370 { get; set; }
        public decimal? BeC5R370 { get; set; }
        public decimal? BeC6R370 { get; set; }
        public decimal? BeC7R370 { get; set; }
        public string BeC2R371 { get; set; }
        public string BeC3R371 { get; set; }
        public decimal? BeC4R371 { get; set; }
        public decimal? BeC5R371 { get; set; }
        public decimal? BeC6R371 { get; set; }
        public decimal? BeC7R371 { get; set; }
        public string BeC2R372 { get; set; }
        public string BeC3R372 { get; set; }
        public decimal? BeC4R372 { get; set; }
        public decimal? BeC5R372 { get; set; }
        public decimal? BeC6R372 { get; set; }
        public decimal? BeC7R372 { get; set; }
        public string OfaC2R380 { get; set; }
        public string OfaC3R380 { get; set; }
        public decimal? OfaC4R380 { get; set; }
        public decimal? OfaC5R380 { get; set; }
        public decimal? OfaC6R380 { get; set; }
        public decimal? OfaC7R380 { get; set; }
        public string OfaC2R390 { get; set; }
        public string OfaC3R390 { get; set; }
        public decimal? OfaC4R390 { get; set; }
        public decimal? OfaC5R390 { get; set; }
        public decimal? OfaC6R390 { get; set; }
        public decimal? OfaC7R390 { get; set; }
        public string OfaC2R410 { get; set; }
        public string OfaC3R410 { get; set; }
        public decimal? OfaC4R410 { get; set; }
        public decimal? OfaC5R410 { get; set; }
        public decimal? OfaC6R410 { get; set; }
        public decimal? OfaC7R410 { get; set; }
        public string OfaC2R411 { get; set; }
        public string OfaC3R411 { get; set; }
        public decimal? OfaC4R411 { get; set; }
        public decimal? OfaC5R411 { get; set; }
        public decimal? OfaC6R411 { get; set; }
        public decimal? OfaC7R411 { get; set; }
        public string OfaC2R412 { get; set; }
        public string OfaC3R412 { get; set; }
        public decimal? OfaC4R412 { get; set; }
        public decimal? OfaC5R412 { get; set; }
        public decimal? OfaC6R412 { get; set; }
        public decimal? OfaC7R412 { get; set; }
        public string OfaC2R420 { get; set; }
        public string OfaC3R420 { get; set; }
        public decimal? OfaC4R420 { get; set; }
        public decimal? OfaC5R420 { get; set; }
        public decimal? OfaC6R420 { get; set; }
        public decimal? OfaC7R420 { get; set; }
        public string OfaC2R421 { get; set; }
        public string OfaC3R421 { get; set; }
        public decimal? OfaC4R421 { get; set; }
        public decimal? OfaC5R421 { get; set; }
        public decimal? OfaC6R421 { get; set; }
        public decimal? OfaC7R421 { get; set; }
        public string OfaC2R422 { get; set; }
        public string OfaC3R422 { get; set; }
        public decimal? OfaC4R422 { get; set; }
        public decimal? OfaC5R422 { get; set; }
        public decimal? OfaC6R422 { get; set; }
        public decimal? OfaC7R422 { get; set; }
        public string OfaC2R440 { get; set; }
        public string OfaC3R440 { get; set; }
        public decimal? OfaC4R440 { get; set; }
        public decimal? OfaC5R440 { get; set; }
        public decimal? OfaC6R440 { get; set; }
        public decimal? OfaC7R440 { get; set; }
        public string OfaC2R441 { get; set; }
        public string OfaC3R441 { get; set; }
        public decimal? OfaC4R441 { get; set; }
        public decimal? OfaC5R441 { get; set; }
        public decimal? OfaC6R441 { get; set; }
        public decimal? OfaC7R441 { get; set; }
        public string OfaC2R442 { get; set; }
        public string OfaC3R442 { get; set; }
        public decimal? OfaC4R442 { get; set; }
        public decimal? OfaC5R442 { get; set; }
        public decimal? OfaC6R442 { get; set; }
        public decimal? OfaC7R442 { get; set; }
        public string OfaC2R460 { get; set; }
        public string OfaC3R460 { get; set; }
        public decimal? OfaC4R460 { get; set; }
        public decimal? OfaC5R460 { get; set; }
        public decimal? OfaC6R460 { get; set; }
        public decimal? OfaC7R460 { get; set; }
        public string OfaC2R461 { get; set; }
        public string OfaC3R461 { get; set; }
        public decimal? OfaC4R461 { get; set; }
        public decimal? OfaC5R461 { get; set; }
        public decimal? OfaC6R461 { get; set; }
        public decimal? OfaC7R461 { get; set; }
        public string OfaC2R462 { get; set; }
        public string OfaC3R462 { get; set; }
        public decimal? OfaC4R462 { get; set; }
        public decimal? OfaC5R462 { get; set; }
        public decimal? OfaC6R462 { get; set; }
        public decimal? OfaC7R462 { get; set; }
        public string OfaC2R470 { get; set; }
        public string OfaC3R470 { get; set; }
        public decimal? OfaC4R470 { get; set; }
        public decimal? OfaC5R470 { get; set; }
        public decimal? OfaC6R470 { get; set; }
        public decimal? OfaC7R470 { get; set; }
        public string OfaC2R471 { get; set; }
        public string OfaC3R471 { get; set; }
        public decimal? OfaC4R471 { get; set; }
        public decimal? OfaC5R471 { get; set; }
        public decimal? OfaC6R471 { get; set; }
        public decimal? OfaC7R471 { get; set; }
        public string OfaC2R472 { get; set; }
        public string OfaC3R472 { get; set; }
        public decimal? OfaC4R472 { get; set; }
        public decimal? OfaC5R472 { get; set; }
        public decimal? OfaC6R472 { get; set; }
        public decimal? OfaC7R472 { get; set; }
        public string OfaC2R480 { get; set; }
        public string OfaC3R480 { get; set; }
        public decimal? OfaC4R480 { get; set; }
        public decimal? OfaC5R480 { get; set; }
        public decimal? OfaC6R480 { get; set; }
        public decimal? OfaC7R480 { get; set; }
        public string OfaC2R481 { get; set; }
        public string OfaC3R481 { get; set; }
        public decimal? OfaC4R481 { get; set; }
        public decimal? OfaC5R481 { get; set; }
        public decimal? OfaC6R481 { get; set; }
        public decimal? OfaC7R481 { get; set; }
        public string OfaC2R482 { get; set; }
        public string OfaC3R482 { get; set; }
        public decimal? OfaC4R482 { get; set; }
        public decimal? OfaC5R482 { get; set; }
        public decimal? OfaC6R482 { get; set; }
        public decimal? OfaC7R482 { get; set; }
        public string OfaC2R510 { get; set; }
        public string OfaC3R510 { get; set; }
        public decimal? OfaC4R510 { get; set; }
        public decimal? OfaC5R510 { get; set; }
        public decimal? OfaC6R510 { get; set; }
        public decimal? OfaC7R510 { get; set; }
        public string OfaC2R520 { get; set; }
        public string OfaC3R520 { get; set; }
        public decimal? OfaC4R520 { get; set; }
        public decimal? OfaC5R520 { get; set; }
        public decimal? OfaC6R520 { get; set; }
        public decimal? OfaC7R520 { get; set; }
        public string OfaC2R521 { get; set; }
        public string OfaC3R521 { get; set; }
        public decimal? OfaC4R521 { get; set; }
        public decimal? OfaC5R521 { get; set; }
        public decimal? OfaC6R521 { get; set; }
        public decimal? OfaC7R521 { get; set; }
        public string OfaC2R522 { get; set; }
        public string OfaC3R522 { get; set; }
        public decimal? OfaC4R522 { get; set; }
        public decimal? OfaC5R522 { get; set; }
        public decimal? OfaC6R522 { get; set; }
        public decimal? OfaC7R522 { get; set; }
        public string OfaC2R530 { get; set; }
        public string OfaC3R530 { get; set; }
        public decimal? OfaC4R530 { get; set; }
        public decimal? OfaC5R530 { get; set; }
        public decimal? OfaC6R530 { get; set; }
        public decimal? OfaC7R530 { get; set; }
        public string OfaC2R531 { get; set; }
        public string OfaC3R531 { get; set; }
        public decimal? OfaC4R531 { get; set; }
        public decimal? OfaC5R531 { get; set; }
        public decimal? OfaC6R531 { get; set; }
        public decimal? OfaC7R531 { get; set; }
        public string OfaC2R532 { get; set; }
        public string OfaC3R532 { get; set; }
        public decimal? OfaC4R532 { get; set; }
        public decimal? OfaC5R532 { get; set; }
        public decimal? OfaC6R532 { get; set; }
        public decimal? OfaC7R532 { get; set; }
        public string OfaC2R540 { get; set; }
        public string OfaC3R540 { get; set; }
        public decimal? OfaC4R540 { get; set; }
        public decimal? OfaC5R540 { get; set; }
        public decimal? OfaC6R540 { get; set; }
        public decimal? OfaC7R540 { get; set; }
        public string OfaC2R541 { get; set; }
        public string OfaC3R541 { get; set; }
        public decimal? OfaC4R541 { get; set; }
        public decimal? OfaC5R541 { get; set; }
        public decimal? OfaC6R541 { get; set; }
        public decimal? OfaC7R541 { get; set; }
        public string OfaC2R542 { get; set; }
        public string OfaC3R542 { get; set; }
        public decimal? OfaC4R542 { get; set; }
        public decimal? OfaC5R542 { get; set; }
        public decimal? OfaC6R542 { get; set; }
        public decimal? OfaC7R542 { get; set; }
        public bool? Subdiv { get; set; }
        public string HrNamtip { get; set; }
        public string HrTypesubotch { get; set; }
        public string Ord { get; set; }
        public string Nameseparatedivision { get; set; }
        public string Codeseparatedivision { get; set; }
        public string Namefounder { get; set; }
        public string Codefounder { get; set; }
        public string Namebodyactingfounder { get; set; }
        public string Codebodyactingfounder { get; set; }
        public string PenPfnLeader { get; set; }
        public string PenPfnChiefAcc { get; set; }
        public string PenPfnLeaderOfFes { get; set; }
        public string PenPfnPostLeader { get; set; }
        public string PenPfnPostChiefAcc { get; set; }
        public string PenPfnPostLeaderOf { get; set; }
        public string PenPfnExecutor { get; set; }
        public string PenPfnPostExecutor { get; set; }
        public string PenPfnPhone { get; set; }
        public string PenCentraccCode { get; set; }
        public string PenCentraccName { get; set; }
        public string PenCentraccOgrn { get; set; }
        public string PenCentraccInn { get; set; }
        public string PenCentraccKpp { get; set; }
        public string PenCentraccAddress { get; set; }
        public string PenCentraccLdr { get; set; }
        public string PenCentraccExec { get; set; }
        public string PenCentraccLdr1 { get; set; }
        public string PenCentraccExec1 { get; set; }
        public string PenCentraccExecm { get; set; }
        public string PenExecuter { get; set; }
        public string PenPostExec { get; set; }
        public string ReportBaseErOkpo1 { get; set; }
    }
}
