using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcReport0503150
    {
        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string HrPnfLeader { get; set; }
        public string HrPnfChiefAcc { get; set; }
        public string HrPnfLeaderOfFes { get; set; }
        public string HrPnfPostLeader { get; set; }
        public string HrPnfPostChiefAcc { get; set; }
        public string HrPnfPostLeaderOf { get; set; }
        public string HrPnfExecutor { get; set; }
        public string HrPnfPostExecutor { get; set; }
        public string HrPnfPhone { get; set; }
        public string HrOrd { get; set; }
        public string HrNamtip { get; set; }
        public string HrKodTofk { get; set; }
        public string HrNameTofk { get; set; }
        public string HrBudgLevel { get; set; }
        public string HrKodUbp { get; set; }
        public string HrNameUbp { get; set; }
        public string HrPrizSo { get; set; }
        public string HrSubotch { get; set; }
        public string HrPrizOb { get; set; }
        public string HrTelIsp { get; set; }
        public string HrCommenty { get; set; }
        public string Surrogat { get; set; }
        public string AS0102 { get; set; }
        public decimal? AS0103 { get; set; }
        public decimal? AS0104 { get; set; }
        public decimal? AS0105 { get; set; }
        public decimal? AS0106 { get; set; }
        public decimal? AS0107 { get; set; }
        public decimal? AS0108 { get; set; }
        public string AS0112 { get; set; }
        public decimal? AS0113 { get; set; }
        public decimal? AS0114 { get; set; }
        public decimal? AS0115 { get; set; }
        public decimal? AS0116 { get; set; }
        public decimal? AS0117 { get; set; }
        public decimal? AS0118 { get; set; }
        public string AS0122 { get; set; }
        public decimal? AS0123 { get; set; }
        public decimal? AS0124 { get; set; }
        public decimal? AS0125 { get; set; }
        public decimal? AS0126 { get; set; }
        public decimal? AS0127 { get; set; }
        public decimal? AS0128 { get; set; }
        public string AS0202 { get; set; }
        public decimal? AS0203 { get; set; }
        public decimal? AS0204 { get; set; }
        public decimal? AS0205 { get; set; }
        public decimal? AS0206 { get; set; }
        public decimal? AS0207 { get; set; }
        public decimal? AS0208 { get; set; }
        public string AS0312 { get; set; }
        public decimal? AS0313 { get; set; }
        public decimal? AS0314 { get; set; }
        public decimal? AS0315 { get; set; }
        public decimal? AS0316 { get; set; }
        public decimal? AS0317 { get; set; }
        public decimal? AS0318 { get; set; }
        public string AS0402 { get; set; }
        public decimal? AS0403 { get; set; }
        public decimal? AS0404 { get; set; }
        public decimal? AS0405 { get; set; }
        public decimal? AS0406 { get; set; }
        public decimal? AS0407 { get; set; }
        public decimal? AS0408 { get; set; }
        public string AS0502 { get; set; }
        public decimal? AS0503 { get; set; }
        public decimal? AS0504 { get; set; }
        public decimal? AS0505 { get; set; }
        public decimal? AS0506 { get; set; }
        public decimal? AS0507 { get; set; }
        public decimal? AS0508 { get; set; }
        public string AS0602 { get; set; }
        public decimal? AS0603 { get; set; }
        public decimal? AS0604 { get; set; }
        public decimal? AS0605 { get; set; }
        public decimal? AS0606 { get; set; }
        public decimal? AS0607 { get; set; }
        public decimal? AS0608 { get; set; }
        public string AS0702 { get; set; }
        public decimal? AS0703 { get; set; }
        public decimal? AS0704 { get; set; }
        public decimal? AS0705 { get; set; }
        public decimal? AS0706 { get; set; }
        public decimal? AS0707 { get; set; }
        public decimal? AS0708 { get; set; }
        public string AS0100 { get; set; }
        public string AS0101 { get; set; }
        public string AS0110 { get; set; }
        public string AS0111 { get; set; }
        public string AS0120 { get; set; }
        public string AS0121 { get; set; }
        public string AS0200 { get; set; }
        public string AS0201 { get; set; }
        public string AS0310 { get; set; }
        public string AS0311 { get; set; }
        public string AS0400 { get; set; }
        public string AS0401 { get; set; }
        public string AS0500 { get; set; }
        public string AS0501 { get; set; }
        public string AS0600 { get; set; }
        public string AS0601 { get; set; }
        public string AS0700 { get; set; }
        public string AS0701 { get; set; }
        public string PS0902 { get; set; }
        public decimal? PS0903 { get; set; }
        public decimal? PS0904 { get; set; }
        public decimal? PS0905 { get; set; }
        public decimal? PS0906 { get; set; }
        public decimal? PS0907 { get; set; }
        public decimal? PS0908 { get; set; }
        public string PS1012 { get; set; }
        public decimal? PS1013 { get; set; }
        public decimal? PS1014 { get; set; }
        public decimal? PS1015 { get; set; }
        public decimal? PS1016 { get; set; }
        public decimal? PS1017 { get; set; }
        public decimal? PS1018 { get; set; }
        public string PS1102 { get; set; }
        public decimal? PS1103 { get; set; }
        public decimal? PS1104 { get; set; }
        public decimal? PS1105 { get; set; }
        public decimal? PS1106 { get; set; }
        public decimal? PS1107 { get; set; }
        public decimal? PS1108 { get; set; }
        public string PS1202 { get; set; }
        public decimal? PS1203 { get; set; }
        public decimal? PS1204 { get; set; }
        public decimal? PS1205 { get; set; }
        public decimal? PS1206 { get; set; }
        public decimal? PS1207 { get; set; }
        public decimal? PS1208 { get; set; }
        public string PS1502 { get; set; }
        public decimal? PS1503 { get; set; }
        public decimal? PS1504 { get; set; }
        public decimal? PS1505 { get; set; }
        public decimal? PS1506 { get; set; }
        public decimal? PS1507 { get; set; }
        public decimal? PS1508 { get; set; }
        public string PS1802 { get; set; }
        public decimal? PS1803 { get; set; }
        public decimal? PS1804 { get; set; }
        public decimal? PS1805 { get; set; }
        public decimal? PS1806 { get; set; }
        public decimal? PS1807 { get; set; }
        public decimal? PS1808 { get; set; }
        public string PS1902 { get; set; }
        public decimal? PS1903 { get; set; }
        public decimal? PS1904 { get; set; }
        public decimal? PS1905 { get; set; }
        public decimal? PS1906 { get; set; }
        public decimal? PS1907 { get; set; }
        public decimal? PS1908 { get; set; }
        public string PS191S2 { get; set; }
        public decimal? PS191S3 { get; set; }
        public decimal? PS191S4 { get; set; }
        public decimal? PS191S5 { get; set; }
        public decimal? PS191S6 { get; set; }
        public decimal? PS191S7 { get; set; }
        public decimal? PS191S8 { get; set; }
        public string PS191S0 { get; set; }
        public string PS191S1 { get; set; }
        public string PS192S2 { get; set; }
        public decimal? PS192S3 { get; set; }
        public decimal? PS192S4 { get; set; }
        public decimal? PS192S5 { get; set; }
        public decimal? PS192S6 { get; set; }
        public decimal? PS192S7 { get; set; }
        public decimal? PS192S8 { get; set; }
        public string PS192S0 { get; set; }
        public string PS192S1 { get; set; }
        public string PS193S2 { get; set; }
        public decimal? PS193S3 { get; set; }
        public decimal? PS193S4 { get; set; }
        public decimal? PS193S5 { get; set; }
        public decimal? PS193S6 { get; set; }
        public decimal? PS193S7 { get; set; }
        public decimal? PS193S8 { get; set; }
        public string PS193S0 { get; set; }
        public string PS193S1 { get; set; }
        public string PS194S2 { get; set; }
        public decimal? PS194S3 { get; set; }
        public decimal? PS194S4 { get; set; }
        public decimal? PS194S5 { get; set; }
        public decimal? PS194S6 { get; set; }
        public decimal? PS194S7 { get; set; }
        public decimal? PS194S8 { get; set; }
        public string PS194S0 { get; set; }
        public string PS194S1 { get; set; }
        public string PS210S2 { get; set; }
        public decimal? PS210S3 { get; set; }
        public decimal? PS210S4 { get; set; }
        public decimal? PS210S5 { get; set; }
        public decimal? PS210S6 { get; set; }
        public decimal? PS210S7 { get; set; }
        public decimal? PS210S8 { get; set; }
        public string PS210S0 { get; set; }
        public string PS210S1 { get; set; }
        public string PS220S2 { get; set; }
        public decimal? PS220S3 { get; set; }
        public decimal? PS220S4 { get; set; }
        public decimal? PS220S5 { get; set; }
        public decimal? PS220S6 { get; set; }
        public decimal? PS220S7 { get; set; }
        public decimal? PS220S8 { get; set; }
        public string PS220S0 { get; set; }
        public string PS220S1 { get; set; }
        public string PS230S2 { get; set; }
        public decimal? PS230S3 { get; set; }
        public decimal? PS230S4 { get; set; }
        public decimal? PS230S5 { get; set; }
        public decimal? PS230S6 { get; set; }
        public decimal? PS230S7 { get; set; }
        public decimal? PS230S8 { get; set; }
        public string PS230S0 { get; set; }
        public string PS230S1 { get; set; }
        public string PS0900 { get; set; }
        public string PS0901 { get; set; }
        public string PS1010 { get; set; }
        public string PS1011 { get; set; }
        public string PS1100 { get; set; }
        public string PS1101 { get; set; }
        public string PS1200 { get; set; }
        public string PS1201 { get; set; }
        public string PS1500 { get; set; }
        public string PS1501 { get; set; }
        public string PS1800 { get; set; }
        public string PS1801 { get; set; }
        public string PS1900 { get; set; }
        public string PS1901 { get; set; }
    }
}
