using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcReportBase
    {
        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string Surrogat { get; set; }
        public string ReportNum { get; set; }
        public string Codereportform { get; set; }
        public string HrErNameOfEntity { get; set; }
        public string HrErCodeOfEntity { get; set; }
        public string HrErOkpo { get; set; }
        public string HrErOktmo { get; set; }
        public string HrErGlavaBk { get; set; }
        public string HrErSubotch { get; set; }
        public string HrErInn { get; set; }
        public string HrErCdofentalt { get; set; }
        public string HrErPrcdofent { get; set; }
        public string HrErPrnmofent { get; set; }
        public string HrPeriodType { get; set; }
        public DateTime? HrReportDate { get; set; }
        public string HrInstitutionCode { get; set; }
        public string HrAccountcode { get; set; }
        public bool? HrUsersing { get; set; }
        public string HrAiCode { get; set; }
        public string HrAiName { get; set; }
        public string HrNamtip { get; set; }
        public string HrTypeactivityname { get; set; }
        public string HrTypeactivitycode { get; set; }
        public string HrBtCodeOfBudget { get; set; }
        public string HrBtNameOfBudget { get; set; }
        public string HrBtCodeOfType { get; set; }
        public string HrTofkcode { get; set; }
        public string HrUbpcode { get; set; }
        public DateTime? HrDataStartactive { get; set; }
        public DateTime? HrDataEndactive { get; set; }
        public string HrCdrf { get; set; }
        public string HrIndicators { get; set; }
        public string HrCodf { get; set; }
        public string HrOffice { get; set; }
        public string HrReorg { get; set; }
        public string HrGlavaReorg { get; set; }
        public string HrOktmoReorg { get; set; }
        public string HrCodeReorg { get; set; }
        public string HrReorgTex { get; set; }
        public bool? HrCheckreorg { get; set; }
        public string StatctrlsStateidc { get; set; }
        public string StatctrlsStatebdc { get; set; }
        public string StatctrlsStateflc { get; set; }
        public string StatctrlsStateexc { get; set; }
        public string StatctrlsGuidflc { get; set; }
        public string StatctrlsGuididc { get; set; }
        public string StatctrlsGuidbdc { get; set; }
        public string StatctrlsGuidexc { get; set; }
        public string StatctrlsGuidprimeexc { get; set; }
        public string Currentapprover { get; set; }
        public string Nextapprover { get; set; }
        public string Fullyapproved { get; set; }
        public string Approvalstate { get; set; }
        public string Typeagreement { get; set; }
        public string Namereportform { get; set; }
        public string Reporttype { get; set; }
        public string Filename { get; set; }
        public DateTime? Importdatetime { get; set; }
        public string ComplectCode { get; set; }
        public string PeriodCode { get; set; }
        public string ImportedWErrors { get; set; }
        public DateTime? TimeSubmit { get; set; }
        public string Reasons { get; set; }
        public string Reporttypemou { get; set; }
        public string Lastreport { get; set; }
        public string Guidconsolid { get; set; }
        public DateTime? Datestatusupdates { get; set; }
        public string Guidprimary { get; set; }
        public string Guidconsolidated { get; set; }
        public string Fksegmentcode { get; set; }
        public string Fksystem { get; set; }
        public string Stateasfk { get; set; }
        public string Asfkdocguid { get; set; }
        public string Printname { get; set; }
        public string FgSo { get; set; }
        public string FgPo { get; set; }
        public string ApLoginGb { get; set; }
        public string ApLoginRfes { get; set; }
        public string ApLoginR { get; set; }
        public string ApLoginOip { get; set; }
        public string ApFioGb { get; set; }
        public string ApFioRfes { get; set; }
        public string ApFioR { get; set; }
        public string ApFioOip { get; set; }
        public string ApDepartmentGb { get; set; }
        public string ApDepartmentRfes { get; set; }
        public string ApDepartmentR { get; set; }
        public string ApDepartmentOip { get; set; }
        public string ApPostfieldR { get; set; }
        public string ApPostfieldRfes { get; set; }
        public string ApPostfieldGb { get; set; }
        public string ApPostfieldOip { get; set; }
        public bool? ApScipsoglas { get; set; }
        public string ApSoglasGb { get; set; }
        public string ApSoglasRfes { get; set; }
        public string ApSoglasR { get; set; }
        public string ApSoglasOip { get; set; }
        public string ApNoteGb { get; set; }
        public string ApNoteRfes { get; set; }
        public string ApNoteR { get; set; }
        public string ApNoteOip { get; set; }
        public string ApSoglasCnb { get; set; }
        public string ApNoteCnb { get; set; }
        public string SignLeader { get; set; }
        public string SignChiefAcc { get; set; }
        public string SignLeaderOfFes { get; set; }
        public string SignPostLeader { get; set; }
        public string SignPostChiefAcc { get; set; }
        public string SignPostLeaderOf { get; set; }
        public string SignExecutor { get; set; }
        public string SignPostExecutor { get; set; }
        public string SignPhone { get; set; }
        public string SignFioOip { get; set; }
        public string SignPostfieldOip { get; set; }
        public string SignLdrFlg { get; set; }
        public string SignChfFlg { get; set; }
        public string SignLdrFesFlg { get; set; }
        public string SignOipFlg { get; set; }
        public string SignLdrCaFlg { get; set; }
        public bool? SignReorgSogl { get; set; }
        public string SignReorgAssign { get; set; }
        public string SignReorgNote { get; set; }
        public string Reqstate { get; set; }
        public DateTime? VnkFormationDate { get; set; }
        public bool? CheckBlockerFlk { get; set; }
        public bool? CheckBlockerVdk { get; set; }
        public bool? CheckBlockerMdk { get; set; }
        public string AgreedReorg { get; set; }
        public string StateEpbs { get; set; }
        public string Guidticket { get; set; }
        public string Guidreceipt { get; set; }
        public string CnbCode { get; set; }
        public string CnbName { get; set; }
        public string CnbOgrn { get; set; }
        public string CnbInn { get; set; }
        public string CnbKpp { get; set; }
        public string CnbCaLeader { get; set; }
        public string CnbCaExecutor { get; set; }
        public string CnbPostCaLeader { get; set; }
        public string CnbPostCaExecutor { get; set; }
        public string CnbCaExecutorMail { get; set; }
        public string CaExecutorMail { get; set; }
        public string Location { get; set; }
        public string AllPrint { get; set; }
        public bool? SubDiv { get; set; }
        public string Okved { get; set; }
        public string ImportSystem { get; set; }
        public string FahFormed { get; set; }
        public string GuidReportTech { get; set; }
        public string StatusFah { get; set; }
        public string PhaseFah { get; set; }
        public string TextFah { get; set; }
        public string RplReportNum { get; set; }
        public string RplErNameOfEntity { get; set; }
        public string RplErCodeOfEntity { get; set; }
        public string RplErOkpo { get; set; }
        public string RplErOktmo { get; set; }
        public string RplErGlavaBk { get; set; }
        public string RplErSubotch { get; set; }
        public string RplErInn { get; set; }
        public string RplErCdofentalt { get; set; }
        public string RplErPrcdofent { get; set; }
        public string RplErPrnmofent { get; set; }
        public string RplReasons1 { get; set; }
        public string RplReasons2 { get; set; }
        public string RplStateRpl { get; set; }
        public string RplGuidrpl { get; set; }
        public string RplNameOfBudget { get; set; }
        public bool? RplFlg { get; set; }
        public string SrcCons { get; set; }
        public string DocsToUpdate { get; set; }
        public string StatePiao { get; set; }
        public string ImpSecurlvcode { get; set; }
        public string ImpCommentinfo { get; set; }
        public string ImpVersionname { get; set; }
        public string ImpPath { get; set; }
        public string Periodtype { get; set; }
        public string ImpSecuritylevel { get; set; }
    }
}
