using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcReport0503768
    {
        public DcReport0503768()
        {
            FsInfmovaccTab1List = new HashSet<FsInfmovaccTab1List>();
            FsInfmovaccTab2List = new HashSet<FsInfmovaccTab2List>();
        }

        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string Nameseparatedivision { get; set; }
        public string Codeseparatedivision { get; set; }
        public string Namefounder { get; set; }
        public string Codefounder { get; set; }
        public string Namebodyactingfounder { get; set; }
        public string Codebodyactingfounder { get; set; }
        public decimal? NonfinancC4R010 { get; set; }
        public decimal? NonfinancC5R010 { get; set; }
        public decimal? NonfinancC6R010 { get; set; }
        public decimal? NonfinancC7R010 { get; set; }
        public decimal? NonfinancC4R011 { get; set; }
        public decimal? NonfinancC5R011 { get; set; }
        public decimal? NonfinancC6R011 { get; set; }
        public decimal? NonfinancC7R011 { get; set; }
        public decimal? NonfinancC4R012 { get; set; }
        public decimal? NonfinancC5R012 { get; set; }
        public decimal? NonfinancC6R012 { get; set; }
        public decimal? NonfinancC7R012 { get; set; }
        public decimal? NonfinancC4R013 { get; set; }
        public decimal? NonfinancC5R013 { get; set; }
        public decimal? NonfinancC6R013 { get; set; }
        public decimal? NonfinancC7R013 { get; set; }
        public decimal? NonfinancC4R014 { get; set; }
        public decimal? NonfinancC5R014 { get; set; }
        public decimal? NonfinancC6R014 { get; set; }
        public decimal? NonfinancC7R014 { get; set; }
        public decimal? NonfinancC4R015 { get; set; }
        public decimal? NonfinancC5R015 { get; set; }
        public decimal? NonfinancC6R015 { get; set; }
        public decimal? NonfinancC7R015 { get; set; }
        public decimal? NonfinancC4R016 { get; set; }
        public decimal? NonfinancC5R016 { get; set; }
        public decimal? NonfinancC6R016 { get; set; }
        public decimal? NonfinancC7R016 { get; set; }
        public decimal? NonfinancC4R017 { get; set; }
        public decimal? NonfinancC5R017 { get; set; }
        public decimal? NonfinancC6R017 { get; set; }
        public decimal? NonfinancC7R017 { get; set; }
        public decimal? NonfinancC4R018 { get; set; }
        public decimal? NonfinancC5R018 { get; set; }
        public decimal? NonfinancC6R018 { get; set; }
        public decimal? NonfinancC7R018 { get; set; }
        public decimal? NonfinancC4R050 { get; set; }
        public decimal? NonfinancC5R050 { get; set; }
        public decimal? NonfinancC6R050 { get; set; }
        public decimal? NonfinancC7R050 { get; set; }
        public decimal? NonfinancC4R051 { get; set; }
        public decimal? NonfinancC5R051 { get; set; }
        public decimal? NonfinancC6R051 { get; set; }
        public decimal? NonfinancC7R051 { get; set; }
        public decimal? NonfinancC4R052 { get; set; }
        public decimal? NonfinancC5R052 { get; set; }
        public decimal? NonfinancC6R052 { get; set; }
        public decimal? NonfinancC7R052 { get; set; }
        public decimal? NonfinancC4R053 { get; set; }
        public decimal? NonfinancC5R053 { get; set; }
        public decimal? NonfinancC6R053 { get; set; }
        public decimal? NonfinancC7R053 { get; set; }
        public decimal? NonfinancC4R054 { get; set; }
        public decimal? NonfinancC5R054 { get; set; }
        public decimal? NonfinancC6R054 { get; set; }
        public decimal? NonfinancC7R054 { get; set; }
        public decimal? NonfinancC4R055 { get; set; }
        public decimal? NonfinancC5R055 { get; set; }
        public decimal? NonfinancC6R055 { get; set; }
        public decimal? NonfinancC7R055 { get; set; }
        public decimal? NonfinancC4R056 { get; set; }
        public decimal? NonfinancC5R056 { get; set; }
        public decimal? NonfinancC6R056 { get; set; }
        public decimal? NonfinancC7R056 { get; set; }
        public decimal? NonfinancC4R057 { get; set; }
        public decimal? NonfinancC5R057 { get; set; }
        public decimal? NonfinancC6R057 { get; set; }
        public decimal? NonfinancC7R057 { get; set; }
        public decimal? NonfinancC4R058 { get; set; }
        public decimal? NonfinancC5R058 { get; set; }
        public decimal? NonfinancC6R058 { get; set; }
        public decimal? NonfinancC7R058 { get; set; }
        public decimal? NonfinancC4R070 { get; set; }
        public decimal? NonfinancC5R070 { get; set; }
        public decimal? NonfinancC6R070 { get; set; }
        public decimal? NonfinancC7R070 { get; set; }
        public decimal? NonfinancC4R080 { get; set; }
        public decimal? NonfinancC5R080 { get; set; }
        public decimal? NonfinancC6R080 { get; set; }
        public decimal? NonfinancC7R080 { get; set; }
        public decimal? NonfinancC4R110 { get; set; }
        public decimal? NonfinancC5R110 { get; set; }
        public decimal? NonfinancC6R110 { get; set; }
        public decimal? NonfinancC7R110 { get; set; }
        public decimal? NonfinancC4R120 { get; set; }
        public decimal? NonfinancC5R120 { get; set; }
        public decimal? NonfinancC6R120 { get; set; }
        public decimal? NonfinancC7R120 { get; set; }
        public decimal? NonfinancC4R130 { get; set; }
        public decimal? NonfinancC5R130 { get; set; }
        public decimal? NonfinancC6R130 { get; set; }
        public decimal? NonfinancC7R130 { get; set; }
        public decimal? NonfinancC4R150 { get; set; }
        public decimal? NonfinancC5R150 { get; set; }
        public decimal? NonfinancC6R150 { get; set; }
        public decimal? NonfinancC7R150 { get; set; }
        public decimal? NonfinancC4R151 { get; set; }
        public decimal? NonfinancC5R151 { get; set; }
        public decimal? NonfinancC6R151 { get; set; }
        public decimal? NonfinancC7R151 { get; set; }
        public decimal? NonfinancC4R152 { get; set; }
        public decimal? NonfinancC5R152 { get; set; }
        public decimal? NonfinancC6R152 { get; set; }
        public decimal? NonfinancC7R152 { get; set; }
        public decimal? NonfinancC4R153 { get; set; }
        public decimal? NonfinancC5R153 { get; set; }
        public decimal? NonfinancC6R153 { get; set; }
        public decimal? NonfinancC7R153 { get; set; }
        public decimal? NonfinancC4R170 { get; set; }
        public decimal? NonfinancC5R170 { get; set; }
        public decimal? NonfinancC6R170 { get; set; }
        public decimal? NonfinancC7R170 { get; set; }
        public decimal? NonfinancC4R190 { get; set; }
        public decimal? NonfinancC5R190 { get; set; }
        public decimal? NonfinancC6R190 { get; set; }
        public decimal? NonfinancC7R190 { get; set; }
        public decimal? NonfinancC4R230 { get; set; }
        public decimal? NonfinancC5R230 { get; set; }
        public decimal? NonfinancC6R230 { get; set; }
        public decimal? NonfinancC7R230 { get; set; }
        public decimal? NonfinancC4R250 { get; set; }
        public decimal? NonfinancC5R250 { get; set; }
        public decimal? NonfinancC6R250 { get; set; }
        public decimal? NonfinancC7R250 { get; set; }
        public decimal? RealpropertyC4R310 { get; set; }
        public decimal? RealpropertyC5R310 { get; set; }
        public decimal? RealpropertyC6R310 { get; set; }
        public decimal? RealpropertyC7R310 { get; set; }
        public decimal? RealpropertyC4R311 { get; set; }
        public decimal? RealpropertyC5R311 { get; set; }
        public decimal? RealpropertyC6R311 { get; set; }
        public decimal? RealpropertyC7R311 { get; set; }
        public decimal? RealpropertyC4R312 { get; set; }
        public decimal? RealpropertyC5R312 { get; set; }
        public decimal? RealpropertyC6R312 { get; set; }
        public decimal? RealpropertyC7R312 { get; set; }
        public decimal? RealpropertyC4R320 { get; set; }
        public decimal? RealpropertyC5R320 { get; set; }
        public decimal? RealpropertyC6R320 { get; set; }
        public decimal? RealpropertyC7R320 { get; set; }
        public decimal? RealpropertyC4R321 { get; set; }
        public decimal? RealpropertyC5R321 { get; set; }
        public decimal? RealpropertyC6R321 { get; set; }
        public decimal? RealpropertyC7R321 { get; set; }
        public decimal? RealpropertyC4R322 { get; set; }
        public decimal? RealpropertyC5R322 { get; set; }
        public decimal? RealpropertyC6R322 { get; set; }
        public decimal? RealpropertyC7R322 { get; set; }
        public decimal? RealpropertyC4R330 { get; set; }
        public decimal? RealpropertyC5R330 { get; set; }
        public decimal? RealpropertyC6R330 { get; set; }
        public decimal? RealpropertyC7R330 { get; set; }
        public decimal? RealpropertyC4R331 { get; set; }
        public decimal? RealpropertyC5R331 { get; set; }
        public decimal? RealpropertyC6R331 { get; set; }
        public decimal? RealpropertyC7R331 { get; set; }
        public decimal? RealpropertyC4R332 { get; set; }
        public decimal? RealpropertyC5R332 { get; set; }
        public decimal? RealpropertyC6R332 { get; set; }
        public decimal? RealpropertyC7R332 { get; set; }
        public decimal? RealpropertyC4R340 { get; set; }
        public decimal? RealpropertyC5R340 { get; set; }
        public decimal? RealpropertyC6R340 { get; set; }
        public decimal? RealpropertyC7R340 { get; set; }
        public decimal? RealpropertyC4R341 { get; set; }
        public decimal? RealpropertyC5R341 { get; set; }
        public decimal? RealpropertyC6R341 { get; set; }
        public decimal? RealpropertyC7R341 { get; set; }
        public decimal? RealpropertyC4R342 { get; set; }
        public decimal? RealpropertyC5R342 { get; set; }
        public decimal? RealpropertyC6R342 { get; set; }
        public decimal? RealpropertyC7R342 { get; set; }
        public decimal? RealpropertyC4R350 { get; set; }
        public decimal? RealpropertyC5R350 { get; set; }
        public decimal? RealpropertyC6R350 { get; set; }
        public decimal? RealpropertyC7R350 { get; set; }
        public decimal? RealpropertyC4R352 { get; set; }
        public decimal? RealpropertyC5R352 { get; set; }
        public decimal? RealpropertyC6R352 { get; set; }
        public decimal? RealpropertyC7R352 { get; set; }
        public decimal? RealpropertyC4R360 { get; set; }
        public decimal? RealpropertyC5R360 { get; set; }
        public decimal? RealpropertyC6R360 { get; set; }
        public decimal? RealpropertyC7R360 { get; set; }
        public decimal? RealpropertyC4R362 { get; set; }
        public decimal? RealpropertyC5R362 { get; set; }
        public decimal? RealpropertyC6R362 { get; set; }
        public decimal? RealpropertyC7R362 { get; set; }
        public decimal? RealpropertyC4R370 { get; set; }
        public decimal? RealpropertyC5R370 { get; set; }
        public decimal? RealpropertyC6R370 { get; set; }
        public decimal? RealpropertyC7R370 { get; set; }
        public decimal? RealpropertyC4R372 { get; set; }
        public decimal? RealpropertyC5R372 { get; set; }
        public decimal? RealpropertyC6R372 { get; set; }
        public decimal? RealpropertyC7R372 { get; set; }
        public decimal? RealpropertyC4R380 { get; set; }
        public decimal? RealpropertyC5R380 { get; set; }
        public decimal? RealpropertyC6R380 { get; set; }
        public decimal? RealpropertyC7R380 { get; set; }
        public decimal? RealpropertyC4R390 { get; set; }
        public decimal? RealpropertyC5R390 { get; set; }
        public decimal? RealpropertyC6R390 { get; set; }
        public decimal? RealpropertyC7R390 { get; set; }
        public decimal? RealpropertyC4R410 { get; set; }
        public decimal? RealpropertyC5R410 { get; set; }
        public decimal? RealpropertyC6R410 { get; set; }
        public decimal? RealpropertyC7R410 { get; set; }
        public decimal? RealpropertyC4R412 { get; set; }
        public decimal? RealpropertyC5R412 { get; set; }
        public decimal? RealpropertyC6R412 { get; set; }
        public decimal? RealpropertyC7R412 { get; set; }
        public decimal? RealpropertyC4R420 { get; set; }
        public decimal? RealpropertyC5R420 { get; set; }
        public decimal? RealpropertyC6R420 { get; set; }
        public decimal? RealpropertyC7R420 { get; set; }
        public decimal? RealpropertyC4R422 { get; set; }
        public decimal? RealpropertyC5R422 { get; set; }
        public decimal? RealpropertyC6R422 { get; set; }
        public decimal? RealpropertyC7R422 { get; set; }
        public decimal? RealpropertyC4R430 { get; set; }
        public decimal? RealpropertyC5R430 { get; set; }
        public decimal? RealpropertyC6R430 { get; set; }
        public decimal? RealpropertyC7R430 { get; set; }
        public decimal? RealpropertyC4R432 { get; set; }
        public decimal? RealpropertyC5R432 { get; set; }
        public decimal? RealpropertyC6R432 { get; set; }
        public decimal? RealpropertyC7R432 { get; set; }
        public decimal? InfmovaccC4R450 { get; set; }
        public decimal? InfmovaccC5R450 { get; set; }
        public decimal? InfmovaccC6R450 { get; set; }
        public decimal? InfmovaccC7R450 { get; set; }
        public decimal? InfmovaccC4R451 { get; set; }
        public decimal? InfmovaccC5R451 { get; set; }
        public decimal? InfmovaccC6R451 { get; set; }
        public decimal? InfmovaccC7R451 { get; set; }
        public decimal? InfmovaccC4R452 { get; set; }
        public decimal? InfmovaccC5R452 { get; set; }
        public decimal? InfmovaccC6R452 { get; set; }
        public decimal? InfmovaccC7R452 { get; set; }
        public decimal? InfmovaccC4R453 { get; set; }
        public decimal? InfmovaccC5R453 { get; set; }
        public decimal? InfmovaccC6R453 { get; set; }
        public decimal? InfmovaccC7R453 { get; set; }
        public decimal? InfmovaccC4R460 { get; set; }
        public decimal? InfmovaccC5R460 { get; set; }
        public decimal? InfmovaccC6R460 { get; set; }
        public decimal? InfmovaccC7R460 { get; set; }
        public decimal? InfmovaccC4R470 { get; set; }
        public decimal? InfmovaccC5R470 { get; set; }
        public decimal? InfmovaccC6R470 { get; set; }
        public decimal? InfmovaccC7R470 { get; set; }
        public decimal? InfmovaccC4R480 { get; set; }
        public decimal? InfmovaccC5R480 { get; set; }
        public decimal? InfmovaccC6R480 { get; set; }
        public decimal? InfmovaccC7R480 { get; set; }
        public decimal? InfmovaccC4R481 { get; set; }
        public decimal? InfmovaccC5R481 { get; set; }
        public decimal? InfmovaccC6R481 { get; set; }
        public decimal? InfmovaccC7R481 { get; set; }
        public decimal? InfmovaccC4R482 { get; set; }
        public decimal? InfmovaccC5R482 { get; set; }
        public decimal? InfmovaccC6R482 { get; set; }
        public decimal? InfmovaccC7R482 { get; set; }
        public decimal? InfmovaccC4R483 { get; set; }
        public decimal? InfmovaccC5R483 { get; set; }
        public decimal? InfmovaccC6R483 { get; set; }
        public decimal? InfmovaccC7R483 { get; set; }
        public decimal? InfmovaccC4R484 { get; set; }
        public decimal? InfmovaccC5R484 { get; set; }
        public decimal? InfmovaccC6R484 { get; set; }
        public decimal? InfmovaccC7R484 { get; set; }
        public decimal? InfmovaccC4R490 { get; set; }
        public decimal? InfmovaccC5R490 { get; set; }
        public decimal? InfmovaccC6R490 { get; set; }
        public decimal? InfmovaccC7R490 { get; set; }
        public decimal? InfmovaccC4R510 { get; set; }
        public decimal? InfmovaccC5R510 { get; set; }
        public decimal? InfmovaccC6R510 { get; set; }
        public decimal? InfmovaccC7R510 { get; set; }
        public decimal? InfmovaccC4R511 { get; set; }
        public decimal? InfmovaccC5R511 { get; set; }
        public decimal? InfmovaccC6R511 { get; set; }
        public decimal? InfmovaccC7R511 { get; set; }
        public decimal? InfmovaccC4R512 { get; set; }
        public decimal? InfmovaccC5R512 { get; set; }
        public decimal? InfmovaccC6R512 { get; set; }
        public decimal? InfmovaccC7R512 { get; set; }
        public decimal? InfmovaccC4R520 { get; set; }
        public decimal? InfmovaccC5R520 { get; set; }
        public decimal? InfmovaccC6R520 { get; set; }
        public decimal? InfmovaccC7R520 { get; set; }
        public decimal? InfmovaccC4R521 { get; set; }
        public decimal? InfmovaccC5R521 { get; set; }
        public decimal? InfmovaccC6R521 { get; set; }
        public decimal? InfmovaccC7R521 { get; set; }
        public decimal? InfmovaccC4R522 { get; set; }
        public decimal? InfmovaccC5R522 { get; set; }
        public decimal? InfmovaccC6R522 { get; set; }
        public decimal? InfmovaccC7R522 { get; set; }
        public decimal? InfmovaccC4R523 { get; set; }
        public decimal? InfmovaccC5R523 { get; set; }
        public decimal? InfmovaccC6R523 { get; set; }
        public decimal? InfmovaccC7R523 { get; set; }
        public decimal? InfmovaccC4R524 { get; set; }
        public decimal? InfmovaccC5R524 { get; set; }
        public decimal? InfmovaccC6R524 { get; set; }
        public decimal? InfmovaccC7R524 { get; set; }
        public decimal? InfmovaccC4R530 { get; set; }
        public decimal? InfmovaccC5R530 { get; set; }
        public decimal? InfmovaccC6R530 { get; set; }
        public decimal? InfmovaccC7R530 { get; set; }
        public decimal? InfmovaccC4R540 { get; set; }
        public decimal? InfmovaccC5R540 { get; set; }
        public decimal? InfmovaccC6R540 { get; set; }
        public decimal? InfmovaccC7R540 { get; set; }
        public decimal? InfmovaccC4R541 { get; set; }
        public decimal? InfmovaccC5R541 { get; set; }
        public decimal? InfmovaccC6R541 { get; set; }
        public decimal? InfmovaccC7R541 { get; set; }
        public decimal? InfmovaccC4R542 { get; set; }
        public decimal? InfmovaccC5R542 { get; set; }
        public decimal? InfmovaccC6R542 { get; set; }
        public decimal? InfmovaccC7R542 { get; set; }
        public decimal? InfmovaccC4R543 { get; set; }
        public decimal? InfmovaccC5R543 { get; set; }
        public decimal? InfmovaccC6R543 { get; set; }
        public decimal? InfmovaccC7R543 { get; set; }
        public decimal? InfmovaccC4R544 { get; set; }
        public decimal? InfmovaccC5R544 { get; set; }
        public decimal? InfmovaccC6R544 { get; set; }
        public decimal? InfmovaccC7R544 { get; set; }
        public decimal? InfmovaccC4R545 { get; set; }
        public decimal? InfmovaccC5R545 { get; set; }
        public decimal? InfmovaccC6R545 { get; set; }
        public decimal? InfmovaccC7R545 { get; set; }
        public decimal? InfmovaccC4R546 { get; set; }
        public decimal? InfmovaccC5R546 { get; set; }
        public decimal? InfmovaccC6R546 { get; set; }
        public decimal? InfmovaccC7R546 { get; set; }
        public decimal? InfmovaccC4R547 { get; set; }
        public decimal? InfmovaccC5R547 { get; set; }
        public decimal? InfmovaccC6R547 { get; set; }
        public decimal? InfmovaccC7R547 { get; set; }
        public decimal? InfmovaccC4R550 { get; set; }
        public decimal? InfmovaccC5R550 { get; set; }
        public decimal? InfmovaccC6R550 { get; set; }
        public decimal? InfmovaccC7R550 { get; set; }
        public decimal? InfmovaccC4R551 { get; set; }
        public decimal? InfmovaccC5R551 { get; set; }
        public decimal? InfmovaccC6R551 { get; set; }
        public decimal? InfmovaccC7R551 { get; set; }
        public decimal? InfmovaccC4R552 { get; set; }
        public decimal? InfmovaccC5R552 { get; set; }
        public decimal? InfmovaccC6R552 { get; set; }
        public decimal? InfmovaccC7R552 { get; set; }
        public decimal? InfmovaccC4R553 { get; set; }
        public decimal? InfmovaccC5R553 { get; set; }
        public decimal? InfmovaccC6R553 { get; set; }
        public decimal? InfmovaccC7R553 { get; set; }
        public decimal? InfmovaccC4R554 { get; set; }
        public decimal? InfmovaccC5R554 { get; set; }
        public decimal? InfmovaccC6R554 { get; set; }
        public decimal? InfmovaccC7R554 { get; set; }
        public decimal? InfmovaccC4R555 { get; set; }
        public decimal? InfmovaccC5R555 { get; set; }
        public decimal? InfmovaccC6R555 { get; set; }
        public decimal? InfmovaccC7R555 { get; set; }
        public decimal? InfmovaccC4R556 { get; set; }
        public decimal? InfmovaccC5R556 { get; set; }
        public decimal? InfmovaccC6R556 { get; set; }
        public decimal? InfmovaccC7R556 { get; set; }
        public decimal? InfmovaccC4R557 { get; set; }
        public decimal? InfmovaccC5R557 { get; set; }
        public decimal? InfmovaccC6R557 { get; set; }
        public decimal? InfmovaccC7R557 { get; set; }
        public decimal? InfmovaccC4R560 { get; set; }
        public decimal? InfmovaccC5R560 { get; set; }
        public decimal? InfmovaccC6R560 { get; set; }
        public decimal? InfmovaccC7R560 { get; set; }
        public decimal? InfmovaccC4R561 { get; set; }
        public decimal? InfmovaccC5R561 { get; set; }
        public decimal? InfmovaccC6R561 { get; set; }
        public decimal? InfmovaccC7R561 { get; set; }
        public decimal? InfmovaccC4R562 { get; set; }
        public decimal? InfmovaccC5R562 { get; set; }
        public decimal? InfmovaccC6R562 { get; set; }
        public decimal? InfmovaccC7R562 { get; set; }
        public decimal? InfmovaccC4R563 { get; set; }
        public decimal? InfmovaccC5R563 { get; set; }
        public decimal? InfmovaccC6R563 { get; set; }
        public decimal? InfmovaccC7R563 { get; set; }
        public decimal? InfmovaccC4R564 { get; set; }
        public decimal? InfmovaccC5R564 { get; set; }
        public decimal? InfmovaccC6R564 { get; set; }
        public decimal? InfmovaccC7R564 { get; set; }
        public decimal? InfmovaccC4R565 { get; set; }
        public decimal? InfmovaccC5R565 { get; set; }
        public decimal? InfmovaccC6R565 { get; set; }
        public decimal? InfmovaccC7R565 { get; set; }
        public decimal? InfmovaccC4R566 { get; set; }
        public decimal? InfmovaccC5R566 { get; set; }
        public decimal? InfmovaccC6R566 { get; set; }
        public decimal? InfmovaccC7R566 { get; set; }
        public decimal? InfmovaccC4R567 { get; set; }
        public decimal? InfmovaccC5R567 { get; set; }
        public decimal? InfmovaccC6R567 { get; set; }
        public decimal? InfmovaccC7R567 { get; set; }
        public decimal? InfmovaccCountertab1 { get; set; }
        public decimal? InfmovaccCountertab2 { get; set; }
        public string PenCentraccCode { get; set; }
        public string PenCentraccName { get; set; }
        public string PenCentraccOgrn { get; set; }
        public string PenCentraccInn { get; set; }
        public string PenCentraccKpp { get; set; }
        public string PenCentraccLdr { get; set; }
        public string PenCentraccExec { get; set; }
        public string PenCentraccExecm { get; set; }
        public string PenCentraccLdr1 { get; set; }
        public string PenCentraccExec1 { get; set; }
        public string PenPfnLeader { get; set; }
        public string PenPfnChiefAcc { get; set; }
        public string PenPfnLeaderOfFes { get; set; }
        public string PenPfnPostLeader { get; set; }
        public string PenPfnPostChiefAcc { get; set; }
        public string PenPfnPostLeaderOf { get; set; }
        public string PenPfnExecutor { get; set; }
        public string PenPfnPostExecutor { get; set; }
        public string PenPfnPhone { get; set; }
        public string PenPostLeaderOfFes { get; set; }
        public bool? SubDiv { get; set; }
        public string ReportBaseErOkpo1 { get; set; }
        public string Ord { get; set; }
        public string Surrogat { get; set; }

        public virtual ICollection<FsInfmovaccTab1List> FsInfmovaccTab1List { get; set; }
        public virtual ICollection<FsInfmovaccTab2List> FsInfmovaccTab2List { get; set; }
    }
}
