using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcReport0503230
    {
        public DcReport0503230()
        {
            FsInfoDebndem230List = new HashSet<FsInfoDebndem230List>();
            FsInfoFrmstr230List = new HashSet<FsInfoFrmstr230List>();
            FsInfoInsdeb230List = new HashSet<FsInfoInsdeb230List>();
            FsInfoPeriod230List = new HashSet<FsInfoPeriod230List>();
            FsInfoSpequip230List = new HashSet<FsInfoSpequip230List>();
            FsInfoTangaas230List = new HashSet<FsInfoTangaas230List>();
            FsInfoUnexrec230List = new HashSet<FsInfoUnexrec230List>();
        }

        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string HrReorgRepor { get; set; }
        public string HrReorgReporKod { get; set; }
        public string HrReorgGlavaBk { get; set; }
        public string Typebalance { get; set; }
        public string NfaC2R010 { get; set; }
        public decimal? NfaC3R010 { get; set; }
        public decimal? NfaC4R010 { get; set; }
        public decimal? NfaC5R010 { get; set; }
        public decimal? NfaC6R010 { get; set; }
        public decimal? NfaC7R010 { get; set; }
        public decimal? NfaC8R010 { get; set; }
        public string NfaC2R011 { get; set; }
        public decimal? NfaC3R011 { get; set; }
        public decimal? NfaC4R011 { get; set; }
        public decimal? NfaC5R011 { get; set; }
        public decimal? NfaC6R011 { get; set; }
        public decimal? NfaC7R011 { get; set; }
        public decimal? NfaC8R011 { get; set; }
        public string NfaC2R013 { get; set; }
        public decimal? NfaC3R013 { get; set; }
        public decimal? NfaC4R013 { get; set; }
        public decimal? NfaC5R013 { get; set; }
        public decimal? NfaC6R013 { get; set; }
        public decimal? NfaC7R013 { get; set; }
        public decimal? NfaC8R013 { get; set; }
        public string NfaC2R014 { get; set; }
        public decimal? NfaC3R014 { get; set; }
        public decimal? NfaC4R014 { get; set; }
        public decimal? NfaC5R014 { get; set; }
        public decimal? NfaC6R014 { get; set; }
        public decimal? NfaC7R014 { get; set; }
        public decimal? NfaC8R014 { get; set; }
        public string NfaC2R020 { get; set; }
        public decimal? NfaC3R020 { get; set; }
        public decimal? NfaC4R020 { get; set; }
        public decimal? NfaC5R020 { get; set; }
        public decimal? NfaC6R020 { get; set; }
        public decimal? NfaC7R020 { get; set; }
        public decimal? NfaC8R020 { get; set; }
        public string NfaC2R021 { get; set; }
        public decimal? NfaC3R021 { get; set; }
        public decimal? NfaC4R021 { get; set; }
        public decimal? NfaC5R021 { get; set; }
        public decimal? NfaC6R021 { get; set; }
        public decimal? NfaC7R021 { get; set; }
        public decimal? NfaC8R021 { get; set; }
        public string NfaC2R023 { get; set; }
        public decimal? NfaC3R023 { get; set; }
        public decimal? NfaC4R023 { get; set; }
        public decimal? NfaC5R023 { get; set; }
        public decimal? NfaC6R023 { get; set; }
        public decimal? NfaC7R023 { get; set; }
        public decimal? NfaC8R023 { get; set; }
        public string NfaC2R024 { get; set; }
        public decimal? NfaC3R024 { get; set; }
        public decimal? NfaC4R024 { get; set; }
        public decimal? NfaC5R024 { get; set; }
        public decimal? NfaC6R024 { get; set; }
        public decimal? NfaC7R024 { get; set; }
        public decimal? NfaC8R024 { get; set; }
        public string NfaC2R030 { get; set; }
        public decimal? NfaC3R030 { get; set; }
        public decimal? NfaC4R030 { get; set; }
        public decimal? NfaC5R030 { get; set; }
        public decimal? NfaC6R030 { get; set; }
        public decimal? NfaC7R030 { get; set; }
        public decimal? NfaC8R030 { get; set; }
        public string NfaC2R031 { get; set; }
        public decimal? NfaC3R031 { get; set; }
        public decimal? NfaC4R031 { get; set; }
        public decimal? NfaC5R031 { get; set; }
        public decimal? NfaC6R031 { get; set; }
        public decimal? NfaC7R031 { get; set; }
        public decimal? NfaC8R031 { get; set; }
        public string NfaC2R033 { get; set; }
        public decimal? NfaC3R033 { get; set; }
        public decimal? NfaC4R033 { get; set; }
        public decimal? NfaC5R033 { get; set; }
        public decimal? NfaC6R033 { get; set; }
        public decimal? NfaC7R033 { get; set; }
        public decimal? NfaC8R033 { get; set; }
        public string NfaC2R034 { get; set; }
        public decimal? NfaC3R034 { get; set; }
        public decimal? NfaC4R034 { get; set; }
        public decimal? NfaC5R034 { get; set; }
        public decimal? NfaC6R034 { get; set; }
        public decimal? NfaC7R034 { get; set; }
        public decimal? NfaC8R034 { get; set; }
        public string NfaC2R040 { get; set; }
        public decimal? NfaC3R040 { get; set; }
        public decimal? NfaC4R040 { get; set; }
        public decimal? NfaC5R040 { get; set; }
        public decimal? NfaC6R040 { get; set; }
        public decimal? NfaC7R040 { get; set; }
        public decimal? NfaC8R040 { get; set; }
        public string NfaC2R042 { get; set; }
        public decimal? NfaC3R042 { get; set; }
        public decimal? NfaC4R042 { get; set; }
        public decimal? NfaC5R042 { get; set; }
        public decimal? NfaC6R042 { get; set; }
        public decimal? NfaC7R042 { get; set; }
        public decimal? NfaC8R042 { get; set; }
        public string NfaC2R043 { get; set; }
        public decimal? NfaC3R043 { get; set; }
        public decimal? NfaC4R043 { get; set; }
        public decimal? NfaC5R043 { get; set; }
        public decimal? NfaC6R043 { get; set; }
        public decimal? NfaC7R043 { get; set; }
        public decimal? NfaC8R043 { get; set; }
        public string NfaC2R050 { get; set; }
        public decimal? NfaC3R050 { get; set; }
        public decimal? NfaC4R050 { get; set; }
        public decimal? NfaC5R050 { get; set; }
        public decimal? NfaC6R050 { get; set; }
        public decimal? NfaC7R050 { get; set; }
        public decimal? NfaC8R050 { get; set; }
        public string NfaC2R052 { get; set; }
        public decimal? NfaC3R052 { get; set; }
        public decimal? NfaC4R052 { get; set; }
        public decimal? NfaC5R052 { get; set; }
        public decimal? NfaC6R052 { get; set; }
        public decimal? NfaC7R052 { get; set; }
        public decimal? NfaC8R052 { get; set; }
        public string NfaC2R053 { get; set; }
        public decimal? NfaC3R053 { get; set; }
        public decimal? NfaC4R053 { get; set; }
        public decimal? NfaC5R053 { get; set; }
        public decimal? NfaC6R053 { get; set; }
        public decimal? NfaC7R053 { get; set; }
        public decimal? NfaC8R053 { get; set; }
        public string NfaC2R060 { get; set; }
        public decimal? NfaC3R060 { get; set; }
        public decimal? NfaC4R060 { get; set; }
        public decimal? NfaC5R060 { get; set; }
        public decimal? NfaC6R060 { get; set; }
        public decimal? NfaC7R060 { get; set; }
        public decimal? NfaC8R060 { get; set; }
        public string NfaC2R062 { get; set; }
        public decimal? NfaC3R062 { get; set; }
        public decimal? NfaC4R062 { get; set; }
        public decimal? NfaC5R062 { get; set; }
        public decimal? NfaC6R062 { get; set; }
        public decimal? NfaC7R062 { get; set; }
        public decimal? NfaC8R062 { get; set; }
        public string NfaC2R063 { get; set; }
        public decimal? NfaC3R063 { get; set; }
        public decimal? NfaC4R063 { get; set; }
        public decimal? NfaC5R063 { get; set; }
        public decimal? NfaC6R063 { get; set; }
        public decimal? NfaC7R063 { get; set; }
        public decimal? NfaC8R063 { get; set; }
        public string NfaC2R070 { get; set; }
        public decimal? NfaC3R070 { get; set; }
        public decimal? NfaC4R070 { get; set; }
        public decimal? NfaC5R070 { get; set; }
        public decimal? NfaC6R070 { get; set; }
        public decimal? NfaC7R070 { get; set; }
        public decimal? NfaC8R070 { get; set; }
        public string NfaC2R080 { get; set; }
        public decimal? NfaC3R080 { get; set; }
        public decimal? NfaC4R080 { get; set; }
        public decimal? NfaC5R080 { get; set; }
        public decimal? NfaC6R080 { get; set; }
        public decimal? NfaC7R080 { get; set; }
        public decimal? NfaC8R080 { get; set; }
        public string NfaC2R090 { get; set; }
        public decimal? NfaC3R090 { get; set; }
        public decimal? NfaC4R090 { get; set; }
        public decimal? NfaC5R090 { get; set; }
        public decimal? NfaC6R090 { get; set; }
        public decimal? NfaC7R090 { get; set; }
        public decimal? NfaC8R090 { get; set; }
        public string NfaC2R091 { get; set; }
        public decimal? NfaC3R091 { get; set; }
        public decimal? NfaC4R091 { get; set; }
        public decimal? NfaC5R091 { get; set; }
        public decimal? NfaC6R091 { get; set; }
        public decimal? NfaC7R091 { get; set; }
        public decimal? NfaC8R091 { get; set; }
        public string NfaC2R093 { get; set; }
        public decimal? NfaC3R093 { get; set; }
        public decimal? NfaC4R093 { get; set; }
        public decimal? NfaC5R093 { get; set; }
        public decimal? NfaC6R093 { get; set; }
        public decimal? NfaC7R093 { get; set; }
        public decimal? NfaC8R093 { get; set; }
        public string NfaC2R094 { get; set; }
        public decimal? NfaC3R094 { get; set; }
        public decimal? NfaC4R094 { get; set; }
        public decimal? NfaC5R094 { get; set; }
        public decimal? NfaC6R094 { get; set; }
        public decimal? NfaC7R094 { get; set; }
        public decimal? NfaC8R094 { get; set; }
        public string NfaC2R100 { get; set; }
        public decimal? NfaC3R100 { get; set; }
        public decimal? NfaC4R100 { get; set; }
        public decimal? NfaC5R100 { get; set; }
        public decimal? NfaC6R100 { get; set; }
        public decimal? NfaC7R100 { get; set; }
        public decimal? NfaC8R100 { get; set; }
        public string NfaC2R101 { get; set; }
        public decimal? NfaC3R101 { get; set; }
        public decimal? NfaC4R101 { get; set; }
        public decimal? NfaC5R101 { get; set; }
        public decimal? NfaC6R101 { get; set; }
        public decimal? NfaC7R101 { get; set; }
        public decimal? NfaC8R101 { get; set; }
        public string NfaC2R103 { get; set; }
        public decimal? NfaC3R103 { get; set; }
        public decimal? NfaC4R103 { get; set; }
        public decimal? NfaC5R103 { get; set; }
        public decimal? NfaC6R103 { get; set; }
        public decimal? NfaC7R103 { get; set; }
        public decimal? NfaC8R103 { get; set; }
        public string NfaC2R104 { get; set; }
        public decimal? NfaC3R104 { get; set; }
        public decimal? NfaC4R104 { get; set; }
        public decimal? NfaC5R104 { get; set; }
        public decimal? NfaC6R104 { get; set; }
        public decimal? NfaC7R104 { get; set; }
        public decimal? NfaC8R104 { get; set; }
        public string NfaC2R110 { get; set; }
        public decimal? NfaC3R110 { get; set; }
        public decimal? NfaC4R110 { get; set; }
        public decimal? NfaC5R110 { get; set; }
        public decimal? NfaC6R110 { get; set; }
        public decimal? NfaC7R110 { get; set; }
        public decimal? NfaC8R110 { get; set; }
        public string NfaC2R120 { get; set; }
        public decimal? NfaC3R120 { get; set; }
        public decimal? NfaC4R120 { get; set; }
        public decimal? NfaC5R120 { get; set; }
        public decimal? NfaC6R120 { get; set; }
        public decimal? NfaC7R120 { get; set; }
        public decimal? NfaC8R120 { get; set; }
        public string NfaC2R130 { get; set; }
        public decimal? NfaC3R130 { get; set; }
        public decimal? NfaC4R130 { get; set; }
        public decimal? NfaC5R130 { get; set; }
        public decimal? NfaC6R130 { get; set; }
        public decimal? NfaC7R130 { get; set; }
        public decimal? NfaC8R130 { get; set; }
        public string NfaC2R140 { get; set; }
        public decimal? NfaC3R140 { get; set; }
        public decimal? NfaC4R140 { get; set; }
        public decimal? NfaC5R140 { get; set; }
        public decimal? NfaC6R140 { get; set; }
        public decimal? NfaC7R140 { get; set; }
        public decimal? NfaC8R140 { get; set; }
        public string NfaC2R150 { get; set; }
        public decimal? NfaC3R150 { get; set; }
        public decimal? NfaC4R150 { get; set; }
        public decimal? NfaC5R150 { get; set; }
        public decimal? NfaC6R150 { get; set; }
        public decimal? NfaC7R150 { get; set; }
        public decimal? NfaC8R150 { get; set; }
        public string FaC2R170 { get; set; }
        public decimal? FaC3R170 { get; set; }
        public decimal? FaC4R170 { get; set; }
        public decimal? FaC5R170 { get; set; }
        public decimal? FaC6R170 { get; set; }
        public decimal? FaC7R170 { get; set; }
        public decimal? FaC8R170 { get; set; }
        public string FaC2R171 { get; set; }
        public decimal? FaC3R171 { get; set; }
        public decimal? FaC4R171 { get; set; }
        public decimal? FaC5R171 { get; set; }
        public decimal? FaC6R171 { get; set; }
        public decimal? FaC7R171 { get; set; }
        public decimal? FaC8R171 { get; set; }
        public string FaC2R172 { get; set; }
        public decimal? FaC3R172 { get; set; }
        public decimal? FaC4R172 { get; set; }
        public decimal? FaC5R172 { get; set; }
        public decimal? FaC6R172 { get; set; }
        public decimal? FaC7R172 { get; set; }
        public decimal? FaC8R172 { get; set; }
        public string FaC2R173 { get; set; }
        public decimal? FaC3R173 { get; set; }
        public decimal? FaC4R173 { get; set; }
        public decimal? FaC5R173 { get; set; }
        public decimal? FaC6R173 { get; set; }
        public decimal? FaC7R173 { get; set; }
        public decimal? FaC8R173 { get; set; }
        public string FaC2R174 { get; set; }
        public decimal? FaC3R174 { get; set; }
        public decimal? FaC4R174 { get; set; }
        public decimal? FaC5R174 { get; set; }
        public decimal? FaC6R174 { get; set; }
        public decimal? FaC7R174 { get; set; }
        public decimal? FaC8R174 { get; set; }
        public string FaC2R175 { get; set; }
        public decimal? FaC3R175 { get; set; }
        public decimal? FaC4R175 { get; set; }
        public decimal? FaC5R175 { get; set; }
        public decimal? FaC6R175 { get; set; }
        public decimal? FaC7R175 { get; set; }
        public decimal? FaC8R175 { get; set; }
        public string FaC2R176 { get; set; }
        public decimal? FaC3R176 { get; set; }
        public decimal? FaC4R176 { get; set; }
        public decimal? FaC5R176 { get; set; }
        public decimal? FaC6R176 { get; set; }
        public decimal? FaC7R176 { get; set; }
        public decimal? FaC8R176 { get; set; }
        public string FaC2R177 { get; set; }
        public decimal? FaC3R177 { get; set; }
        public decimal? FaC4R177 { get; set; }
        public decimal? FaC5R177 { get; set; }
        public decimal? FaC6R177 { get; set; }
        public decimal? FaC7R177 { get; set; }
        public decimal? FaC8R177 { get; set; }
        public string FaC2R178 { get; set; }
        public decimal? FaC3R178 { get; set; }
        public decimal? FaC4R178 { get; set; }
        public decimal? FaC5R178 { get; set; }
        public decimal? FaC6R178 { get; set; }
        public decimal? FaC7R178 { get; set; }
        public decimal? FaC8R178 { get; set; }
        public string FaC2R179 { get; set; }
        public decimal? FaC3R179 { get; set; }
        public decimal? FaC4R179 { get; set; }
        public decimal? FaC5R179 { get; set; }
        public decimal? FaC6R179 { get; set; }
        public decimal? FaC7R179 { get; set; }
        public decimal? FaC8R179 { get; set; }
        public string FaC2R210 { get; set; }
        public decimal? FaC3R210 { get; set; }
        public decimal? FaC4R210 { get; set; }
        public decimal? FaC5R210 { get; set; }
        public decimal? FaC6R210 { get; set; }
        public decimal? FaC7R210 { get; set; }
        public decimal? FaC8R210 { get; set; }
        public string FaC2R211 { get; set; }
        public decimal? FaC3R211 { get; set; }
        public decimal? FaC4R211 { get; set; }
        public decimal? FaC5R211 { get; set; }
        public decimal? FaC6R211 { get; set; }
        public decimal? FaC7R211 { get; set; }
        public decimal? FaC8R211 { get; set; }
        public string FaC2R212 { get; set; }
        public decimal? FaC3R212 { get; set; }
        public decimal? FaC4R212 { get; set; }
        public decimal? FaC5R212 { get; set; }
        public decimal? FaC6R212 { get; set; }
        public decimal? FaC7R212 { get; set; }
        public decimal? FaC8R212 { get; set; }
        public string FaC2R213 { get; set; }
        public decimal? FaC3R213 { get; set; }
        public decimal? FaC4R213 { get; set; }
        public decimal? FaC5R213 { get; set; }
        public decimal? FaC6R213 { get; set; }
        public decimal? FaC7R213 { get; set; }
        public decimal? FaC8R213 { get; set; }
        public string FaC2R230 { get; set; }
        public decimal? FaC3R230 { get; set; }
        public decimal? FaC4R230 { get; set; }
        public decimal? FaC5R230 { get; set; }
        public decimal? FaC6R230 { get; set; }
        public decimal? FaC7R230 { get; set; }
        public decimal? FaC8R230 { get; set; }
        public string FaC2R260 { get; set; }
        public decimal? FaC3R260 { get; set; }
        public decimal? FaC4R260 { get; set; }
        public decimal? FaC5R260 { get; set; }
        public decimal? FaC6R260 { get; set; }
        public decimal? FaC7R260 { get; set; }
        public decimal? FaC8R260 { get; set; }
        public string FaC2R290 { get; set; }
        public decimal? FaC3R290 { get; set; }
        public decimal? FaC4R290 { get; set; }
        public decimal? FaC5R290 { get; set; }
        public decimal? FaC6R290 { get; set; }
        public decimal? FaC7R290 { get; set; }
        public decimal? FaC8R290 { get; set; }
        public string FaC2R291 { get; set; }
        public decimal? FaC3R291 { get; set; }
        public decimal? FaC4R291 { get; set; }
        public decimal? FaC5R291 { get; set; }
        public decimal? FaC6R291 { get; set; }
        public decimal? FaC7R291 { get; set; }
        public decimal? FaC8R291 { get; set; }
        public string FaC2R292 { get; set; }
        public decimal? FaC3R292 { get; set; }
        public decimal? FaC4R292 { get; set; }
        public decimal? FaC5R292 { get; set; }
        public decimal? FaC6R292 { get; set; }
        public decimal? FaC7R292 { get; set; }
        public decimal? FaC8R292 { get; set; }
        public string FaC2R293 { get; set; }
        public decimal? FaC3R293 { get; set; }
        public decimal? FaC4R293 { get; set; }
        public decimal? FaC5R293 { get; set; }
        public decimal? FaC6R293 { get; set; }
        public decimal? FaC7R293 { get; set; }
        public decimal? FaC8R293 { get; set; }
        public string FaC2R310 { get; set; }
        public decimal? FaC3R310 { get; set; }
        public decimal? FaC4R310 { get; set; }
        public decimal? FaC5R310 { get; set; }
        public decimal? FaC6R310 { get; set; }
        public decimal? FaC7R310 { get; set; }
        public decimal? FaC8R310 { get; set; }
        public string FaC2R320 { get; set; }
        public decimal? FaC3R320 { get; set; }
        public decimal? FaC4R320 { get; set; }
        public decimal? FaC5R320 { get; set; }
        public decimal? FaC6R320 { get; set; }
        public decimal? FaC7R320 { get; set; }
        public decimal? FaC8R320 { get; set; }
        public string FaC2R330 { get; set; }
        public decimal? FaC3R330 { get; set; }
        public decimal? FaC4R330 { get; set; }
        public decimal? FaC5R330 { get; set; }
        public decimal? FaC6R330 { get; set; }
        public decimal? FaC7R330 { get; set; }
        public decimal? FaC8R330 { get; set; }
        public string FaC2R331 { get; set; }
        public decimal? FaC3R331 { get; set; }
        public decimal? FaC4R331 { get; set; }
        public decimal? FaC5R331 { get; set; }
        public decimal? FaC6R331 { get; set; }
        public decimal? FaC7R331 { get; set; }
        public decimal? FaC8R331 { get; set; }
        public string FaC2R332 { get; set; }
        public decimal? FaC3R332 { get; set; }
        public decimal? FaC4R332 { get; set; }
        public decimal? FaC5R332 { get; set; }
        public decimal? FaC6R332 { get; set; }
        public decimal? FaC7R332 { get; set; }
        public decimal? FaC8R332 { get; set; }
        public string FaC2R333 { get; set; }
        public decimal? FaC3R333 { get; set; }
        public decimal? FaC4R333 { get; set; }
        public decimal? FaC5R333 { get; set; }
        public decimal? FaC6R333 { get; set; }
        public decimal? FaC7R333 { get; set; }
        public decimal? FaC8R333 { get; set; }
        public string FaC2R370 { get; set; }
        public decimal? FaC3R370 { get; set; }
        public decimal? FaC4R370 { get; set; }
        public decimal? FaC5R370 { get; set; }
        public decimal? FaC6R370 { get; set; }
        public decimal? FaC7R370 { get; set; }
        public decimal? FaC8R370 { get; set; }
        public string FaC2R371 { get; set; }
        public decimal? FaC3R371 { get; set; }
        public decimal? FaC4R371 { get; set; }
        public decimal? FaC5R371 { get; set; }
        public decimal? FaC6R371 { get; set; }
        public decimal? FaC7R371 { get; set; }
        public decimal? FaC8R371 { get; set; }
        public string FaC2R372 { get; set; }
        public decimal? FaC3R372 { get; set; }
        public decimal? FaC4R372 { get; set; }
        public decimal? FaC5R372 { get; set; }
        public decimal? FaC6R372 { get; set; }
        public decimal? FaC7R372 { get; set; }
        public decimal? FaC8R372 { get; set; }
        public string FaC2R373 { get; set; }
        public decimal? FaC3R373 { get; set; }
        public decimal? FaC4R373 { get; set; }
        public decimal? FaC5R373 { get; set; }
        public decimal? FaC6R373 { get; set; }
        public decimal? FaC7R373 { get; set; }
        public decimal? FaC8R373 { get; set; }
        public string FaC2R400 { get; set; }
        public decimal? FaC3R400 { get; set; }
        public decimal? FaC4R400 { get; set; }
        public decimal? FaC5R400 { get; set; }
        public decimal? FaC6R400 { get; set; }
        public decimal? FaC7R400 { get; set; }
        public decimal? FaC8R400 { get; set; }
        public string FaC2R410 { get; set; }
        public decimal? FaC3R410 { get; set; }
        public decimal? FaC4R410 { get; set; }
        public decimal? FaC5R410 { get; set; }
        public decimal? FaC6R410 { get; set; }
        public decimal? FaC7R410 { get; set; }
        public decimal? FaC8R410 { get; set; }
        public string FaC2R380 { get; set; }
        public decimal? FaC3R380 { get; set; }
        public decimal? FaC4R380 { get; set; }
        public decimal? FaC5R380 { get; set; }
        public decimal? FaC6R380 { get; set; }
        public decimal? FaC7R380 { get; set; }
        public decimal? FaC8R380 { get; set; }
        public string FaC2R334 { get; set; }
        public decimal? FaC3R334 { get; set; }
        public decimal? FaC4R334 { get; set; }
        public decimal? FaC5R334 { get; set; }
        public decimal? FaC6R334 { get; set; }
        public decimal? FaC7R334 { get; set; }
        public decimal? FaC8R334 { get; set; }
        public string ClC2R470 { get; set; }
        public decimal? ClC3R470 { get; set; }
        public decimal? ClC4R470 { get; set; }
        public decimal? ClC5R470 { get; set; }
        public decimal? ClC6R470 { get; set; }
        public decimal? ClC7R470 { get; set; }
        public decimal? ClC8R470 { get; set; }
        public string ClC2R471 { get; set; }
        public decimal? ClC3R471 { get; set; }
        public decimal? ClC4R471 { get; set; }
        public decimal? ClC5R471 { get; set; }
        public decimal? ClC6R471 { get; set; }
        public decimal? ClC7R471 { get; set; }
        public decimal? ClC8R471 { get; set; }
        public string ClC2R472 { get; set; }
        public decimal? ClC3R472 { get; set; }
        public decimal? ClC4R472 { get; set; }
        public decimal? ClC5R472 { get; set; }
        public decimal? ClC6R472 { get; set; }
        public decimal? ClC7R472 { get; set; }
        public decimal? ClC8R472 { get; set; }
        public string ClC2R473 { get; set; }
        public decimal? ClC3R473 { get; set; }
        public decimal? ClC4R473 { get; set; }
        public decimal? ClC5R473 { get; set; }
        public decimal? ClC6R473 { get; set; }
        public decimal? ClC7R473 { get; set; }
        public decimal? ClC8R473 { get; set; }
        public string ClC2R474 { get; set; }
        public decimal? ClC3R474 { get; set; }
        public decimal? ClC4R474 { get; set; }
        public decimal? ClC5R474 { get; set; }
        public decimal? ClC6R474 { get; set; }
        public decimal? ClC7R474 { get; set; }
        public decimal? ClC8R474 { get; set; }
        public string ClC2R490 { get; set; }
        public decimal? ClC3R490 { get; set; }
        public decimal? ClC4R490 { get; set; }
        public decimal? ClC5R490 { get; set; }
        public decimal? ClC6R490 { get; set; }
        public decimal? ClC7R490 { get; set; }
        public decimal? ClC8R490 { get; set; }
        public string ClC2R510 { get; set; }
        public decimal? ClC3R510 { get; set; }
        public decimal? ClC4R510 { get; set; }
        public decimal? ClC5R510 { get; set; }
        public decimal? ClC6R510 { get; set; }
        public decimal? ClC7R510 { get; set; }
        public decimal? ClC8R510 { get; set; }
        public string ClC2R511 { get; set; }
        public decimal? ClC3R511 { get; set; }
        public decimal? ClC4R511 { get; set; }
        public decimal? ClC5R511 { get; set; }
        public decimal? ClC6R511 { get; set; }
        public decimal? ClC7R511 { get; set; }
        public decimal? ClC8R511 { get; set; }
        public string ClC2R512 { get; set; }
        public decimal? ClC3R512 { get; set; }
        public decimal? ClC4R512 { get; set; }
        public decimal? ClC5R512 { get; set; }
        public decimal? ClC6R512 { get; set; }
        public decimal? ClC7R512 { get; set; }
        public decimal? ClC8R512 { get; set; }
        public string ClC2R513 { get; set; }
        public decimal? ClC3R513 { get; set; }
        public decimal? ClC4R513 { get; set; }
        public decimal? ClC5R513 { get; set; }
        public decimal? ClC6R513 { get; set; }
        public decimal? ClC7R513 { get; set; }
        public decimal? ClC8R513 { get; set; }
        public string ClC2R514 { get; set; }
        public decimal? ClC3R514 { get; set; }
        public decimal? ClC4R514 { get; set; }
        public decimal? ClC5R514 { get; set; }
        public decimal? ClC6R514 { get; set; }
        public decimal? ClC7R514 { get; set; }
        public decimal? ClC8R514 { get; set; }
        public string ClC2R515 { get; set; }
        public decimal? ClC3R515 { get; set; }
        public decimal? ClC4R515 { get; set; }
        public decimal? ClC5R515 { get; set; }
        public decimal? ClC6R515 { get; set; }
        public decimal? ClC7R515 { get; set; }
        public decimal? ClC8R515 { get; set; }
        public string ClC2R516 { get; set; }
        public decimal? ClC3R516 { get; set; }
        public decimal? ClC4R516 { get; set; }
        public decimal? ClC5R516 { get; set; }
        public decimal? ClC6R516 { get; set; }
        public decimal? ClC7R516 { get; set; }
        public decimal? ClC8R516 { get; set; }
        public string ClC2R530 { get; set; }
        public decimal? ClC3R530 { get; set; }
        public decimal? ClC4R530 { get; set; }
        public decimal? ClC5R530 { get; set; }
        public decimal? ClC6R530 { get; set; }
        public decimal? ClC7R530 { get; set; }
        public decimal? ClC8R530 { get; set; }
        public string ClC2R531 { get; set; }
        public decimal? ClC3R531 { get; set; }
        public decimal? ClC4R531 { get; set; }
        public decimal? ClC5R531 { get; set; }
        public decimal? ClC6R531 { get; set; }
        public decimal? ClC7R531 { get; set; }
        public decimal? ClC8R531 { get; set; }
        public string ClC2R532 { get; set; }
        public decimal? ClC3R532 { get; set; }
        public decimal? ClC4R532 { get; set; }
        public decimal? ClC5R532 { get; set; }
        public decimal? ClC6R532 { get; set; }
        public decimal? ClC7R532 { get; set; }
        public decimal? ClC8R532 { get; set; }
        public string ClC2R533 { get; set; }
        public decimal? ClC3R533 { get; set; }
        public decimal? ClC4R533 { get; set; }
        public decimal? ClC5R533 { get; set; }
        public decimal? ClC6R533 { get; set; }
        public decimal? ClC7R533 { get; set; }
        public decimal? ClC8R533 { get; set; }
        public string ClC2R534 { get; set; }
        public decimal? ClC3R534 { get; set; }
        public decimal? ClC4R534 { get; set; }
        public decimal? ClC5R534 { get; set; }
        public decimal? ClC6R534 { get; set; }
        public decimal? ClC7R534 { get; set; }
        public decimal? ClC8R534 { get; set; }
        public string ClC2R535 { get; set; }
        public decimal? ClC3R535 { get; set; }
        public decimal? ClC4R535 { get; set; }
        public decimal? ClC5R535 { get; set; }
        public decimal? ClC6R535 { get; set; }
        public decimal? ClC7R535 { get; set; }
        public decimal? ClC8R535 { get; set; }
        public string ClC2R600 { get; set; }
        public decimal? ClC3R600 { get; set; }
        public decimal? ClC4R600 { get; set; }
        public decimal? ClC5R600 { get; set; }
        public decimal? ClC6R600 { get; set; }
        public decimal? ClC7R600 { get; set; }
        public decimal? ClC8R600 { get; set; }
        public string ClC2R570 { get; set; }
        public decimal? ClC3R570 { get; set; }
        public decimal? ClC4R570 { get; set; }
        public decimal? ClC5R570 { get; set; }
        public decimal? ClC6R570 { get; set; }
        public decimal? ClC7R570 { get; set; }
        public decimal? ClC8R570 { get; set; }
        public string ClC2R580 { get; set; }
        public decimal? ClC3R580 { get; set; }
        public decimal? ClC4R580 { get; set; }
        public decimal? ClC5R580 { get; set; }
        public decimal? ClC6R580 { get; set; }
        public decimal? ClC7R580 { get; set; }
        public decimal? ClC8R580 { get; set; }
        public string ClC2R590 { get; set; }
        public decimal? ClC3R590 { get; set; }
        public decimal? ClC4R590 { get; set; }
        public decimal? ClC5R590 { get; set; }
        public decimal? ClC6R590 { get; set; }
        public decimal? ClC7R590 { get; set; }
        public decimal? ClC8R590 { get; set; }
        public string FrC2R620 { get; set; }
        public decimal? FrC3R620 { get; set; }
        public decimal? FrC4R620 { get; set; }
        public decimal? FrC5R620 { get; set; }
        public decimal? FrC6R620 { get; set; }
        public decimal? FrC7R620 { get; set; }
        public decimal? FrC8R620 { get; set; }
        public string FrC2R621 { get; set; }
        public decimal? FrC3R621 { get; set; }
        public decimal? FrC4R621 { get; set; }
        public decimal? FrC5R621 { get; set; }
        public decimal? FrC6R621 { get; set; }
        public decimal? FrC7R621 { get; set; }
        public decimal? FrC8R621 { get; set; }
        public string FrC2R622 { get; set; }
        public decimal? FrC3R622 { get; set; }
        public decimal? FrC4R622 { get; set; }
        public decimal? FrC5R622 { get; set; }
        public decimal? FrC6R622 { get; set; }
        public decimal? FrC7R622 { get; set; }
        public decimal? FrC8R622 { get; set; }
        public string FrC2R623 { get; set; }
        public decimal? FrC3R623 { get; set; }
        public decimal? FrC4R623 { get; set; }
        public decimal? FrC5R623 { get; set; }
        public decimal? FrC6R623 { get; set; }
        public decimal? FrC7R623 { get; set; }
        public decimal? FrC8R623 { get; set; }
        public string FrC2R624 { get; set; }
        public decimal? FrC3R624 { get; set; }
        public decimal? FrC4R624 { get; set; }
        public decimal? FrC5R624 { get; set; }
        public decimal? FrC6R624 { get; set; }
        public decimal? FrC7R624 { get; set; }
        public decimal? FrC8R624 { get; set; }
        public string FrC2R625 { get; set; }
        public decimal? FrC3R625 { get; set; }
        public decimal? FrC4R625 { get; set; }
        public decimal? FrC5R625 { get; set; }
        public decimal? FrC6R625 { get; set; }
        public decimal? FrC7R625 { get; set; }
        public decimal? FrC8R625 { get; set; }
        public string FrC2R900 { get; set; }
        public decimal? FrC3R900 { get; set; }
        public decimal? FrC4R900 { get; set; }
        public decimal? FrC5R900 { get; set; }
        public decimal? FrC6R900 { get; set; }
        public decimal? FrC7R900 { get; set; }
        public decimal? FrC8R900 { get; set; }
        public string FrC2R626 { get; set; }
        public decimal? FrC3R626 { get; set; }
        public decimal? FrC4R626 { get; set; }
        public decimal? FrC5R626 { get; set; }
        public decimal? FrC6R626 { get; set; }
        public decimal? FrC7R626 { get; set; }
        public decimal? FrC8R626 { get; set; }
        public string InfoC3R010 { get; set; }
        public decimal? InfoC4R010 { get; set; }
        public decimal? InfoC5R010 { get; set; }
        public string InfoC3R011 { get; set; }
        public decimal? InfoC4R011 { get; set; }
        public decimal? InfoC5R011 { get; set; }
        public string InfoC3R012 { get; set; }
        public decimal? InfoC4R012 { get; set; }
        public decimal? InfoC5R012 { get; set; }
        public string InfoC3R015 { get; set; }
        public decimal? InfoC4R015 { get; set; }
        public decimal? InfoC5R015 { get; set; }
        public string InfoC3R020 { get; set; }
        public decimal? InfoC4R020 { get; set; }
        public decimal? InfoC5R020 { get; set; }
        public string InfoC3R030 { get; set; }
        public decimal? InfoC4R030 { get; set; }
        public decimal? InfoC5R030 { get; set; }
        public string InfoC3R040 { get; set; }
        public decimal? InfoC4R040 { get; set; }
        public decimal? InfoC5R040 { get; set; }
        public string InfoC3R050 { get; set; }
        public decimal? InfoC4R050 { get; set; }
        public decimal? InfoC5R050 { get; set; }
        public string InfoC3R051 { get; set; }
        public decimal? InfoC4R051 { get; set; }
        public decimal? InfoC5R051 { get; set; }
        public string InfoC3R054 { get; set; }
        public decimal? InfoC4R054 { get; set; }
        public decimal? InfoC5R054 { get; set; }
        public string InfoC3R060 { get; set; }
        public decimal? InfoC4R060 { get; set; }
        public decimal? InfoC5R060 { get; set; }
        public string InfoC3R070 { get; set; }
        public decimal? InfoC4R070 { get; set; }
        public decimal? InfoC5R070 { get; set; }
        public string InfoC3R071 { get; set; }
        public decimal? InfoC4R071 { get; set; }
        public decimal? InfoC5R071 { get; set; }
        public string InfoC3R072 { get; set; }
        public decimal? InfoC4R072 { get; set; }
        public decimal? InfoC5R072 { get; set; }
        public string InfoC3R080 { get; set; }
        public decimal? InfoC4R080 { get; set; }
        public decimal? InfoC5R080 { get; set; }
        public string InfoC3R090 { get; set; }
        public decimal? InfoC4R090 { get; set; }
        public decimal? InfoC5R090 { get; set; }
        public string InfoC3R100 { get; set; }
        public decimal? InfoC4R100 { get; set; }
        public decimal? InfoC5R100 { get; set; }
        public string InfoC3R101 { get; set; }
        public decimal? InfoC4R101 { get; set; }
        public decimal? InfoC5R101 { get; set; }
        public string InfoC3R102 { get; set; }
        public decimal? InfoC4R102 { get; set; }
        public decimal? InfoC5R102 { get; set; }
        public string InfoC3R103 { get; set; }
        public decimal? InfoC4R103 { get; set; }
        public decimal? InfoC5R103 { get; set; }
        public string InfoC3R104 { get; set; }
        public decimal? InfoC4R104 { get; set; }
        public decimal? InfoC5R104 { get; set; }
        public string InfoC3R105 { get; set; }
        public decimal? InfoC4R105 { get; set; }
        public decimal? InfoC5R105 { get; set; }
        public string InfoC3R110 { get; set; }
        public decimal? InfoC4R110 { get; set; }
        public decimal? InfoC5R110 { get; set; }
        public string InfoC3R111 { get; set; }
        public decimal? InfoC4R111 { get; set; }
        public decimal? InfoC5R111 { get; set; }
        public string InfoC3R112 { get; set; }
        public decimal? InfoC4R112 { get; set; }
        public decimal? InfoC5R112 { get; set; }
        public string InfoC3R120 { get; set; }
        public decimal? InfoC4R120 { get; set; }
        public decimal? InfoC5R120 { get; set; }
        public string InfoC3R130 { get; set; }
        public decimal? InfoC4R130 { get; set; }
        public decimal? InfoC5R130 { get; set; }
        public string InfoC3R140 { get; set; }
        public decimal? InfoC4R140 { get; set; }
        public decimal? InfoC5R140 { get; set; }
        public string InfoC3R150 { get; set; }
        public decimal? InfoC4R150 { get; set; }
        public decimal? InfoC5R150 { get; set; }
        public string InfoC3R160 { get; set; }
        public decimal? InfoC4R160 { get; set; }
        public decimal? InfoC5R160 { get; set; }
        public string InfoC3R170 { get; set; }
        public decimal? InfoC4R170 { get; set; }
        public decimal? InfoC5R170 { get; set; }
        public string InfoC3R171 { get; set; }
        public decimal? InfoC4R171 { get; set; }
        public decimal? InfoC5R171 { get; set; }
        public string InfoC3R172 { get; set; }
        public decimal? InfoC4R172 { get; set; }
        public decimal? InfoC5R172 { get; set; }
        public string InfoC3R173 { get; set; }
        public decimal? InfoC4R173 { get; set; }
        public decimal? InfoC5R173 { get; set; }
        public string InfoC3R180 { get; set; }
        public decimal? InfoC4R180 { get; set; }
        public decimal? InfoC5R180 { get; set; }
        public string InfoC3R181 { get; set; }
        public decimal? InfoC4R181 { get; set; }
        public decimal? InfoC5R181 { get; set; }
        public string InfoC3R182 { get; set; }
        public decimal? InfoC4R182 { get; set; }
        public decimal? InfoC5R182 { get; set; }
        public string InfoC3R190 { get; set; }
        public decimal? InfoC4R190 { get; set; }
        public decimal? InfoC5R190 { get; set; }
        public string InfoC3R200 { get; set; }
        public decimal? InfoC4R200 { get; set; }
        public decimal? InfoC5R200 { get; set; }
        public string InfoC3R210 { get; set; }
        public decimal? InfoC4R210 { get; set; }
        public decimal? InfoC5R210 { get; set; }
        public string InfoC3R220 { get; set; }
        public decimal? InfoC4R220 { get; set; }
        public decimal? InfoC5R220 { get; set; }
        public string InfoC3R221 { get; set; }
        public decimal? InfoC4R221 { get; set; }
        public decimal? InfoC5R221 { get; set; }
        public string InfoC3R224 { get; set; }
        public decimal? InfoC4R224 { get; set; }
        public decimal? InfoC5R224 { get; set; }
        public string InfoC3R230 { get; set; }
        public decimal? InfoC4R230 { get; set; }
        public decimal? InfoC5R230 { get; set; }
        public string InfoC3R240 { get; set; }
        public decimal? InfoC4R240 { get; set; }
        public decimal? InfoC5R240 { get; set; }
        public string InfoC3R241 { get; set; }
        public decimal? InfoC4R241 { get; set; }
        public decimal? InfoC5R241 { get; set; }
        public string InfoC3R242 { get; set; }
        public decimal? InfoC4R242 { get; set; }
        public decimal? InfoC5R242 { get; set; }
        public string InfoC3R244 { get; set; }
        public decimal? InfoC4R244 { get; set; }
        public decimal? InfoC5R244 { get; set; }
        public string InfoC3R246 { get; set; }
        public decimal? InfoC4R246 { get; set; }
        public decimal? InfoC5R246 { get; set; }
        public string InfoC3R250 { get; set; }
        public decimal? InfoC4R250 { get; set; }
        public decimal? InfoC5R250 { get; set; }
        public string InfoC3R251 { get; set; }
        public decimal? InfoC4R251 { get; set; }
        public decimal? InfoC5R251 { get; set; }
        public string InfoC3R252 { get; set; }
        public decimal? InfoC4R252 { get; set; }
        public decimal? InfoC5R252 { get; set; }
        public string InfoC3R254 { get; set; }
        public decimal? InfoC4R254 { get; set; }
        public decimal? InfoC5R254 { get; set; }
        public string InfoC3R256 { get; set; }
        public decimal? InfoC4R256 { get; set; }
        public decimal? InfoC5R256 { get; set; }
        public string InfoC3R260 { get; set; }
        public decimal? InfoC4R260 { get; set; }
        public decimal? InfoC5R260 { get; set; }
        public string InfoC3R261 { get; set; }
        public decimal? InfoC4R261 { get; set; }
        public decimal? InfoC5R261 { get; set; }
        public string InfoC3R262 { get; set; }
        public decimal? InfoC4R262 { get; set; }
        public decimal? InfoC5R262 { get; set; }
        public string InfoC3R264 { get; set; }
        public decimal? InfoC4R264 { get; set; }
        public decimal? InfoC5R264 { get; set; }
        public string InfoC3R266 { get; set; }
        public decimal? InfoC4R266 { get; set; }
        public decimal? InfoC5R266 { get; set; }
        public string InfoCountertangaassets { get; set; }
        public string InfoCounterfrmstrictacc { get; set; }
        public string InfoCounterinsolventdeb { get; set; }
        public string InfoCounterspecequip { get; set; }
        public string InfoCounterunexplreceip { get; set; }
        public string InfoCounterdebtnotdeman { get; set; }
        public string InfoCounterperiodicals { get; set; }
        public string InfoC3R016 { get; set; }
        public decimal? InfoC4R016 { get; set; }
        public decimal? InfoC5R016 { get; set; }
        public string InfoC3R248 { get; set; }
        public decimal? InfoC4R248 { get; set; }
        public decimal? InfoC5R248 { get; set; }
        public string InfoC3R249 { get; set; }
        public decimal? InfoC4R249 { get; set; }
        public decimal? InfoC5R249 { get; set; }
        public string InfoC3R258 { get; set; }
        public decimal? InfoC4R258 { get; set; }
        public decimal? InfoC5R258 { get; set; }
        public string InfoC3R268 { get; set; }
        public decimal? InfoC4R268 { get; set; }
        public decimal? InfoC5R268 { get; set; }
        public string InfoC3R270 { get; set; }
        public decimal? InfoC4R270 { get; set; }
        public decimal? InfoC5R270 { get; set; }
        public string InfoC3R280 { get; set; }
        public decimal? InfoC4R280 { get; set; }
        public decimal? InfoC5R280 { get; set; }
        public string InfoCs3R290 { get; set; }
        public decimal? InfoCs4R290 { get; set; }
        public decimal? InfoCs5R290 { get; set; }
        public string InfoCs3R300 { get; set; }
        public decimal? InfoCs4R300 { get; set; }
        public decimal? InfoCs5R300 { get; set; }
        public string InfoCs3R310 { get; set; }
        public decimal? InfoCs4R310 { get; set; }
        public decimal? InfoCs5R310 { get; set; }
        public string SePfnLeader { get; set; }
        public string SePfnChiefAcc { get; set; }
        public string SePfnLeaderOfFes { get; set; }
        public string SePfnPostLeader { get; set; }
        public string SePfnPostChiefAcc { get; set; }
        public string SePfnPostLeaderOf { get; set; }
        public string SePfnExecutor { get; set; }
        public string SePfnPostExecutor { get; set; }
        public string SePfnPhone { get; set; }
        public string Ord { get; set; }

        public virtual ICollection<FsInfoDebndem230List> FsInfoDebndem230List { get; set; }
        public virtual ICollection<FsInfoFrmstr230List> FsInfoFrmstr230List { get; set; }
        public virtual ICollection<FsInfoInsdeb230List> FsInfoInsdeb230List { get; set; }
        public virtual ICollection<FsInfoPeriod230List> FsInfoPeriod230List { get; set; }
        public virtual ICollection<FsInfoSpequip230List> FsInfoSpequip230List { get; set; }
        public virtual ICollection<FsInfoTangaas230List> FsInfoTangaas230List { get; set; }
        public virtual ICollection<FsInfoUnexrec230List> FsInfoUnexrec230List { get; set; }
    }
}
