using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcReport0503773
    {
        public DcReport0503773()
        {
            FsRcTab0503773aList = new HashSet<FsRcTab0503773aList>();
            FsRcTab0503773bList = new HashSet<FsRcTab0503773bList>();
            FsRcTab773aItogList = new HashSet<FsRcTab773aItogList>();
            FsRcTab773bItogList = new HashSet<FsRcTab773bItogList>();
        }

        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string HrNameseparatedivision { get; set; }
        public string HrCodeseparatedivision { get; set; }
        public string HrNamefounder { get; set; }
        public string HrCodefounder { get; set; }
        public string HrNamebodyactingfounder { get; set; }
        public string HrCodebodyactingfounder { get; set; }
        public string HrNameKvfo { get; set; }
        public string HrCodeKvfo { get; set; }
        public decimal? AssetC3R010 { get; set; }
        public decimal? AssetC4R010 { get; set; }
        public decimal? AssetC5R010 { get; set; }
        public decimal? AssetC3R011 { get; set; }
        public decimal? AssetC4R011 { get; set; }
        public decimal? AssetC5R011 { get; set; }
        public decimal? AssetC3R012 { get; set; }
        public decimal? AssetC4R012 { get; set; }
        public decimal? AssetC5R012 { get; set; }
        public decimal? AssetC3R013 { get; set; }
        public decimal? AssetC4R013 { get; set; }
        public decimal? AssetC5R013 { get; set; }
        public decimal? AssetC3R014 { get; set; }
        public decimal? AssetC4R014 { get; set; }
        public decimal? AssetC5R014 { get; set; }
        public decimal? AssetC3R020 { get; set; }
        public decimal? AssetC4R020 { get; set; }
        public decimal? AssetC5R020 { get; set; }
        public decimal? AssetC3R021 { get; set; }
        public decimal? AssetC4R021 { get; set; }
        public decimal? AssetC5R021 { get; set; }
        public decimal? AssetC3R022 { get; set; }
        public decimal? AssetC4R022 { get; set; }
        public decimal? AssetC5R022 { get; set; }
        public decimal? AssetC3R023 { get; set; }
        public decimal? AssetC4R023 { get; set; }
        public decimal? AssetC5R023 { get; set; }
        public decimal? AssetC3R024 { get; set; }
        public decimal? AssetC4R024 { get; set; }
        public decimal? AssetC5R024 { get; set; }
        public decimal? AssetC3R030 { get; set; }
        public decimal? AssetC4R030 { get; set; }
        public decimal? AssetC5R030 { get; set; }
        public decimal? AssetC3R031 { get; set; }
        public decimal? AssetC4R031 { get; set; }
        public decimal? AssetC5R031 { get; set; }
        public decimal? AssetC3R032 { get; set; }
        public decimal? AssetC4R032 { get; set; }
        public decimal? AssetC5R032 { get; set; }
        public decimal? AssetC3R033 { get; set; }
        public decimal? AssetC4R033 { get; set; }
        public decimal? AssetC5R033 { get; set; }
        public decimal? AssetC3R034 { get; set; }
        public decimal? AssetC4R034 { get; set; }
        public decimal? AssetC5R034 { get; set; }
        public decimal? AssetC3R040 { get; set; }
        public decimal? AssetC4R040 { get; set; }
        public decimal? AssetC5R040 { get; set; }
        public decimal? AssetC3R041 { get; set; }
        public decimal? AssetC4R041 { get; set; }
        public decimal? AssetC5R041 { get; set; }
        public decimal? AssetC3R042 { get; set; }
        public decimal? AssetC4R042 { get; set; }
        public decimal? AssetC5R042 { get; set; }
        public decimal? AssetC3R043 { get; set; }
        public decimal? AssetC4R043 { get; set; }
        public decimal? AssetC5R043 { get; set; }
        public decimal? AssetC3R050 { get; set; }
        public decimal? AssetC4R050 { get; set; }
        public decimal? AssetC5R050 { get; set; }
        public decimal? AssetC3R051 { get; set; }
        public decimal? AssetC4R051 { get; set; }
        public decimal? AssetC5R051 { get; set; }
        public decimal? AssetC3R052 { get; set; }
        public decimal? AssetC4R052 { get; set; }
        public decimal? AssetC5R052 { get; set; }
        public decimal? AssetC3R053 { get; set; }
        public decimal? AssetC4R053 { get; set; }
        public decimal? AssetC5R053 { get; set; }
        public decimal? AssetC3R060 { get; set; }
        public decimal? AssetC4R060 { get; set; }
        public decimal? AssetC5R060 { get; set; }
        public decimal? AssetC3R061 { get; set; }
        public decimal? AssetC4R061 { get; set; }
        public decimal? AssetC5R061 { get; set; }
        public decimal? AssetC3R062 { get; set; }
        public decimal? AssetC4R062 { get; set; }
        public decimal? AssetC5R062 { get; set; }
        public decimal? AssetC3R063 { get; set; }
        public decimal? AssetC4R063 { get; set; }
        public decimal? AssetC5R063 { get; set; }
        public decimal? AssetC3R070 { get; set; }
        public decimal? AssetC4R070 { get; set; }
        public decimal? AssetC5R070 { get; set; }
        public decimal? AssetC3R080 { get; set; }
        public decimal? AssetC4R080 { get; set; }
        public decimal? AssetC5R080 { get; set; }
        public decimal? AssetC3R081 { get; set; }
        public decimal? AssetC4R081 { get; set; }
        public decimal? AssetC5R081 { get; set; }
        public decimal? AssetC3R090 { get; set; }
        public decimal? AssetC4R090 { get; set; }
        public decimal? AssetC5R090 { get; set; }
        public decimal? AssetC3R091 { get; set; }
        public decimal? AssetC4R091 { get; set; }
        public decimal? AssetC5R091 { get; set; }
        public decimal? AssetC3R092 { get; set; }
        public decimal? AssetC4R092 { get; set; }
        public decimal? AssetC5R092 { get; set; }
        public decimal? AssetC3R093 { get; set; }
        public decimal? AssetC4R093 { get; set; }
        public decimal? AssetC5R093 { get; set; }
        public decimal? AssetC3R094 { get; set; }
        public decimal? AssetC4R094 { get; set; }
        public decimal? AssetC5R094 { get; set; }
        public decimal? AssetC3R100 { get; set; }
        public decimal? AssetC4R100 { get; set; }
        public decimal? AssetC5R100 { get; set; }
        public decimal? AssetC3R101 { get; set; }
        public decimal? AssetC4R101 { get; set; }
        public decimal? AssetC5R101 { get; set; }
        public decimal? AssetC3R102 { get; set; }
        public decimal? AssetC4R102 { get; set; }
        public decimal? AssetC5R102 { get; set; }
        public decimal? AssetC3R103 { get; set; }
        public decimal? AssetC4R103 { get; set; }
        public decimal? AssetC5R103 { get; set; }
        public decimal? AssetC3R104 { get; set; }
        public decimal? AssetC4R104 { get; set; }
        public decimal? AssetC5R104 { get; set; }
        public decimal? AssetC3R110 { get; set; }
        public decimal? AssetC4R110 { get; set; }
        public decimal? AssetC5R110 { get; set; }
        public decimal? AssetC3R120 { get; set; }
        public decimal? AssetC4R120 { get; set; }
        public decimal? AssetC5R120 { get; set; }
        public decimal? AssetC3R130 { get; set; }
        public decimal? AssetC4R130 { get; set; }
        public decimal? AssetC5R130 { get; set; }
        public decimal? AssetC3R140 { get; set; }
        public decimal? AssetC4R140 { get; set; }
        public decimal? AssetC5R140 { get; set; }
        public decimal? AssetC3R150 { get; set; }
        public decimal? AssetC4R150 { get; set; }
        public decimal? AssetC5R150 { get; set; }
        public decimal? AssetC3R170 { get; set; }
        public decimal? AssetC4R170 { get; set; }
        public decimal? AssetC5R170 { get; set; }
        public decimal? AssetC3R171 { get; set; }
        public decimal? AssetC4R171 { get; set; }
        public decimal? AssetC5R171 { get; set; }
        public decimal? AssetC3R172 { get; set; }
        public decimal? AssetC4R172 { get; set; }
        public decimal? AssetC5R172 { get; set; }
        public decimal? AssetC3R173 { get; set; }
        public decimal? AssetC4R173 { get; set; }
        public decimal? AssetC5R173 { get; set; }
        public decimal? AssetC3R174 { get; set; }
        public decimal? AssetC4R174 { get; set; }
        public decimal? AssetC5R174 { get; set; }
        public decimal? AssetC3R175 { get; set; }
        public decimal? AssetC4R175 { get; set; }
        public decimal? AssetC5R175 { get; set; }
        public decimal? AssetC3R176 { get; set; }
        public decimal? AssetC4R176 { get; set; }
        public decimal? AssetC5R176 { get; set; }
        public decimal? AssetC3R177 { get; set; }
        public decimal? AssetC4R177 { get; set; }
        public decimal? AssetC5R177 { get; set; }
        public decimal? AssetC3R178 { get; set; }
        public decimal? AssetC4R178 { get; set; }
        public decimal? AssetC5R178 { get; set; }
        public decimal? AssetC3R179 { get; set; }
        public decimal? AssetC4R179 { get; set; }
        public decimal? AssetC5R179 { get; set; }
        public decimal? AssetC3R180 { get; set; }
        public decimal? AssetC4R180 { get; set; }
        public decimal? AssetC5R180 { get; set; }
        public decimal? AssetC3R181 { get; set; }
        public decimal? AssetC4R181 { get; set; }
        public decimal? AssetC5R181 { get; set; }
        public decimal? AssetC3R182 { get; set; }
        public decimal? AssetC4R182 { get; set; }
        public decimal? AssetC5R182 { get; set; }
        public decimal? AssetC3R183 { get; set; }
        public decimal? AssetC4R183 { get; set; }
        public decimal? AssetC5R183 { get; set; }
        public decimal? AssetC3R190 { get; set; }
        public decimal? AssetC4R190 { get; set; }
        public decimal? AssetC5R190 { get; set; }
        public decimal? AssetC3R191 { get; set; }
        public decimal? AssetC4R191 { get; set; }
        public decimal? AssetC5R191 { get; set; }
        public decimal? AssetC3R192 { get; set; }
        public decimal? AssetC4R192 { get; set; }
        public decimal? AssetC5R192 { get; set; }
        public decimal? AssetC3R193 { get; set; }
        public decimal? AssetC4R193 { get; set; }
        public decimal? AssetC5R193 { get; set; }
        public decimal? AssetC3R200 { get; set; }
        public decimal? AssetC4R200 { get; set; }
        public decimal? AssetC5R200 { get; set; }
        public decimal? AssetC3R201 { get; set; }
        public decimal? AssetC4R201 { get; set; }
        public decimal? AssetC5R201 { get; set; }
        public decimal? AssetC3R202 { get; set; }
        public decimal? AssetC4R202 { get; set; }
        public decimal? AssetC5R202 { get; set; }
        public decimal? AssetC3R203 { get; set; }
        public decimal? AssetC4R203 { get; set; }
        public decimal? AssetC5R203 { get; set; }
        public decimal? AssetC3R210 { get; set; }
        public decimal? AssetC4R210 { get; set; }
        public decimal? AssetC5R210 { get; set; }
        public decimal? AssetC3R211 { get; set; }
        public decimal? AssetC4R211 { get; set; }
        public decimal? AssetC5R211 { get; set; }
        public decimal? AssetC3R212 { get; set; }
        public decimal? AssetC4R212 { get; set; }
        public decimal? AssetC5R212 { get; set; }
        public decimal? AssetC3R213 { get; set; }
        public decimal? AssetC4R213 { get; set; }
        public decimal? AssetC5R213 { get; set; }
        public decimal? AssetC3R230 { get; set; }
        public decimal? AssetC4R230 { get; set; }
        public decimal? AssetC5R230 { get; set; }
        public decimal? AssetC3R260 { get; set; }
        public decimal? AssetC4R260 { get; set; }
        public decimal? AssetC5R260 { get; set; }
        public decimal? AssetC3R290 { get; set; }
        public decimal? AssetC4R290 { get; set; }
        public decimal? AssetC5R290 { get; set; }
        public decimal? AssetC3R291 { get; set; }
        public decimal? AssetC4R291 { get; set; }
        public decimal? AssetC5R291 { get; set; }
        public decimal? AssetC3R292 { get; set; }
        public decimal? AssetC4R292 { get; set; }
        public decimal? AssetC5R292 { get; set; }
        public decimal? AssetC3R293 { get; set; }
        public decimal? AssetC4R293 { get; set; }
        public decimal? AssetC5R293 { get; set; }
        public decimal? AssetC3R310 { get; set; }
        public decimal? AssetC4R310 { get; set; }
        public decimal? AssetC5R310 { get; set; }
        public decimal? AssetC3R320 { get; set; }
        public decimal? AssetC4R320 { get; set; }
        public decimal? AssetC5R320 { get; set; }
        public decimal? AssetC3R330 { get; set; }
        public decimal? AssetC4R330 { get; set; }
        public decimal? AssetC5R330 { get; set; }
        public decimal? AssetC3R331 { get; set; }
        public decimal? AssetC4R331 { get; set; }
        public decimal? AssetC5R331 { get; set; }
        public decimal? AssetC3R333 { get; set; }
        public decimal? AssetC4R333 { get; set; }
        public decimal? AssetC5R333 { get; set; }
        public decimal? AssetC3R335 { get; set; }
        public decimal? AssetC4R335 { get; set; }
        public decimal? AssetC5R335 { get; set; }
        public decimal? AssetC3R336 { get; set; }
        public decimal? AssetC4R336 { get; set; }
        public decimal? AssetC5R336 { get; set; }
        public decimal? AssetC3R337 { get; set; }
        public decimal? AssetC4R337 { get; set; }
        public decimal? AssetC5R337 { get; set; }
        public decimal? AssetC3R338 { get; set; }
        public decimal? AssetC4R338 { get; set; }
        public decimal? AssetC5R338 { get; set; }
        public decimal? AssetC3R370 { get; set; }
        public decimal? AssetC4R370 { get; set; }
        public decimal? AssetC5R370 { get; set; }
        public decimal? AssetC3R371 { get; set; }
        public decimal? AssetC4R371 { get; set; }
        public decimal? AssetC5R371 { get; set; }
        public decimal? AssetC3R372 { get; set; }
        public decimal? AssetC4R372 { get; set; }
        public decimal? AssetC5R372 { get; set; }
        public decimal? AssetC3R373 { get; set; }
        public decimal? AssetC4R373 { get; set; }
        public decimal? AssetC5R373 { get; set; }
        public decimal? AssetC3R400 { get; set; }
        public decimal? AssetC4R400 { get; set; }
        public decimal? AssetC5R400 { get; set; }
        public decimal? AssetC3R410 { get; set; }
        public decimal? AssetC4R410 { get; set; }
        public decimal? AssetC5R410 { get; set; }
        public decimal? LiabilityC3R470 { get; set; }
        public decimal? LiabilityC4R470 { get; set; }
        public decimal? LiabilityC5R470 { get; set; }
        public decimal? LiabilityC3R471 { get; set; }
        public decimal? LiabilityC4R471 { get; set; }
        public decimal? LiabilityC5R471 { get; set; }
        public decimal? LiabilityC3R472 { get; set; }
        public decimal? LiabilityC4R472 { get; set; }
        public decimal? LiabilityC5R472 { get; set; }
        public decimal? LiabilityC3R474 { get; set; }
        public decimal? LiabilityC4R474 { get; set; }
        public decimal? LiabilityC5R474 { get; set; }
        public decimal? LiabilityC3R490 { get; set; }
        public decimal? LiabilityC4R490 { get; set; }
        public decimal? LiabilityC5R490 { get; set; }
        public decimal? LiabilityC3R510 { get; set; }
        public decimal? LiabilityC4R510 { get; set; }
        public decimal? LiabilityC5R510 { get; set; }
        public decimal? LiabilityC3R511 { get; set; }
        public decimal? LiabilityC4R511 { get; set; }
        public decimal? LiabilityC5R511 { get; set; }
        public decimal? LiabilityC3R512 { get; set; }
        public decimal? LiabilityC4R512 { get; set; }
        public decimal? LiabilityC5R512 { get; set; }
        public decimal? LiabilityC3R513 { get; set; }
        public decimal? LiabilityC4R513 { get; set; }
        public decimal? LiabilityC5R513 { get; set; }
        public decimal? LiabilityC3R514 { get; set; }
        public decimal? LiabilityC4R514 { get; set; }
        public decimal? LiabilityC5R514 { get; set; }
        public decimal? LiabilityC3R515 { get; set; }
        public decimal? LiabilityC4R515 { get; set; }
        public decimal? LiabilityC5R515 { get; set; }
        public decimal? LiabilityC3R516 { get; set; }
        public decimal? LiabilityC4R516 { get; set; }
        public decimal? LiabilityC5R516 { get; set; }
        public decimal? LiabilityC3R530 { get; set; }
        public decimal? LiabilityC4R530 { get; set; }
        public decimal? LiabilityC5R530 { get; set; }
        public decimal? LiabilityC3R531 { get; set; }
        public decimal? LiabilityC4R531 { get; set; }
        public decimal? LiabilityC5R531 { get; set; }
        public decimal? LiabilityC3R532 { get; set; }
        public decimal? LiabilityC4R532 { get; set; }
        public decimal? LiabilityC5R532 { get; set; }
        public decimal? LiabilityC3R533 { get; set; }
        public decimal? LiabilityC4R533 { get; set; }
        public decimal? LiabilityC5R533 { get; set; }
        public decimal? LiabilityC3R534 { get; set; }
        public decimal? LiabilityC4R534 { get; set; }
        public decimal? LiabilityC5R534 { get; set; }
        public decimal? LiabilityC3R536 { get; set; }
        public decimal? LiabilityC4R536 { get; set; }
        public decimal? LiabilityC5R536 { get; set; }
        public decimal? LiabilityC3R600 { get; set; }
        public decimal? LiabilityC4R600 { get; set; }
        public decimal? LiabilityC5R600 { get; set; }
        public decimal? LiabilityC3R620 { get; set; }
        public decimal? LiabilityC4R620 { get; set; }
        public decimal? LiabilityC5R620 { get; set; }
        public decimal? LiabilityC3R623 { get; set; }
        public decimal? LiabilityC4R623 { get; set; }
        public decimal? LiabilityC5R623 { get; set; }
        public decimal? LiabilityC3R6231 { get; set; }
        public decimal? LiabilityC4R6231 { get; set; }
        public decimal? LiabilityC5R6231 { get; set; }
        public decimal? LiabilityC3R624 { get; set; }
        public decimal? LiabilityC4R624 { get; set; }
        public decimal? LiabilityC5R624 { get; set; }
        public decimal? LiabilityC3R625 { get; set; }
        public decimal? LiabilityC4R625 { get; set; }
        public decimal? LiabilityC5R625 { get; set; }
        public decimal? LiabilityC3R900 { get; set; }
        public decimal? LiabilityC4R900 { get; set; }
        public decimal? LiabilityC5R900 { get; set; }
        public decimal? RcC2R2 { get; set; }
        public decimal? RcC2R3 { get; set; }
        public string CaCode { get; set; }
        public string CaName { get; set; }
        public string CaOgrn { get; set; }
        public string CaInn { get; set; }
        public string CaKpp { get; set; }
        public string CaCaLeader { get; set; }
        public string CaCaExecutor { get; set; }
        public string CaPostCaLeader { get; set; }
        public string CaPostCaExecutor { get; set; }
        public string CaCaExecutorMail { get; set; }
        public string SeLeader { get; set; }
        public string SeChiefAcc { get; set; }
        public string SeLeaderOfFes { get; set; }
        public string SePostLeader { get; set; }
        public string SePostChiefAcc { get; set; }
        public string SePostLeaderOf { get; set; }
        public string SeExecutor { get; set; }
        public string SePostExecutor { get; set; }
        public string SePhone { get; set; }
        public string SysNamtip { get; set; }
        public string SysOrd { get; set; }
        public string Subotch { get; set; }

        public virtual ICollection<FsRcTab0503773aList> FsRcTab0503773aList { get; set; }
        public virtual ICollection<FsRcTab0503773bList> FsRcTab0503773bList { get; set; }
        public virtual ICollection<FsRcTab773aItogList> FsRcTab773aItogList { get; set; }
        public virtual ICollection<FsRcTab773bItogList> FsRcTab773bItogList { get; set; }
    }
}
