using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class DcTestArpReport0503074
    {
        public DcTestArpReport0503074()
        {
            FsHrTtList = new HashSet<FsHrTtList>();
        }

        public decimal Docid { get; set; }
        public decimal? Version { get; set; }
        public string HrBtCodeOfBudget { get; set; }
        public string HrBtNameOfBudget { get; set; }
        public string HrBtCodeOfType { get; set; }
        public string HrSubotch { get; set; }
        public string HrNamtip { get; set; }
        public string HrOktmo { get; set; }
        public string HrTypeterritorial { get; set; }
        public decimal? InfexpsbC4R010 { get; set; }
        public decimal? InfexpsbC6R010 { get; set; }
        public decimal? InfexpsbC8R010 { get; set; }
        public decimal? InfexpsbC10R010 { get; set; }
        public decimal? InfexpsbC4R011 { get; set; }
        public decimal? InfexpsbC6R011 { get; set; }
        public decimal? InfexpsbC8R011 { get; set; }
        public decimal? InfexpsbC10R011 { get; set; }
        public decimal? InfexpsbC4R012 { get; set; }
        public decimal? InfexpsbC6R012 { get; set; }
        public decimal? InfexpsbC8R012 { get; set; }
        public decimal? InfexpsbC10R012 { get; set; }
        public decimal? InfexpsbC4R013 { get; set; }
        public decimal? InfexpsbC6R013 { get; set; }
        public decimal? InfexpsbC8R013 { get; set; }
        public decimal? InfexpsbC10R013 { get; set; }
        public decimal? InfexpsbC4R020 { get; set; }
        public decimal? InfexpsbC6R020 { get; set; }
        public decimal? InfexpsbC8R020 { get; set; }
        public decimal? InfexpsbC10R020 { get; set; }
        public decimal? InfexpsbC4R021 { get; set; }
        public decimal? InfexpsbC6R021 { get; set; }
        public decimal? InfexpsbC8R021 { get; set; }
        public decimal? InfexpsbC10R021 { get; set; }
        public decimal? InfexpsbC4R022 { get; set; }
        public decimal? InfexpsbC6R022 { get; set; }
        public decimal? InfexpsbC8R022 { get; set; }
        public decimal? InfexpsbC10R022 { get; set; }
        public decimal? InfexpsbC4R023 { get; set; }
        public decimal? InfexpsbC6R023 { get; set; }
        public decimal? InfexpsbC8R023 { get; set; }
        public decimal? InfexpsbC10R023 { get; set; }
        public decimal? InfexpsbC4R024 { get; set; }
        public decimal? InfexpsbC6R024 { get; set; }
        public decimal? InfexpsbC8R024 { get; set; }
        public decimal? InfexpsbC10R024 { get; set; }
        public decimal? InfexpsbC4R025 { get; set; }
        public decimal? InfexpsbC6R025 { get; set; }
        public decimal? InfexpsbC8R025 { get; set; }
        public decimal? InfexpsbC10R025 { get; set; }
        public decimal? InfexpsbC4R030 { get; set; }
        public decimal? InfexpsbC6R030 { get; set; }
        public decimal? InfexpsbC8R030 { get; set; }
        public decimal? InfexpsbC10R030 { get; set; }
        public decimal? InfexpsbC4R031 { get; set; }
        public decimal? InfexpsbC6R031 { get; set; }
        public decimal? InfexpsbC8R031 { get; set; }
        public decimal? InfexpsbC10R031 { get; set; }
        public decimal? InfexpsbC4R032 { get; set; }
        public decimal? InfexpsbC6R032 { get; set; }
        public decimal? InfexpsbC8R032 { get; set; }
        public decimal? InfexpsbC10R032 { get; set; }
        public decimal? InfexpsbC4R033 { get; set; }
        public decimal? InfexpsbC6R033 { get; set; }
        public decimal? InfexpsbC8R033 { get; set; }
        public decimal? InfexpsbC10R033 { get; set; }
        public decimal? InfexpsbC4R040 { get; set; }
        public decimal? InfexpsbC6R040 { get; set; }
        public decimal? InfexpsbC8R040 { get; set; }
        public decimal? InfexpsbC10R040 { get; set; }
        public decimal? InfexpsbC4R041 { get; set; }
        public decimal? InfexpsbC6R041 { get; set; }
        public decimal? InfexpsbC8R041 { get; set; }
        public decimal? InfexpsbC10R041 { get; set; }
        public decimal? InfexpsbC4R042 { get; set; }
        public decimal? InfexpsbC6R042 { get; set; }
        public decimal? InfexpsbC8R042 { get; set; }
        public decimal? InfexpsbC10R042 { get; set; }
        public decimal? InfexpsbC4R043 { get; set; }
        public decimal? InfexpsbC6R043 { get; set; }
        public decimal? InfexpsbC8R043 { get; set; }
        public decimal? InfexpsbC10R043 { get; set; }
        public decimal? InfexpsbC4R050 { get; set; }
        public decimal? InfexpsbC6R050 { get; set; }
        public decimal? InfexpsbC8R050 { get; set; }
        public decimal? InfexpsbC10R050 { get; set; }
        public decimal? InfexpsbC4R060 { get; set; }
        public decimal? InfexpsbC6R060 { get; set; }
        public decimal? InfexpsbC8R060 { get; set; }
        public decimal? InfexpsbC10R060 { get; set; }
        public decimal? InfexpsbC3R070 { get; set; }
        public decimal? InfexpsbC4R070 { get; set; }
        public decimal? InfexpsbC5R070 { get; set; }
        public decimal? InfexpsbC6R070 { get; set; }
        public decimal? InfexpsbC7R070 { get; set; }
        public decimal? InfexpsbC8R070 { get; set; }
        public decimal? InfexpsbC9R070 { get; set; }
        public decimal? InfexpsbC10R070 { get; set; }
        public decimal? InfexpsbC3R080 { get; set; }
        public decimal? InfexpsbC4R080 { get; set; }
        public decimal? InfexpsbC5R080 { get; set; }
        public decimal? InfexpsbC6R080 { get; set; }
        public decimal? InfexpsbC7R080 { get; set; }
        public decimal? InfexpsbC8R080 { get; set; }
        public decimal? InfexpsbC9R080 { get; set; }
        public decimal? InfexpsbC10R080 { get; set; }
        public decimal? InfexpsbC4R081 { get; set; }
        public decimal? InfexpsbC6R081 { get; set; }
        public decimal? InfexpsbC8R081 { get; set; }
        public decimal? InfexpsbC10R081 { get; set; }
        public decimal? InfexpsbC4R082 { get; set; }
        public decimal? InfexpsbC6R082 { get; set; }
        public decimal? InfexpsbC8R082 { get; set; }
        public decimal? InfexpsbC10R082 { get; set; }
        public decimal? InfexpsbC4R083 { get; set; }
        public decimal? InfexpsbC6R083 { get; set; }
        public decimal? InfexpsbC8R083 { get; set; }
        public decimal? InfexpsbC10R083 { get; set; }
        public decimal? InfexpsbC4R084 { get; set; }
        public decimal? InfexpsbC6R084 { get; set; }
        public decimal? InfexpsbC8R084 { get; set; }
        public decimal? InfexpsbC10R084 { get; set; }
        public decimal? InfexpsbC3R090 { get; set; }
        public decimal? InfexpsbC4R090 { get; set; }
        public decimal? InfexpsbC5R090 { get; set; }
        public decimal? InfexpsbC6R090 { get; set; }
        public decimal? InfexpsbC7R090 { get; set; }
        public decimal? InfexpsbC8R090 { get; set; }
        public decimal? InfexpsbC9R090 { get; set; }
        public decimal? InfexpsbC10R090 { get; set; }
        public decimal? InfexpsbC4R091 { get; set; }
        public decimal? InfexpsbC6R091 { get; set; }
        public decimal? InfexpsbC8R091 { get; set; }
        public decimal? InfexpsbC10R091 { get; set; }
        public decimal? InfexpsbC4R092 { get; set; }
        public decimal? InfexpsbC6R092 { get; set; }
        public decimal? InfexpsbC8R092 { get; set; }
        public decimal? InfexpsbC10R092 { get; set; }
        public decimal? InfexpsbC4R093 { get; set; }
        public decimal? InfexpsbC6R093 { get; set; }
        public decimal? InfexpsbC8R093 { get; set; }
        public decimal? InfexpsbC10R093 { get; set; }
        public decimal? InfexpsbC4R094 { get; set; }
        public decimal? InfexpsbC6R094 { get; set; }
        public decimal? InfexpsbC8R094 { get; set; }
        public decimal? InfexpsbC10R094 { get; set; }
        public decimal? InfexpsbC4R095 { get; set; }
        public decimal? InfexpsbC6R095 { get; set; }
        public decimal? InfexpsbC8R095 { get; set; }
        public decimal? InfexpsbC10R095 { get; set; }
        public decimal? InfexpsbC3R100 { get; set; }
        public decimal? InfexpsbC4R100 { get; set; }
        public decimal? InfexpsbC5R100 { get; set; }
        public decimal? InfexpsbC6R100 { get; set; }
        public decimal? InfexpsbC7R100 { get; set; }
        public decimal? InfexpsbC8R100 { get; set; }
        public decimal? InfexpsbC9R100 { get; set; }
        public decimal? InfexpsbC10R100 { get; set; }
        public decimal? InfexpsbC3R101 { get; set; }
        public decimal? InfexpsbC4R101 { get; set; }
        public decimal? InfexpsbC5R101 { get; set; }
        public decimal? InfexpsbC6R101 { get; set; }
        public decimal? InfexpsbC7R101 { get; set; }
        public decimal? InfexpsbC8R101 { get; set; }
        public decimal? InfexpsbC9R101 { get; set; }
        public decimal? InfexpsbC10R101 { get; set; }
        public decimal? InfexpsbC3R102 { get; set; }
        public decimal? InfexpsbC4R102 { get; set; }
        public decimal? InfexpsbC5R102 { get; set; }
        public decimal? InfexpsbC6R102 { get; set; }
        public decimal? InfexpsbC7R102 { get; set; }
        public decimal? InfexpsbC8R102 { get; set; }
        public decimal? InfexpsbC9R102 { get; set; }
        public decimal? InfexpsbC10R102 { get; set; }
        public decimal? InfpostnumgovemC3R200 { get; set; }
        public decimal? InfpostnumgovemC4R200 { get; set; }
        public decimal? InfpostnumgovemC5R200 { get; set; }
        public decimal? InfpostnumgovemC6R200 { get; set; }
        public decimal? InfpostnumgovemC7R200 { get; set; }
        public decimal? InfpostnumgovemC8R200 { get; set; }
        public decimal? InfpostnumgovemC9R200 { get; set; }
        public decimal? InfpostnumgovemC10R200 { get; set; }
        public decimal? InfpostnumgovemC11R200 { get; set; }
        public decimal? InfpostnumgovemC12R200 { get; set; }
        public decimal? InfpostnumgovemC13R200 { get; set; }
        public decimal? InfpostnumgovemC14R200 { get; set; }
        public decimal? InfpostnumgovemC3R210 { get; set; }
        public decimal? InfpostnumgovemC4R210 { get; set; }
        public decimal? InfpostnumgovemC5R210 { get; set; }
        public decimal? InfpostnumgovemC6R210 { get; set; }
        public decimal? InfpostnumgovemC7R210 { get; set; }
        public decimal? InfpostnumgovemC8R210 { get; set; }
        public decimal? InfpostnumgovemC9R210 { get; set; }
        public decimal? InfpostnumgovemC10R210 { get; set; }
        public decimal? InfpostnumgovemC11R210 { get; set; }
        public decimal? InfpostnumgovemC12R210 { get; set; }
        public decimal? InfpostnumgovemC13R210 { get; set; }
        public decimal? InfpostnumgovemC14R210 { get; set; }
        public decimal? InfpostnumgovemC3R220 { get; set; }
        public decimal? InfpostnumgovemC4R220 { get; set; }
        public decimal? InfpostnumgovemC5R220 { get; set; }
        public decimal? InfpostnumgovemC6R220 { get; set; }
        public decimal? InfpostnumgovemC7R220 { get; set; }
        public decimal? InfpostnumgovemC8R220 { get; set; }
        public decimal? InfpostnumgovemC9R220 { get; set; }
        public decimal? InfpostnumgovemC10R220 { get; set; }
        public decimal? InfpostnumgovemC11R220 { get; set; }
        public decimal? InfpostnumgovemC12R220 { get; set; }
        public decimal? InfpostnumgovemC13R220 { get; set; }
        public decimal? InfpostnumgovemC14R220 { get; set; }
        public decimal? InfpostnumgovemC3R230 { get; set; }
        public decimal? InfpostnumgovemC4R230 { get; set; }
        public decimal? InfpostnumgovemC5R230 { get; set; }
        public decimal? InfpostnumgovemC6R230 { get; set; }
        public decimal? InfpostnumgovemC7R230 { get; set; }
        public decimal? InfpostnumgovemC8R230 { get; set; }
        public decimal? InfpostnumgovemC9R230 { get; set; }
        public decimal? InfpostnumgovemC10R230 { get; set; }
        public decimal? InfpostnumgovemC11R230 { get; set; }
        public decimal? InfpostnumgovemC12R230 { get; set; }
        public decimal? InfpostnumgovemC13R230 { get; set; }
        public decimal? InfpostnumgovemC14R230 { get; set; }
        public decimal? InfpostnumgovemC3R240 { get; set; }
        public decimal? InfpostnumgovemC4R240 { get; set; }
        public decimal? InfpostnumgovemC5R240 { get; set; }
        public decimal? InfpostnumgovemC6R240 { get; set; }
        public decimal? InfpostnumgovemC7R240 { get; set; }
        public decimal? InfpostnumgovemC8R240 { get; set; }
        public decimal? InfpostnumgovemC9R240 { get; set; }
        public decimal? InfpostnumgovemC10R240 { get; set; }
        public decimal? InfpostnumgovemC11R240 { get; set; }
        public decimal? InfpostnumgovemC12R240 { get; set; }
        public decimal? InfpostnumgovemC13R240 { get; set; }
        public decimal? InfpostnumgovemC14R240 { get; set; }
        public decimal? InfpostnumgovemC3R241 { get; set; }
        public decimal? InfpostnumgovemC4R241 { get; set; }
        public decimal? InfpostnumgovemC5R241 { get; set; }
        public decimal? InfpostnumgovemC6R241 { get; set; }
        public decimal? InfpostnumgovemC7R241 { get; set; }
        public decimal? InfpostnumgovemC8R241 { get; set; }
        public decimal? InfpostnumgovemC9R241 { get; set; }
        public decimal? InfpostnumgovemC10R241 { get; set; }
        public decimal? InfpostnumgovemC11R241 { get; set; }
        public decimal? InfpostnumgovemC12R241 { get; set; }
        public decimal? InfpostnumgovemC13R241 { get; set; }
        public decimal? InfpostnumgovemC14R241 { get; set; }
        public decimal? InfpostnumgovemC3R242 { get; set; }
        public decimal? InfpostnumgovemC4R242 { get; set; }
        public decimal? InfpostnumgovemC5R242 { get; set; }
        public decimal? InfpostnumgovemC6R242 { get; set; }
        public decimal? InfpostnumgovemC7R242 { get; set; }
        public decimal? InfpostnumgovemC8R242 { get; set; }
        public decimal? InfpostnumgovemC9R242 { get; set; }
        public decimal? InfpostnumgovemC10R242 { get; set; }
        public decimal? InfpostnumgovemC11R242 { get; set; }
        public decimal? InfpostnumgovemC12R242 { get; set; }
        public decimal? InfpostnumgovemC13R242 { get; set; }
        public decimal? InfpostnumgovemC14R242 { get; set; }
        public decimal? InfpostnumgovemC3R243 { get; set; }
        public decimal? InfpostnumgovemC4R243 { get; set; }
        public decimal? InfpostnumgovemC5R243 { get; set; }
        public decimal? InfpostnumgovemC6R243 { get; set; }
        public decimal? InfpostnumgovemC7R243 { get; set; }
        public decimal? InfpostnumgovemC8R243 { get; set; }
        public decimal? InfpostnumgovemC9R243 { get; set; }
        public decimal? InfpostnumgovemC10R243 { get; set; }
        public decimal? InfpostnumgovemC11R243 { get; set; }
        public decimal? InfpostnumgovemC12R243 { get; set; }
        public decimal? InfpostnumgovemC13R243 { get; set; }
        public decimal? InfpostnumgovemC14R243 { get; set; }
        public decimal? InfpostnumgovemC3R250 { get; set; }
        public decimal? InfpostnumgovemC4R250 { get; set; }
        public decimal? InfpostnumgovemC5R250 { get; set; }
        public decimal? InfpostnumgovemC6R250 { get; set; }
        public decimal? InfpostnumgovemC7R250 { get; set; }
        public decimal? InfpostnumgovemC8R250 { get; set; }
        public decimal? InfpostnumgovemC9R250 { get; set; }
        public decimal? InfpostnumgovemC10R250 { get; set; }
        public decimal? InfpostnumgovemC11R250 { get; set; }
        public decimal? InfpostnumgovemC12R250 { get; set; }
        public decimal? InfpostnumgovemC13R250 { get; set; }
        public decimal? InfpostnumgovemC14R250 { get; set; }
        public decimal? InfpostnumgovemC3R251 { get; set; }
        public decimal? InfpostnumgovemC4R251 { get; set; }
        public decimal? InfpostnumgovemC5R251 { get; set; }
        public decimal? InfpostnumgovemC6R251 { get; set; }
        public decimal? InfpostnumgovemC7R251 { get; set; }
        public decimal? InfpostnumgovemC8R251 { get; set; }
        public decimal? InfpostnumgovemC9R251 { get; set; }
        public decimal? InfpostnumgovemC10R251 { get; set; }
        public decimal? InfpostnumgovemC11R251 { get; set; }
        public decimal? InfpostnumgovemC12R251 { get; set; }
        public decimal? InfpostnumgovemC13R251 { get; set; }
        public decimal? InfpostnumgovemC14R251 { get; set; }
        public decimal? InfpostnumgovemC3R252 { get; set; }
        public decimal? InfpostnumgovemC4R252 { get; set; }
        public decimal? InfpostnumgovemC5R252 { get; set; }
        public decimal? InfpostnumgovemC6R252 { get; set; }
        public decimal? InfpostnumgovemC7R252 { get; set; }
        public decimal? InfpostnumgovemC8R252 { get; set; }
        public decimal? InfpostnumgovemC9R252 { get; set; }
        public decimal? InfpostnumgovemC10R252 { get; set; }
        public decimal? InfpostnumgovemC11R252 { get; set; }
        public decimal? InfpostnumgovemC12R252 { get; set; }
        public decimal? InfpostnumgovemC13R252 { get; set; }
        public decimal? InfpostnumgovemC14R252 { get; set; }
        public decimal? InfpostnumgovemC3R253 { get; set; }
        public decimal? InfpostnumgovemC4R253 { get; set; }
        public decimal? InfpostnumgovemC5R253 { get; set; }
        public decimal? InfpostnumgovemC6R253 { get; set; }
        public decimal? InfpostnumgovemC7R253 { get; set; }
        public decimal? InfpostnumgovemC8R253 { get; set; }
        public decimal? InfpostnumgovemC9R253 { get; set; }
        public decimal? InfpostnumgovemC10R253 { get; set; }
        public decimal? InfpostnumgovemC11R253 { get; set; }
        public decimal? InfpostnumgovemC12R253 { get; set; }
        public decimal? InfpostnumgovemC13R253 { get; set; }
        public decimal? InfpostnumgovemC14R253 { get; set; }
        public decimal? InfpostnumgovemC3R260 { get; set; }
        public decimal? InfpostnumgovemC4R260 { get; set; }
        public decimal? InfpostnumgovemC5R260 { get; set; }
        public decimal? InfpostnumgovemC6R260 { get; set; }
        public decimal? InfpostnumgovemC7R260 { get; set; }
        public decimal? InfpostnumgovemC8R260 { get; set; }
        public decimal? InfpostnumgovemC9R260 { get; set; }
        public decimal? InfpostnumgovemC10R260 { get; set; }
        public decimal? InfpostnumgovemC11R260 { get; set; }
        public decimal? InfpostnumgovemC12R260 { get; set; }
        public decimal? InfpostnumgovemC13R260 { get; set; }
        public decimal? InfpostnumgovemC14R260 { get; set; }
        public decimal? InfpostnumgovemC3R261 { get; set; }
        public decimal? InfpostnumgovemC4R261 { get; set; }
        public decimal? InfpostnumgovemC5R261 { get; set; }
        public decimal? InfpostnumgovemC6R261 { get; set; }
        public decimal? InfpostnumgovemC7R261 { get; set; }
        public decimal? InfpostnumgovemC8R261 { get; set; }
        public decimal? InfpostnumgovemC9R261 { get; set; }
        public decimal? InfpostnumgovemC10R261 { get; set; }
        public decimal? InfpostnumgovemC11R261 { get; set; }
        public decimal? InfpostnumgovemC12R261 { get; set; }
        public decimal? InfpostnumgovemC13R261 { get; set; }
        public decimal? InfpostnumgovemC14R261 { get; set; }
        public decimal? InfpostnumgovemC3R262 { get; set; }
        public decimal? InfpostnumgovemC4R262 { get; set; }
        public decimal? InfpostnumgovemC5R262 { get; set; }
        public decimal? InfpostnumgovemC6R262 { get; set; }
        public decimal? InfpostnumgovemC7R262 { get; set; }
        public decimal? InfpostnumgovemC8R262 { get; set; }
        public decimal? InfpostnumgovemC9R262 { get; set; }
        public decimal? InfpostnumgovemC10R262 { get; set; }
        public decimal? InfpostnumgovemC11R262 { get; set; }
        public decimal? InfpostnumgovemC12R262 { get; set; }
        public decimal? InfpostnumgovemC13R262 { get; set; }
        public decimal? InfpostnumgovemC14R262 { get; set; }
        public decimal? InfpostnumgovemC3R263 { get; set; }
        public decimal? InfpostnumgovemC4R263 { get; set; }
        public decimal? InfpostnumgovemC5R263 { get; set; }
        public decimal? InfpostnumgovemC6R263 { get; set; }
        public decimal? InfpostnumgovemC7R263 { get; set; }
        public decimal? InfpostnumgovemC8R263 { get; set; }
        public decimal? InfpostnumgovemC9R263 { get; set; }
        public decimal? InfpostnumgovemC10R263 { get; set; }
        public decimal? InfpostnumgovemC11R263 { get; set; }
        public decimal? InfpostnumgovemC12R263 { get; set; }
        public decimal? InfpostnumgovemC13R263 { get; set; }
        public decimal? InfpostnumgovemC14R263 { get; set; }
        public decimal? InfpostnumgovemC3R264 { get; set; }
        public decimal? InfpostnumgovemC4R264 { get; set; }
        public decimal? InfpostnumgovemC5R264 { get; set; }
        public decimal? InfpostnumgovemC6R264 { get; set; }
        public decimal? InfpostnumgovemC7R264 { get; set; }
        public decimal? InfpostnumgovemC8R264 { get; set; }
        public decimal? InfpostnumgovemC9R264 { get; set; }
        public decimal? InfpostnumgovemC10R264 { get; set; }
        public decimal? InfpostnumgovemC11R264 { get; set; }
        public decimal? InfpostnumgovemC12R264 { get; set; }
        public decimal? InfpostnumgovemC13R264 { get; set; }
        public decimal? InfpostnumgovemC14R264 { get; set; }
        public decimal? InfpostnumgovemC3R270 { get; set; }
        public decimal? InfpostnumgovemC4R270 { get; set; }
        public decimal? InfpostnumgovemC5R270 { get; set; }
        public decimal? InfpostnumgovemC6R270 { get; set; }
        public decimal? InfpostnumgovemC7R270 { get; set; }
        public decimal? InfpostnumgovemC8R270 { get; set; }
        public decimal? InfpostnumgovemC9R270 { get; set; }
        public decimal? InfpostnumgovemC10R270 { get; set; }
        public decimal? InfpostnumgovemC11R270 { get; set; }
        public decimal? InfpostnumgovemC12R270 { get; set; }
        public decimal? InfpostnumgovemC13R270 { get; set; }
        public decimal? InfpostnumgovemC14R270 { get; set; }
        public decimal? InfpostnumgovemC3R271 { get; set; }
        public decimal? InfpostnumgovemC4R271 { get; set; }
        public decimal? InfpostnumgovemC5R271 { get; set; }
        public decimal? InfpostnumgovemC6R271 { get; set; }
        public decimal? InfpostnumgovemC7R271 { get; set; }
        public decimal? InfpostnumgovemC8R271 { get; set; }
        public decimal? InfpostnumgovemC9R271 { get; set; }
        public decimal? InfpostnumgovemC10R271 { get; set; }
        public decimal? InfpostnumgovemC11R271 { get; set; }
        public decimal? InfpostnumgovemC12R271 { get; set; }
        public decimal? InfpostnumgovemC13R271 { get; set; }
        public decimal? InfpostnumgovemC14R271 { get; set; }
        public decimal? InfpostnumgovemC3R272 { get; set; }
        public decimal? InfpostnumgovemC4R272 { get; set; }
        public decimal? InfpostnumgovemC5R272 { get; set; }
        public decimal? InfpostnumgovemC6R272 { get; set; }
        public decimal? InfpostnumgovemC7R272 { get; set; }
        public decimal? InfpostnumgovemC8R272 { get; set; }
        public decimal? InfpostnumgovemC9R272 { get; set; }
        public decimal? InfpostnumgovemC10R272 { get; set; }
        public decimal? InfpostnumgovemC11R272 { get; set; }
        public decimal? InfpostnumgovemC12R272 { get; set; }
        public decimal? InfpostnumgovemC13R272 { get; set; }
        public decimal? InfpostnumgovemC14R272 { get; set; }
        public decimal? InfpostnumgovemC3R273 { get; set; }
        public decimal? InfpostnumgovemC4R273 { get; set; }
        public decimal? InfpostnumgovemC5R273 { get; set; }
        public decimal? InfpostnumgovemC6R273 { get; set; }
        public decimal? InfpostnumgovemC7R273 { get; set; }
        public decimal? InfpostnumgovemC8R273 { get; set; }
        public decimal? InfpostnumgovemC9R273 { get; set; }
        public decimal? InfpostnumgovemC10R273 { get; set; }
        public decimal? InfpostnumgovemC11R273 { get; set; }
        public decimal? InfpostnumgovemC12R273 { get; set; }
        public decimal? InfpostnumgovemC13R273 { get; set; }
        public decimal? InfpostnumgovemC14R273 { get; set; }
        public decimal? InfpostnumgovemC3R274 { get; set; }
        public decimal? InfpostnumgovemC4R274 { get; set; }
        public decimal? InfpostnumgovemC5R274 { get; set; }
        public decimal? InfpostnumgovemC6R274 { get; set; }
        public decimal? InfpostnumgovemC7R274 { get; set; }
        public decimal? InfpostnumgovemC8R274 { get; set; }
        public decimal? InfpostnumgovemC9R274 { get; set; }
        public decimal? InfpostnumgovemC10R274 { get; set; }
        public decimal? InfpostnumgovemC11R274 { get; set; }
        public decimal? InfpostnumgovemC12R274 { get; set; }
        public decimal? InfpostnumgovemC13R274 { get; set; }
        public decimal? InfpostnumgovemC14R274 { get; set; }
        public decimal? InfpostnumgovemC3R280 { get; set; }
        public decimal? InfpostnumgovemC4R280 { get; set; }
        public decimal? InfpostnumgovemC5R280 { get; set; }
        public decimal? InfpostnumgovemC6R280 { get; set; }
        public decimal? InfpostnumgovemC7R280 { get; set; }
        public decimal? InfpostnumgovemC8R280 { get; set; }
        public decimal? InfpostnumgovemC9R280 { get; set; }
        public decimal? InfpostnumgovemC10R280 { get; set; }
        public decimal? InfpostnumgovemC11R280 { get; set; }
        public decimal? InfpostnumgovemC12R280 { get; set; }
        public decimal? InfpostnumgovemC13R280 { get; set; }
        public decimal? InfpostnumgovemC14R280 { get; set; }
        public decimal? InfpostnumgovemC3R290 { get; set; }
        public decimal? InfpostnumgovemC4R290 { get; set; }
        public decimal? InfpostnumgovemC5R290 { get; set; }
        public decimal? InfpostnumgovemC6R290 { get; set; }
        public decimal? InfpostnumgovemC7R290 { get; set; }
        public decimal? InfpostnumgovemC8R290 { get; set; }
        public decimal? InfpostnumgovemC9R290 { get; set; }
        public decimal? InfpostnumgovemC10R290 { get; set; }
        public decimal? InfpostnumgovemC11R290 { get; set; }
        public decimal? InfpostnumgovemC12R290 { get; set; }
        public decimal? InfpostnumgovemC13R290 { get; set; }
        public decimal? InfpostnumgovemC14R290 { get; set; }
        public decimal? InfpostnumgovemC3R300 { get; set; }
        public decimal? InfpostnumgovemC4R300 { get; set; }
        public decimal? InfpostnumgovemC5R300 { get; set; }
        public decimal? InfpostnumgovemC6R300 { get; set; }
        public decimal? InfpostnumgovemC7R300 { get; set; }
        public decimal? InfpostnumgovemC8R300 { get; set; }
        public decimal? InfpostnumgovemC9R300 { get; set; }
        public decimal? InfpostnumgovemC10R300 { get; set; }
        public decimal? InfpostnumgovemC11R300 { get; set; }
        public decimal? InfpostnumgovemC12R300 { get; set; }
        public decimal? InfpostnumgovemC13R300 { get; set; }
        public decimal? InfpostnumgovemC14R300 { get; set; }
        public decimal? InfpostnumgovemC3R310 { get; set; }
        public decimal? InfpostnumgovemC4R310 { get; set; }
        public decimal? InfpostnumgovemC5R310 { get; set; }
        public decimal? InfpostnumgovemC6R310 { get; set; }
        public decimal? InfpostnumgovemC7R310 { get; set; }
        public decimal? InfpostnumgovemC8R310 { get; set; }
        public decimal? InfpostnumgovemC9R310 { get; set; }
        public decimal? InfpostnumgovemC10R310 { get; set; }
        public decimal? InfpostnumgovemC11R310 { get; set; }
        public decimal? InfpostnumgovemC12R310 { get; set; }
        public decimal? InfpostnumgovemC13R310 { get; set; }
        public decimal? InfpostnumgovemC14R310 { get; set; }
        public decimal? InfpostnumgovemC3R311 { get; set; }
        public decimal? InfpostnumgovemC4R311 { get; set; }
        public decimal? InfpostnumgovemC5R311 { get; set; }
        public decimal? InfpostnumgovemC6R311 { get; set; }
        public decimal? InfpostnumgovemC7R311 { get; set; }
        public decimal? InfpostnumgovemC8R311 { get; set; }
        public decimal? InfpostnumgovemC9R311 { get; set; }
        public decimal? InfpostnumgovemC10R311 { get; set; }
        public decimal? InfpostnumgovemC11R311 { get; set; }
        public decimal? InfpostnumgovemC12R311 { get; set; }
        public decimal? InfpostnumgovemC13R311 { get; set; }
        public decimal? InfpostnumgovemC14R311 { get; set; }
        public decimal? InfpostnumgovemC3R312 { get; set; }
        public decimal? InfpostnumgovemC4R312 { get; set; }
        public decimal? InfpostnumgovemC5R312 { get; set; }
        public decimal? InfpostnumgovemC6R312 { get; set; }
        public decimal? InfpostnumgovemC7R312 { get; set; }
        public decimal? InfpostnumgovemC8R312 { get; set; }
        public decimal? InfpostnumgovemC9R312 { get; set; }
        public decimal? InfpostnumgovemC10R312 { get; set; }
        public decimal? InfpostnumgovemC11R312 { get; set; }
        public decimal? InfpostnumgovemC12R312 { get; set; }
        public decimal? InfpostnumgovemC13R312 { get; set; }
        public decimal? InfpostnumgovemC14R312 { get; set; }
        public decimal? InfnumrC3R320 { get; set; }
        public decimal? InfnumrC4R320 { get; set; }
        public decimal? InfnumrC5R320 { get; set; }
        public decimal? InfnumrC6R320 { get; set; }
        public decimal? InfnumrC3R321 { get; set; }
        public decimal? InfnumrC4R321 { get; set; }
        public decimal? InfnumrC5R321 { get; set; }
        public decimal? InfnumrC6R321 { get; set; }
        public decimal? InfnumrC3R322 { get; set; }
        public decimal? InfnumrC4R322 { get; set; }
        public decimal? InfnumrC5R322 { get; set; }
        public decimal? InfnumrC6R322 { get; set; }
        public decimal? InfnumrC3R400 { get; set; }
        public decimal? InfnumrC4R400 { get; set; }
        public decimal? InfnumrC5R400 { get; set; }
        public decimal? InfnumrC6R400 { get; set; }
        public decimal? InfnumrC3R410 { get; set; }
        public decimal? InfnumrC4R410 { get; set; }
        public decimal? InfnumrC5R410 { get; set; }
        public decimal? InfnumrC6R410 { get; set; }
        public decimal? InfnumrC3R411 { get; set; }
        public decimal? InfnumrC4R411 { get; set; }
        public decimal? InfnumrC5R411 { get; set; }
        public decimal? InfnumrC6R411 { get; set; }
        public decimal? InfnumrC3R412 { get; set; }
        public decimal? InfnumrC4R412 { get; set; }
        public decimal? InfnumrC5R412 { get; set; }
        public decimal? InfnumrC6R412 { get; set; }
        public decimal? InfnumrC3R413 { get; set; }
        public decimal? InfnumrC4R413 { get; set; }
        public decimal? InfnumrC5R413 { get; set; }
        public decimal? InfnumrC6R413 { get; set; }
        public decimal? InfnumrC3R420 { get; set; }
        public decimal? InfnumrC4R420 { get; set; }
        public decimal? InfnumrC5R420 { get; set; }
        public decimal? InfnumrC6R420 { get; set; }
        public decimal? InfnumrC3R421 { get; set; }
        public decimal? InfnumrC4R421 { get; set; }
        public decimal? InfnumrC5R421 { get; set; }
        public decimal? InfnumrC6R421 { get; set; }
        public decimal? InfnumrC3R422 { get; set; }
        public decimal? InfnumrC4R422 { get; set; }
        public decimal? InfnumrC5R422 { get; set; }
        public decimal? InfnumrC6R422 { get; set; }
        public decimal? InfnumrC3R423 { get; set; }
        public decimal? InfnumrC4R423 { get; set; }
        public decimal? InfnumrC5R423 { get; set; }
        public decimal? InfnumrC6R423 { get; set; }
        public decimal? InfnumrC3R430 { get; set; }
        public decimal? InfnumrC4R430 { get; set; }
        public decimal? InfnumrC5R430 { get; set; }
        public decimal? InfnumrC6R430 { get; set; }
        public decimal? InfnumrC3R431 { get; set; }
        public decimal? InfnumrC4R431 { get; set; }
        public decimal? InfnumrC5R431 { get; set; }
        public decimal? InfnumrC6R431 { get; set; }
        public decimal? InfnumrC3R432 { get; set; }
        public decimal? InfnumrC4R432 { get; set; }
        public decimal? InfnumrC5R432 { get; set; }
        public decimal? InfnumrC6R432 { get; set; }
        public decimal? InfnumrC3R433 { get; set; }
        public decimal? InfnumrC4R433 { get; set; }
        public decimal? InfnumrC5R433 { get; set; }
        public decimal? InfnumrC6R433 { get; set; }
        public decimal? InfnumrC3R434 { get; set; }
        public decimal? InfnumrC4R434 { get; set; }
        public decimal? InfnumrC5R434 { get; set; }
        public decimal? InfnumrC6R434 { get; set; }
        public decimal? InfnumrC3R440 { get; set; }
        public decimal? InfnumrC4R440 { get; set; }
        public decimal? InfnumrC5R440 { get; set; }
        public decimal? InfnumrC6R440 { get; set; }
        public decimal? InfnumrC3R441 { get; set; }
        public decimal? InfnumrC4R441 { get; set; }
        public decimal? InfnumrC5R441 { get; set; }
        public decimal? InfnumrC6R441 { get; set; }
        public decimal? InfnumrC3R442 { get; set; }
        public decimal? InfnumrC4R442 { get; set; }
        public decimal? InfnumrC5R442 { get; set; }
        public decimal? InfnumrC6R442 { get; set; }
        public decimal? InfnumrC3R443 { get; set; }
        public decimal? InfnumrC4R443 { get; set; }
        public decimal? InfnumrC5R443 { get; set; }
        public decimal? InfnumrC6R443 { get; set; }
        public decimal? InfnumrC3R444 { get; set; }
        public decimal? InfnumrC4R444 { get; set; }
        public decimal? InfnumrC5R444 { get; set; }
        public decimal? InfnumrC6R444 { get; set; }
        public decimal? InfnumcarC3R450 { get; set; }
        public decimal? InfnumcarC4R450 { get; set; }
        public decimal? InfnumcarC5R450 { get; set; }
        public decimal? InfnumcarC6R450 { get; set; }
        public decimal? InfnumcarC7R450 { get; set; }
        public decimal? InfnumcarC8R450 { get; set; }
        public decimal? InfnumcarC9R450 { get; set; }
        public decimal? InfnumcarC10R450 { get; set; }
        public decimal? InfnumcarC3R460 { get; set; }
        public decimal? InfnumcarC4R460 { get; set; }
        public decimal? InfnumcarC5R460 { get; set; }
        public decimal? InfnumcarC6R460 { get; set; }
        public decimal? InfnumcarC7R460 { get; set; }
        public decimal? InfnumcarC8R460 { get; set; }
        public decimal? InfnumcarC9R460 { get; set; }
        public decimal? InfnumcarC10R460 { get; set; }
        public decimal? InfnumcarC3R470 { get; set; }
        public decimal? InfnumcarC4R470 { get; set; }
        public decimal? InfnumcarC5R470 { get; set; }
        public decimal? InfnumcarC6R470 { get; set; }
        public decimal? InfnumcarC7R470 { get; set; }
        public decimal? InfnumcarC8R470 { get; set; }
        public decimal? InfnumcarC9R470 { get; set; }
        public decimal? InfnumcarC10R470 { get; set; }
        public decimal? InfnumcarC3R471 { get; set; }
        public decimal? InfnumcarC4R471 { get; set; }
        public decimal? InfnumcarC5R471 { get; set; }
        public decimal? InfnumcarC6R471 { get; set; }
        public decimal? InfnumcarC7R471 { get; set; }
        public decimal? InfnumcarC8R471 { get; set; }
        public decimal? InfnumcarC9R471 { get; set; }
        public decimal? InfnumcarC10R471 { get; set; }
        public decimal? InfnumcarC3R480 { get; set; }
        public decimal? InfnumcarC4R480 { get; set; }
        public decimal? InfnumcarC5R480 { get; set; }
        public decimal? InfnumcarC6R480 { get; set; }
        public decimal? InfnumcarC7R480 { get; set; }
        public decimal? InfnumcarC8R480 { get; set; }
        public decimal? InfnumcarC9R480 { get; set; }
        public decimal? InfnumcarC10R480 { get; set; }
        public decimal? InfnumcarC3R481 { get; set; }
        public decimal? InfnumcarC4R481 { get; set; }
        public decimal? InfnumcarC5R481 { get; set; }
        public decimal? InfnumcarC6R481 { get; set; }
        public decimal? InfnumcarC7R481 { get; set; }
        public decimal? InfnumcarC8R481 { get; set; }
        public decimal? InfnumcarC9R481 { get; set; }
        public decimal? InfnumcarC10R481 { get; set; }
        public decimal? InffedbudexpC3R510 { get; set; }
        public decimal? InffedbudexpC5R510 { get; set; }
        public decimal? InffedbudexpC7R510 { get; set; }
        public decimal? InffedbudexpC8R510 { get; set; }
        public decimal? InffedbudexpC9R510 { get; set; }
        public decimal? InffedbudexpC10R510 { get; set; }
        public decimal? InffedbudexpC12R510 { get; set; }
        public decimal? InffedbudexpC14R510 { get; set; }
        public decimal? InffedbudexpC15R510 { get; set; }
        public decimal? InffedbudexpC16R510 { get; set; }
        public decimal? InffedbudexpC17R510 { get; set; }
        public decimal? InffedbudexpC19R510 { get; set; }
        public decimal? InffedbudexpC21R510 { get; set; }
        public decimal? InffedbudexpC22R510 { get; set; }
        public decimal? InffedbudexpC23R510 { get; set; }
        public decimal? InffedbudexpC3R520 { get; set; }
        public decimal? InffedbudexpC5R520 { get; set; }
        public decimal? InffedbudexpC7R520 { get; set; }
        public decimal? InffedbudexpC8R520 { get; set; }
        public decimal? InffedbudexpC9R520 { get; set; }
        public decimal? InffedbudexpC10R520 { get; set; }
        public decimal? InffedbudexpC12R520 { get; set; }
        public decimal? InffedbudexpC14R520 { get; set; }
        public decimal? InffedbudexpC15R520 { get; set; }
        public decimal? InffedbudexpC16R520 { get; set; }
        public decimal? InffedbudexpC17R520 { get; set; }
        public decimal? InffedbudexpC19R520 { get; set; }
        public decimal? InffedbudexpC21R520 { get; set; }
        public decimal? InffedbudexpC22R520 { get; set; }
        public decimal? InffedbudexpC23R520 { get; set; }
        public decimal? InffedbudexpC3R530 { get; set; }
        public decimal? InffedbudexpC5R530 { get; set; }
        public decimal? InffedbudexpC6R530 { get; set; }
        public decimal? InffedbudexpC7R530 { get; set; }
        public decimal? InffedbudexpC8R530 { get; set; }
        public decimal? InffedbudexpC9R530 { get; set; }
        public decimal? InffedbudexpC10R530 { get; set; }
        public decimal? InffedbudexpC12R530 { get; set; }
        public decimal? InffedbudexpC13R530 { get; set; }
        public decimal? InffedbudexpC14R530 { get; set; }
        public decimal? InffedbudexpC15R530 { get; set; }
        public decimal? InffedbudexpC16R530 { get; set; }
        public decimal? InffedbudexpC17R530 { get; set; }
        public decimal? InffedbudexpC19R530 { get; set; }
        public decimal? InffedbudexpC20R530 { get; set; }
        public decimal? InffedbudexpC21R530 { get; set; }
        public decimal? InffedbudexpC22R530 { get; set; }
        public decimal? InffedbudexpC23R530 { get; set; }
        public decimal? InffedbudexpC3R540 { get; set; }
        public decimal? InffedbudexpC4R540 { get; set; }
        public decimal? InffedbudexpC5R540 { get; set; }
        public decimal? InffedbudexpC7R540 { get; set; }
        public decimal? InffedbudexpC8R540 { get; set; }
        public decimal? InffedbudexpC9R540 { get; set; }
        public decimal? InffedbudexpC10R540 { get; set; }
        public decimal? InffedbudexpC11R540 { get; set; }
        public decimal? InffedbudexpC12R540 { get; set; }
        public decimal? InffedbudexpC14R540 { get; set; }
        public decimal? InffedbudexpC15R540 { get; set; }
        public decimal? InffedbudexpC16R540 { get; set; }
        public decimal? InffedbudexpC17R540 { get; set; }
        public decimal? InffedbudexpC18R540 { get; set; }
        public decimal? InffedbudexpC19R540 { get; set; }
        public decimal? InffedbudexpC21R540 { get; set; }
        public decimal? InffedbudexpC22R540 { get; set; }
        public decimal? InffedbudexpC23R540 { get; set; }
        public decimal? InffedbudexpC3R550 { get; set; }
        public decimal? InffedbudexpC4R550 { get; set; }
        public decimal? InffedbudexpC5R550 { get; set; }
        public decimal? InffedbudexpC7R550 { get; set; }
        public decimal? InffedbudexpC8R550 { get; set; }
        public decimal? InffedbudexpC9R550 { get; set; }
        public decimal? InffedbudexpC10R550 { get; set; }
        public decimal? InffedbudexpC11R550 { get; set; }
        public decimal? InffedbudexpC12R550 { get; set; }
        public decimal? InffedbudexpC14R550 { get; set; }
        public decimal? InffedbudexpC15R550 { get; set; }
        public decimal? InffedbudexpC16R550 { get; set; }
        public decimal? InffedbudexpC17R550 { get; set; }
        public decimal? InffedbudexpC18R550 { get; set; }
        public decimal? InffedbudexpC19R550 { get; set; }
        public decimal? InffedbudexpC21R550 { get; set; }
        public decimal? InffedbudexpC22R550 { get; set; }
        public decimal? InffedbudexpC23R550 { get; set; }
        public decimal? InffedbudexpC3R560 { get; set; }
        public decimal? InffedbudexpC4R560 { get; set; }
        public decimal? InffedbudexpC5R560 { get; set; }
        public decimal? InffedbudexpC6R560 { get; set; }
        public decimal? InffedbudexpC7R560 { get; set; }
        public decimal? InffedbudexpC8R560 { get; set; }
        public decimal? InffedbudexpC9R560 { get; set; }
        public decimal? InffedbudexpC10R560 { get; set; }
        public decimal? InffedbudexpC11R560 { get; set; }
        public decimal? InffedbudexpC12R560 { get; set; }
        public decimal? InffedbudexpC13R560 { get; set; }
        public decimal? InffedbudexpC14R560 { get; set; }
        public decimal? InffedbudexpC15R560 { get; set; }
        public decimal? InffedbudexpC16R560 { get; set; }
        public decimal? InffedbudexpC17R560 { get; set; }
        public decimal? InffedbudexpC18R560 { get; set; }
        public decimal? InffedbudexpC19R560 { get; set; }
        public decimal? InffedbudexpC20R560 { get; set; }
        public decimal? InffedbudexpC21R560 { get; set; }
        public decimal? InffedbudexpC22R560 { get; set; }
        public decimal? InffedbudexpC23R560 { get; set; }
        public decimal? TypeterC3R610 { get; set; }
        public decimal? TypeterC5R610 { get; set; }
        public decimal? TypeterC7R610 { get; set; }
        public decimal? TypeterC8R610 { get; set; }
        public decimal? TypeterC9R610 { get; set; }
        public decimal? TypeterC10R610 { get; set; }
        public decimal? TypeterC12R610 { get; set; }
        public decimal? TypeterC14R610 { get; set; }
        public decimal? TypeterC15R610 { get; set; }
        public decimal? TypeterC16R610 { get; set; }
        public decimal? TypeterC17R610 { get; set; }
        public decimal? TypeterC19R610 { get; set; }
        public decimal? TypeterC21R610 { get; set; }
        public decimal? TypeterC22R610 { get; set; }
        public decimal? TypeterC23R610 { get; set; }
        public decimal? TypeterC3R620 { get; set; }
        public decimal? TypeterC5R620 { get; set; }
        public decimal? TypeterC7R620 { get; set; }
        public decimal? TypeterC8R620 { get; set; }
        public decimal? TypeterC9R620 { get; set; }
        public decimal? TypeterC10R620 { get; set; }
        public decimal? TypeterC12R620 { get; set; }
        public decimal? TypeterC14R620 { get; set; }
        public decimal? TypeterC15R620 { get; set; }
        public decimal? TypeterC16R620 { get; set; }
        public decimal? TypeterC17R620 { get; set; }
        public decimal? TypeterC19R620 { get; set; }
        public decimal? TypeterC21R620 { get; set; }
        public decimal? TypeterC22R620 { get; set; }
        public decimal? TypeterC23R620 { get; set; }
        public decimal? TypeterC3R630 { get; set; }
        public decimal? TypeterC5R630 { get; set; }
        public decimal? TypeterC6R630 { get; set; }
        public decimal? TypeterC7R630 { get; set; }
        public decimal? TypeterC8R630 { get; set; }
        public decimal? TypeterC9R630 { get; set; }
        public decimal? TypeterC10R630 { get; set; }
        public decimal? TypeterC12R630 { get; set; }
        public decimal? TypeterC13R630 { get; set; }
        public decimal? TypeterC14R630 { get; set; }
        public decimal? TypeterC15R630 { get; set; }
        public decimal? TypeterC16R630 { get; set; }
        public decimal? TypeterC17R630 { get; set; }
        public decimal? TypeterC19R630 { get; set; }
        public decimal? TypeterC20R630 { get; set; }
        public decimal? TypeterC21R630 { get; set; }
        public decimal? TypeterC22R630 { get; set; }
        public decimal? TypeterC23R630 { get; set; }
        public decimal? TypeterC3R640 { get; set; }
        public decimal? TypeterC4R640 { get; set; }
        public decimal? TypeterC5R640 { get; set; }
        public decimal? TypeterC7R640 { get; set; }
        public decimal? TypeterC8R640 { get; set; }
        public decimal? TypeterC9R640 { get; set; }
        public decimal? TypeterC10R640 { get; set; }
        public decimal? TypeterC11R640 { get; set; }
        public decimal? TypeterC12R640 { get; set; }
        public decimal? TypeterC14R640 { get; set; }
        public decimal? TypeterC15R640 { get; set; }
        public decimal? TypeterC16R640 { get; set; }
        public decimal? TypeterC17R640 { get; set; }
        public decimal? TypeterC18R640 { get; set; }
        public decimal? TypeterC19R640 { get; set; }
        public decimal? TypeterC21R640 { get; set; }
        public decimal? TypeterC22R640 { get; set; }
        public decimal? TypeterC23R640 { get; set; }
        public decimal? TypeterC3R641 { get; set; }
        public decimal? TypeterC4R641 { get; set; }
        public decimal? TypeterC5R641 { get; set; }
        public decimal? TypeterC7R641 { get; set; }
        public decimal? TypeterC8R641 { get; set; }
        public decimal? TypeterC9R641 { get; set; }
        public decimal? TypeterC10R641 { get; set; }
        public decimal? TypeterC11R641 { get; set; }
        public decimal? TypeterC12R641 { get; set; }
        public decimal? TypeterC14R641 { get; set; }
        public decimal? TypeterC15R641 { get; set; }
        public decimal? TypeterC16R641 { get; set; }
        public decimal? TypeterC17R641 { get; set; }
        public decimal? TypeterC18R641 { get; set; }
        public decimal? TypeterC19R641 { get; set; }
        public decimal? TypeterC21R641 { get; set; }
        public decimal? TypeterC22R641 { get; set; }
        public decimal? TypeterC23R641 { get; set; }
        public decimal? TypeterC3R650 { get; set; }
        public decimal? TypeterC4R650 { get; set; }
        public decimal? TypeterC5R650 { get; set; }
        public decimal? TypeterC6R650 { get; set; }
        public decimal? TypeterC7R650 { get; set; }
        public decimal? TypeterC8R650 { get; set; }
        public decimal? TypeterC9R650 { get; set; }
        public decimal? TypeterC10R650 { get; set; }
        public decimal? TypeterC11R650 { get; set; }
        public decimal? TypeterC12R650 { get; set; }
        public decimal? TypeterC13R650 { get; set; }
        public decimal? TypeterC14R650 { get; set; }
        public decimal? TypeterC15R650 { get; set; }
        public decimal? TypeterC16R650 { get; set; }
        public decimal? TypeterC17R650 { get; set; }
        public decimal? TypeterC18R650 { get; set; }
        public decimal? TypeterC19R650 { get; set; }
        public decimal? TypeterC20R650 { get; set; }
        public decimal? TypeterC21R650 { get; set; }
        public decimal? TypeterC22R650 { get; set; }
        public decimal? TypeterC23R650 { get; set; }
        public decimal? TypeterC3R651 { get; set; }
        public decimal? TypeterC4R651 { get; set; }
        public decimal? TypeterC5R651 { get; set; }
        public decimal? TypeterC7R651 { get; set; }
        public decimal? TypeterC8R651 { get; set; }
        public decimal? TypeterC9R651 { get; set; }
        public decimal? TypeterC10R651 { get; set; }
        public decimal? TypeterC11R651 { get; set; }
        public decimal? TypeterC12R651 { get; set; }
        public decimal? TypeterC14R651 { get; set; }
        public decimal? TypeterC15R651 { get; set; }
        public decimal? TypeterC16R651 { get; set; }
        public decimal? TypeterC17R651 { get; set; }
        public decimal? TypeterC18R651 { get; set; }
        public decimal? TypeterC19R651 { get; set; }
        public decimal? TypeterC21R651 { get; set; }
        public decimal? TypeterC22R651 { get; set; }
        public decimal? TypeterC23R651 { get; set; }
        public decimal? TypeterC3R660 { get; set; }
        public decimal? TypeterC4R660 { get; set; }
        public decimal? TypeterC5R660 { get; set; }
        public decimal? TypeterC6R660 { get; set; }
        public decimal? TypeterC7R660 { get; set; }
        public decimal? TypeterC8R660 { get; set; }
        public decimal? TypeterC9R660 { get; set; }
        public decimal? TypeterC10R660 { get; set; }
        public decimal? TypeterC11R660 { get; set; }
        public decimal? TypeterC12R660 { get; set; }
        public decimal? TypeterC13R660 { get; set; }
        public decimal? TypeterC14R660 { get; set; }
        public decimal? TypeterC15R660 { get; set; }
        public decimal? TypeterC16R660 { get; set; }
        public decimal? TypeterC17R660 { get; set; }
        public decimal? TypeterC18R660 { get; set; }
        public decimal? TypeterC19R660 { get; set; }
        public decimal? TypeterC20R660 { get; set; }
        public decimal? TypeterC21R660 { get; set; }
        public decimal? TypeterC22R660 { get; set; }
        public decimal? TypeterC23R660 { get; set; }
        public string SigPfnLeader { get; set; }
        public string SigPfnChiefAcc { get; set; }
        public string SigPfnLeaderOfFes { get; set; }
        public string SigPfnPostLeader { get; set; }
        public string SigPfnPostChiefAcc { get; set; }
        public string SigPfnPostLeaderOf { get; set; }
        public string SigPfnExecutor { get; set; }
        public string SigPfnPostExecutor { get; set; }
        public string SigPfnPhone { get; set; }
        public string Surrogat { get; set; }
        public string Ord { get; set; }

        public virtual ICollection<FsHrTtList> FsHrTtList { get; set; }
    }
}
