using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class HArprep0503830
    {
        public HArprep0503830()
        {
            HfsInfoFrmstr830List = new HashSet<HfsInfoFrmstr830List>();
            HfsInfoInsdeb830List = new HashSet<HfsInfoInsdeb830List>();
            HfsInfoInskred830List = new HashSet<HfsInfoInskred830List>();
            HfsInfoPeriod830List = new HashSet<HfsInfoPeriod830List>();
            HfsInfoSpequip830List = new HashSet<HfsInfoSpequip830List>();
            HfsInfoTangaas830List = new HashSet<HfsInfoTangaas830List>();
        }

        public decimal Id { get; set; }
        public string HrNameseparatedivision { get; set; }
        public string HrCodeseparatedivision { get; set; }
        public string HrNamehomeorg { get; set; }
        public string HrCodehomeorg { get; set; }
        public string HrReportBaseErOkpo1 { get; set; }
        public string HrNamefounder { get; set; }
        public string HrCodefounder { get; set; }
        public string HrNamebodyactingfounder { get; set; }
        public string HrCodebodyactingfounder { get; set; }
        public string HrReorgRepor { get; set; }
        public string HrReorgReporKod { get; set; }
        public string HrReorgGlavaBk { get; set; }
        public decimal? InfoC4R010 { get; set; }
        public decimal? InfoC5R010 { get; set; }
        public decimal? InfoC6R010 { get; set; }
        public decimal? InfoC7R010 { get; set; }
        public decimal? InfoC8R010 { get; set; }
        public decimal? InfoC9R010 { get; set; }
        public decimal? InfoC10R010 { get; set; }
        public decimal? InfoC11R010 { get; set; }
        public decimal? InfoC4R011 { get; set; }
        public decimal? InfoC5R011 { get; set; }
        public decimal? InfoC6R011 { get; set; }
        public decimal? InfoC7R011 { get; set; }
        public decimal? InfoC8R011 { get; set; }
        public decimal? InfoC9R011 { get; set; }
        public decimal? InfoC10R011 { get; set; }
        public decimal? InfoC4R012 { get; set; }
        public decimal? InfoC5R012 { get; set; }
        public decimal? InfoC6R012 { get; set; }
        public decimal? InfoC7R012 { get; set; }
        public decimal? InfoC8R012 { get; set; }
        public decimal? InfoC9R012 { get; set; }
        public decimal? InfoC4R015 { get; set; }
        public decimal? InfoC5R015 { get; set; }
        public decimal? InfoC6R015 { get; set; }
        public decimal? InfoC7R015 { get; set; }
        public decimal? InfoC8R015 { get; set; }
        public decimal? InfoC9R015 { get; set; }
        public decimal? InfoC10R015 { get; set; }
        public decimal? InfoC11R015 { get; set; }
        public decimal? InfoC4R020 { get; set; }
        public decimal? InfoC5R020 { get; set; }
        public decimal? InfoC6R020 { get; set; }
        public decimal? InfoC7R020 { get; set; }
        public decimal? InfoC8R020 { get; set; }
        public decimal? InfoC9R020 { get; set; }
        public decimal? InfoC4R030 { get; set; }
        public decimal? InfoC5R030 { get; set; }
        public decimal? InfoC6R030 { get; set; }
        public decimal? InfoC7R030 { get; set; }
        public decimal? InfoC8R030 { get; set; }
        public decimal? InfoC9R030 { get; set; }
        public decimal? InfoC4R040 { get; set; }
        public decimal? InfoC5R040 { get; set; }
        public decimal? InfoC6R040 { get; set; }
        public decimal? InfoC7R040 { get; set; }
        public decimal? InfoC8R040 { get; set; }
        public decimal? InfoC9R040 { get; set; }
        public decimal? InfoC4R050 { get; set; }
        public decimal? InfoC5R050 { get; set; }
        public decimal? InfoC6R050 { get; set; }
        public decimal? InfoC7R050 { get; set; }
        public decimal? InfoC8R050 { get; set; }
        public decimal? InfoC9R050 { get; set; }
        public decimal? InfoC4R051 { get; set; }
        public decimal? InfoC5R051 { get; set; }
        public decimal? InfoC6R051 { get; set; }
        public decimal? InfoC7R051 { get; set; }
        public decimal? InfoC8R051 { get; set; }
        public decimal? InfoC9R051 { get; set; }
        public decimal? InfoC4R052 { get; set; }
        public decimal? InfoC5R052 { get; set; }
        public decimal? InfoC6R052 { get; set; }
        public decimal? InfoC7R052 { get; set; }
        public decimal? InfoC8R052 { get; set; }
        public decimal? InfoC9R052 { get; set; }
        public decimal? InfoC4R054 { get; set; }
        public decimal? InfoC5R054 { get; set; }
        public decimal? InfoC6R054 { get; set; }
        public decimal? InfoC7R054 { get; set; }
        public decimal? InfoC8R054 { get; set; }
        public decimal? InfoC9R054 { get; set; }
        public decimal? InfoC4R055 { get; set; }
        public decimal? InfoC5R055 { get; set; }
        public decimal? InfoC6R055 { get; set; }
        public decimal? InfoC7R055 { get; set; }
        public decimal? InfoC8R055 { get; set; }
        public decimal? InfoC9R055 { get; set; }
        public decimal? InfoC4R060 { get; set; }
        public decimal? InfoC5R060 { get; set; }
        public decimal? InfoC6R060 { get; set; }
        public decimal? InfoC7R060 { get; set; }
        public decimal? InfoC8R060 { get; set; }
        public decimal? InfoC9R060 { get; set; }
        public decimal? InfoC4R070 { get; set; }
        public decimal? InfoC5R070 { get; set; }
        public decimal? InfoC6R070 { get; set; }
        public decimal? InfoC7R070 { get; set; }
        public decimal? InfoC8R070 { get; set; }
        public decimal? InfoC9R070 { get; set; }
        public decimal? InfoC4R071 { get; set; }
        public decimal? InfoC5R071 { get; set; }
        public decimal? InfoC6R071 { get; set; }
        public decimal? InfoC7R071 { get; set; }
        public decimal? InfoC8R071 { get; set; }
        public decimal? InfoC9R071 { get; set; }
        public decimal? InfoC4R072 { get; set; }
        public decimal? InfoC5R072 { get; set; }
        public decimal? InfoC6R072 { get; set; }
        public decimal? InfoC7R072 { get; set; }
        public decimal? InfoC8R072 { get; set; }
        public decimal? InfoC9R072 { get; set; }
        public decimal? InfoC4R080 { get; set; }
        public decimal? InfoC5R080 { get; set; }
        public decimal? InfoC6R080 { get; set; }
        public decimal? InfoC7R080 { get; set; }
        public decimal? InfoC8R080 { get; set; }
        public decimal? InfoC9R080 { get; set; }
        public decimal? InfoC4R090 { get; set; }
        public decimal? InfoC5R090 { get; set; }
        public decimal? InfoC6R090 { get; set; }
        public decimal? InfoC7R090 { get; set; }
        public decimal? InfoC8R090 { get; set; }
        public decimal? InfoC9R090 { get; set; }
        public decimal? InfoC4R100 { get; set; }
        public decimal? InfoC5R100 { get; set; }
        public decimal? InfoC6R100 { get; set; }
        public decimal? InfoC7R100 { get; set; }
        public decimal? InfoC8R100 { get; set; }
        public decimal? InfoC9R100 { get; set; }
        public decimal? InfoC4R101 { get; set; }
        public decimal? InfoC5R101 { get; set; }
        public decimal? InfoC6R101 { get; set; }
        public decimal? InfoC7R101 { get; set; }
        public decimal? InfoC8R101 { get; set; }
        public decimal? InfoC9R101 { get; set; }
        public decimal? InfoC4R102 { get; set; }
        public decimal? InfoC5R102 { get; set; }
        public decimal? InfoC6R102 { get; set; }
        public decimal? InfoC7R102 { get; set; }
        public decimal? InfoC8R102 { get; set; }
        public decimal? InfoC9R102 { get; set; }
        public decimal? InfoC4R103 { get; set; }
        public decimal? InfoC5R103 { get; set; }
        public decimal? InfoC6R103 { get; set; }
        public decimal? InfoC7R103 { get; set; }
        public decimal? InfoC8R103 { get; set; }
        public decimal? InfoC9R103 { get; set; }
        public decimal? InfoC4R104 { get; set; }
        public decimal? InfoC5R104 { get; set; }
        public decimal? InfoC6R104 { get; set; }
        public decimal? InfoC7R104 { get; set; }
        public decimal? InfoC8R104 { get; set; }
        public decimal? InfoC9R104 { get; set; }
        public decimal? InfoC4R105 { get; set; }
        public decimal? InfoC5R105 { get; set; }
        public decimal? InfoC6R105 { get; set; }
        public decimal? InfoC7R105 { get; set; }
        public decimal? InfoC8R105 { get; set; }
        public decimal? InfoC9R105 { get; set; }
        public decimal? InfoC4R120 { get; set; }
        public decimal? InfoC5R120 { get; set; }
        public decimal? InfoC6R120 { get; set; }
        public decimal? InfoC7R120 { get; set; }
        public decimal? InfoC8R120 { get; set; }
        public decimal? InfoC9R120 { get; set; }
        public decimal? InfoC4R130 { get; set; }
        public decimal? InfoC5R130 { get; set; }
        public decimal? InfoC6R130 { get; set; }
        public decimal? InfoC7R130 { get; set; }
        public decimal? InfoC8R130 { get; set; }
        public decimal? InfoC9R130 { get; set; }
        public decimal? InfoC4R150 { get; set; }
        public decimal? InfoC5R150 { get; set; }
        public decimal? InfoC6R150 { get; set; }
        public decimal? InfoC7R150 { get; set; }
        public decimal? InfoC8R150 { get; set; }
        public decimal? InfoC9R150 { get; set; }
        public decimal? InfoC4R160 { get; set; }
        public decimal? InfoC5R160 { get; set; }
        public decimal? InfoC6R160 { get; set; }
        public decimal? InfoC7R160 { get; set; }
        public decimal? InfoC8R160 { get; set; }
        public decimal? InfoC9R160 { get; set; }
        public decimal? InfoC4R170 { get; set; }
        public decimal? InfoC5R170 { get; set; }
        public decimal? InfoC6R170 { get; set; }
        public decimal? InfoC7R170 { get; set; }
        public decimal? InfoC8R170 { get; set; }
        public decimal? InfoC9R170 { get; set; }
        public decimal? InfoC4R171 { get; set; }
        public decimal? InfoC5R171 { get; set; }
        public decimal? InfoC6R171 { get; set; }
        public decimal? InfoC7R171 { get; set; }
        public decimal? InfoC8R171 { get; set; }
        public decimal? InfoC9R171 { get; set; }
        public decimal? InfoC4R172 { get; set; }
        public decimal? InfoC5R172 { get; set; }
        public decimal? InfoC6R172 { get; set; }
        public decimal? InfoC7R172 { get; set; }
        public decimal? InfoC8R172 { get; set; }
        public decimal? InfoC9R172 { get; set; }
        public decimal? InfoC4R173 { get; set; }
        public decimal? InfoC5R173 { get; set; }
        public decimal? InfoC6R173 { get; set; }
        public decimal? InfoC7R173 { get; set; }
        public decimal? InfoC8R173 { get; set; }
        public decimal? InfoC9R173 { get; set; }
        public decimal? InfoC4R180 { get; set; }
        public decimal? InfoC5R180 { get; set; }
        public decimal? InfoC6R180 { get; set; }
        public decimal? InfoC7R180 { get; set; }
        public decimal? InfoC8R180 { get; set; }
        public decimal? InfoC9R180 { get; set; }
        public decimal? InfoC4R181 { get; set; }
        public decimal? InfoC5R181 { get; set; }
        public decimal? InfoC6R181 { get; set; }
        public decimal? InfoC7R181 { get; set; }
        public decimal? InfoC8R181 { get; set; }
        public decimal? InfoC9R181 { get; set; }
        public decimal? InfoC4R182 { get; set; }
        public decimal? InfoC5R182 { get; set; }
        public decimal? InfoC6R182 { get; set; }
        public decimal? InfoC7R182 { get; set; }
        public decimal? InfoC8R182 { get; set; }
        public decimal? InfoC9R182 { get; set; }
        public decimal? InfoC4R200 { get; set; }
        public decimal? InfoC5R200 { get; set; }
        public decimal? InfoC6R200 { get; set; }
        public decimal? InfoC7R200 { get; set; }
        public decimal? InfoC8R200 { get; set; }
        public decimal? InfoC9R200 { get; set; }
        public decimal? InfoC4R210 { get; set; }
        public decimal? InfoC5R210 { get; set; }
        public decimal? InfoC6R210 { get; set; }
        public decimal? InfoC7R210 { get; set; }
        public decimal? InfoC8R210 { get; set; }
        public decimal? InfoC9R210 { get; set; }
        public decimal? InfoC4R211 { get; set; }
        public decimal? InfoC5R211 { get; set; }
        public decimal? InfoC6R211 { get; set; }
        public decimal? InfoC7R211 { get; set; }
        public decimal? InfoC8R211 { get; set; }
        public decimal? InfoC9R211 { get; set; }
        public decimal? InfoC4R212 { get; set; }
        public decimal? InfoC5R212 { get; set; }
        public decimal? InfoC6R212 { get; set; }
        public decimal? InfoC7R212 { get; set; }
        public decimal? InfoC8R212 { get; set; }
        public decimal? InfoC9R212 { get; set; }
        public decimal? InfoC4R220 { get; set; }
        public decimal? InfoC5R220 { get; set; }
        public decimal? InfoC6R220 { get; set; }
        public decimal? InfoC7R220 { get; set; }
        public decimal? InfoC8R220 { get; set; }
        public decimal? InfoC9R220 { get; set; }
        public decimal? InfoC4R221 { get; set; }
        public decimal? InfoC5R221 { get; set; }
        public decimal? InfoC6R221 { get; set; }
        public decimal? InfoC7R221 { get; set; }
        public decimal? InfoC8R221 { get; set; }
        public decimal? InfoC9R221 { get; set; }
        public decimal? InfoC4R222 { get; set; }
        public decimal? InfoC5R222 { get; set; }
        public decimal? InfoC6R222 { get; set; }
        public decimal? InfoC7R222 { get; set; }
        public decimal? InfoC8R222 { get; set; }
        public decimal? InfoC9R222 { get; set; }
        public decimal? InfoC4R224 { get; set; }
        public decimal? InfoC5R224 { get; set; }
        public decimal? InfoC6R224 { get; set; }
        public decimal? InfoC7R224 { get; set; }
        public decimal? InfoC8R224 { get; set; }
        public decimal? InfoC9R224 { get; set; }
        public decimal? InfoC4R225 { get; set; }
        public decimal? InfoC5R225 { get; set; }
        public decimal? InfoC6R225 { get; set; }
        public decimal? InfoC7R225 { get; set; }
        public decimal? InfoC8R225 { get; set; }
        public decimal? InfoC9R225 { get; set; }
        public decimal? InfoC4R230 { get; set; }
        public decimal? InfoC5R230 { get; set; }
        public decimal? InfoC6R230 { get; set; }
        public decimal? InfoC7R230 { get; set; }
        public decimal? InfoC8R230 { get; set; }
        public decimal? InfoC9R230 { get; set; }
        public decimal? InfoC4R240 { get; set; }
        public decimal? InfoC5R240 { get; set; }
        public decimal? InfoC6R240 { get; set; }
        public decimal? InfoC7R240 { get; set; }
        public decimal? InfoC8R240 { get; set; }
        public decimal? InfoC9R240 { get; set; }
        public decimal? InfoC4R241 { get; set; }
        public decimal? InfoC5R241 { get; set; }
        public decimal? InfoC6R241 { get; set; }
        public decimal? InfoC7R241 { get; set; }
        public decimal? InfoC8R241 { get; set; }
        public decimal? InfoC9R241 { get; set; }
        public decimal? InfoC4R242 { get; set; }
        public decimal? InfoC5R242 { get; set; }
        public decimal? InfoC6R242 { get; set; }
        public decimal? InfoC7R242 { get; set; }
        public decimal? InfoC8R242 { get; set; }
        public decimal? InfoC9R242 { get; set; }
        public decimal? InfoC4R243 { get; set; }
        public decimal? InfoC5R243 { get; set; }
        public decimal? InfoC6R243 { get; set; }
        public decimal? InfoC7R243 { get; set; }
        public decimal? InfoC8R243 { get; set; }
        public decimal? InfoC9R243 { get; set; }
        public decimal? InfoC4R244 { get; set; }
        public decimal? InfoC5R244 { get; set; }
        public decimal? InfoC6R244 { get; set; }
        public decimal? InfoC7R244 { get; set; }
        public decimal? InfoC8R244 { get; set; }
        public decimal? InfoC9R244 { get; set; }
        public decimal? InfoC4R245 { get; set; }
        public decimal? InfoC5R245 { get; set; }
        public decimal? InfoC6R245 { get; set; }
        public decimal? InfoC7R245 { get; set; }
        public decimal? InfoC8R245 { get; set; }
        public decimal? InfoC9R245 { get; set; }
        public decimal? InfoC4R246 { get; set; }
        public decimal? InfoC5R246 { get; set; }
        public decimal? InfoC6R246 { get; set; }
        public decimal? InfoC7R246 { get; set; }
        public decimal? InfoC8R246 { get; set; }
        public decimal? InfoC9R246 { get; set; }
        public decimal? InfoC4R247 { get; set; }
        public decimal? InfoC5R247 { get; set; }
        public decimal? InfoC6R247 { get; set; }
        public decimal? InfoC7R247 { get; set; }
        public decimal? InfoC8R247 { get; set; }
        public decimal? InfoC9R247 { get; set; }
        public decimal? InfoC4R250 { get; set; }
        public decimal? InfoC5R250 { get; set; }
        public decimal? InfoC6R250 { get; set; }
        public decimal? InfoC7R250 { get; set; }
        public decimal? InfoC8R250 { get; set; }
        public decimal? InfoC9R250 { get; set; }
        public decimal? InfoC4R251 { get; set; }
        public decimal? InfoC5R251 { get; set; }
        public decimal? InfoC6R251 { get; set; }
        public decimal? InfoC7R251 { get; set; }
        public decimal? InfoC8R251 { get; set; }
        public decimal? InfoC9R251 { get; set; }
        public decimal? InfoC4R252 { get; set; }
        public decimal? InfoC5R252 { get; set; }
        public decimal? InfoC6R252 { get; set; }
        public decimal? InfoC7R252 { get; set; }
        public decimal? InfoC8R252 { get; set; }
        public decimal? InfoC9R252 { get; set; }
        public decimal? InfoC4R253 { get; set; }
        public decimal? InfoC5R253 { get; set; }
        public decimal? InfoC6R253 { get; set; }
        public decimal? InfoC7R253 { get; set; }
        public decimal? InfoC8R253 { get; set; }
        public decimal? InfoC9R253 { get; set; }
        public decimal? InfoC5R254 { get; set; }
        public decimal? InfoC6R254 { get; set; }
        public decimal? InfoC7R254 { get; set; }
        public decimal? InfoC8R254 { get; set; }
        public decimal? InfoC9R254 { get; set; }
        public decimal? InfoC4R255 { get; set; }
        public decimal? InfoC5R255 { get; set; }
        public decimal? InfoC6R255 { get; set; }
        public decimal? InfoC7R255 { get; set; }
        public decimal? InfoC8R255 { get; set; }
        public decimal? InfoC9R255 { get; set; }
        public decimal? InfoC4R256 { get; set; }
        public decimal? InfoC5R256 { get; set; }
        public decimal? InfoC6R256 { get; set; }
        public decimal? InfoC7R256 { get; set; }
        public decimal? InfoC8R256 { get; set; }
        public decimal? InfoC9R256 { get; set; }
        public decimal? InfoC4R257 { get; set; }
        public decimal? InfoC5R257 { get; set; }
        public decimal? InfoC6R257 { get; set; }
        public decimal? InfoC7R257 { get; set; }
        public decimal? InfoC8R257 { get; set; }
        public decimal? InfoC9R257 { get; set; }
        public decimal? InfoC4R260 { get; set; }
        public decimal? InfoC5R260 { get; set; }
        public decimal? InfoC6R260 { get; set; }
        public decimal? InfoC7R260 { get; set; }
        public decimal? InfoC8R260 { get; set; }
        public decimal? InfoC9R260 { get; set; }
        public decimal? InfoC4R261 { get; set; }
        public decimal? InfoC5R261 { get; set; }
        public decimal? InfoC6R261 { get; set; }
        public decimal? InfoC7R261 { get; set; }
        public decimal? InfoC8R261 { get; set; }
        public decimal? InfoC9R261 { get; set; }
        public decimal? InfoC4R262 { get; set; }
        public decimal? InfoC5R262 { get; set; }
        public decimal? InfoC6R262 { get; set; }
        public decimal? InfoC7R262 { get; set; }
        public decimal? InfoC8R262 { get; set; }
        public decimal? InfoC9R262 { get; set; }
        public decimal? InfoC4R263 { get; set; }
        public decimal? InfoC5R263 { get; set; }
        public decimal? InfoC6R263 { get; set; }
        public decimal? InfoC7R263 { get; set; }
        public decimal? InfoC8R263 { get; set; }
        public decimal? InfoC9R263 { get; set; }
        public decimal? InfoC4R264 { get; set; }
        public decimal? InfoC5R264 { get; set; }
        public decimal? InfoC6R264 { get; set; }
        public decimal? InfoC7R264 { get; set; }
        public decimal? InfoC8R264 { get; set; }
        public decimal? InfoC9R264 { get; set; }
        public decimal? InfoC4R265 { get; set; }
        public decimal? InfoC5R265 { get; set; }
        public decimal? InfoC6R265 { get; set; }
        public decimal? InfoC7R265 { get; set; }
        public decimal? InfoC8R265 { get; set; }
        public decimal? InfoC9R265 { get; set; }
        public decimal? InfoC4R266 { get; set; }
        public decimal? InfoC5R266 { get; set; }
        public decimal? InfoC6R266 { get; set; }
        public decimal? InfoC7R266 { get; set; }
        public decimal? InfoC8R266 { get; set; }
        public decimal? InfoC9R266 { get; set; }
        public decimal? InfoC4R267 { get; set; }
        public decimal? InfoC5R267 { get; set; }
        public decimal? InfoC6R267 { get; set; }
        public decimal? InfoC7R267 { get; set; }
        public decimal? InfoC8R267 { get; set; }
        public decimal? InfoC9R267 { get; set; }
        public decimal? InfoC4R270 { get; set; }
        public decimal? InfoC5R270 { get; set; }
        public decimal? InfoC6R270 { get; set; }
        public decimal? InfoC7R270 { get; set; }
        public decimal? InfoC8R270 { get; set; }
        public decimal? InfoC9R270 { get; set; }
        public decimal? InfoC10R270 { get; set; }
        public decimal? InfoC11R270 { get; set; }
        public decimal? InfoC4R280 { get; set; }
        public decimal? InfoC5R280 { get; set; }
        public decimal? InfoC6R280 { get; set; }
        public decimal? InfoC7R280 { get; set; }
        public decimal? InfoC8R280 { get; set; }
        public decimal? InfoC9R280 { get; set; }
        public decimal? InfoC10R280 { get; set; }
        public decimal? InfoC4R290 { get; set; }
        public decimal? InfoC5R290 { get; set; }
        public decimal? InfoC6R290 { get; set; }
        public decimal? InfoCountertangaassets { get; set; }
        public decimal? InfoCounterfrmstrictacc { get; set; }
        public decimal? InfoCounterinsolventdeb { get; set; }
        public decimal? InfoCounterspecequip { get; set; }
        public decimal? InfoCounterdebtnotdeman { get; set; }
        public decimal? InfoCounterperiodicals { get; set; }
        public decimal? PenLeader { get; set; }
        public decimal? PenChiefAcc { get; set; }
        public decimal? PenLeaderOfFes { get; set; }
        public decimal? CentraccCode { get; set; }
        public decimal? CentraccName { get; set; }
        public decimal? CentraccOgrn { get; set; }
        public decimal? CentraccInn { get; set; }
        public decimal? CentraccKpp { get; set; }
        public decimal? CentraccC4R268 { get; set; }
        public decimal? CentraccC5R270 { get; set; }
        public decimal? CentraccC6R270 { get; set; }
        public decimal? CentraccC7R270 { get; set; }
        public decimal? CentraccC8R270 { get; set; }
        public decimal? CentraccC9R270 { get; set; }
        public decimal? CentraccC10R270 { get; set; }
        public decimal? CentraccC11R270 { get; set; }
        public decimal? CaLeader { get; set; }
        public decimal? CaExecutor { get; set; }
        public decimal? CaLeader1 { get; set; }
        public decimal? CaExecutor1 { get; set; }
        public decimal? CaExecutorMail { get; set; }
        public decimal? ReportNum { get; set; }
        public decimal? Codereportform { get; set; }
        public decimal? HrErNameOfEntity { get; set; }
        public decimal? HrErCodeOfEntity { get; set; }
        public decimal? HrErOkpo { get; set; }
        public decimal? HrErOktmo { get; set; }
        public decimal? HrErGlavaBk { get; set; }
        public decimal? HrErPrcdofent { get; set; }
        public decimal? HrErPrnmofent { get; set; }
        public decimal? HrPeriodType { get; set; }
        public decimal? HrReportDate { get; set; }
        public decimal? HrInstitutionCode { get; set; }
        public decimal? HrAiCode { get; set; }
        public decimal? HrAiName { get; set; }
        public decimal? HrTypeactivityname { get; set; }
        public decimal? HrTypeactivitycode { get; set; }
        public decimal? HrBtCodeOfBudget { get; set; }
        public decimal? HrBtNameOfBudget { get; set; }
        public decimal? HrBtCodeOfType { get; set; }
        public decimal? Fullyapproved { get; set; }
        public decimal? Lastreport { get; set; }
        public decimal? InfoC7R290 { get; set; }
        public decimal? InfoC8R290 { get; set; }
        public decimal? InfoC9R290 { get; set; }
        public decimal? InfoC10R290 { get; set; }
        public decimal? InfoC11R290 { get; set; }
        public decimal? InfoC4R300 { get; set; }
        public decimal? InfoC5R300 { get; set; }
        public decimal? InfoC6R300 { get; set; }
        public decimal? InfoC7R300 { get; set; }
        public decimal? InfoC8R300 { get; set; }
        public decimal? InfoC9R300 { get; set; }
        public decimal? InfoC10R300 { get; set; }
        public decimal? InfoC11R300 { get; set; }
        public decimal? InfoC4R016 { get; set; }
        public decimal? InfoC5R016 { get; set; }
        public decimal? InfoC6R016 { get; set; }
        public decimal? InfoC7R016 { get; set; }
        public decimal? InfoC8R016 { get; set; }
        public decimal? InfoC9R016 { get; set; }
        public decimal? InfoC10R016 { get; set; }
        public decimal? InfoC11R016 { get; set; }
        public decimal? InfoC10R020 { get; set; }
        public decimal? InfoC11R020 { get; set; }
        public decimal? InfoC10R030 { get; set; }
        public decimal? InfoC11R030 { get; set; }
        public decimal? InfoC10R040 { get; set; }
        public decimal? InfoC11R040 { get; set; }
        public decimal? InfoC10R050 { get; set; }
        public decimal? InfoC11R050 { get; set; }
        public decimal? InfoC10R051 { get; set; }
        public decimal? InfoC11R051 { get; set; }
        public decimal? InfoC10R052 { get; set; }
        public decimal? InfoC11R052 { get; set; }
        public decimal? InfoC10R054 { get; set; }
        public decimal? InfoC11R054 { get; set; }
        public decimal? InfoC10R055 { get; set; }
        public decimal? InfoC11R055 { get; set; }
        public decimal? InfoC10R060 { get; set; }
        public decimal? InfoC11R060 { get; set; }
        public decimal? InfoC4R249 { get; set; }
        public decimal? InfoC5R249 { get; set; }
        public decimal? InfoC6R249 { get; set; }
        public decimal? InfoC7R249 { get; set; }
        public decimal? InfoC8R249 { get; set; }
        public decimal? InfoC9R249 { get; set; }
        public decimal? InfoC10R249 { get; set; }
        public decimal? InfoC11R249 { get; set; }
        public decimal? InfoC4R248 { get; set; }
        public decimal? InfoC5R248 { get; set; }
        public decimal? InfoC6R248 { get; set; }
        public decimal? InfoC7R248 { get; set; }
        public decimal? InfoC8R248 { get; set; }
        public decimal? InfoC9R248 { get; set; }
        public decimal? InfoC10R248 { get; set; }
        public decimal? InfoC11R248 { get; set; }
        public decimal? InfoC10R070 { get; set; }
        public decimal? InfoC11R070 { get; set; }
        public decimal? InfoC10R071 { get; set; }
        public decimal? InfoC11R071 { get; set; }
        public decimal? InfoC10R072 { get; set; }
        public decimal? InfoC11R072 { get; set; }
        public decimal? InfoC10R080 { get; set; }
        public decimal? InfoC11R080 { get; set; }
        public decimal? InfoC10R090 { get; set; }
        public decimal? InfoC11R090 { get; set; }
        public decimal? InfoC10R100 { get; set; }
        public decimal? InfoC11R100 { get; set; }
        public decimal? InfoC10R101 { get; set; }
        public decimal? InfoC11R101 { get; set; }
        public decimal? InfoC10R102 { get; set; }
        public decimal? InfoC11R102 { get; set; }
        public decimal? InfoC10R103 { get; set; }
        public decimal? InfoC11R103 { get; set; }
        public decimal? InfoC10R104 { get; set; }
        public decimal? InfoC11R104 { get; set; }
        public decimal? InfoC10R105 { get; set; }
        public decimal? InfoC11R105 { get; set; }
        public decimal? InfoC10R120 { get; set; }
        public decimal? InfoC11R120 { get; set; }
        public decimal? InfoC10R130 { get; set; }
        public decimal? InfoC11R130 { get; set; }
        public decimal? InfoC10R150 { get; set; }
        public decimal? InfoC11R150 { get; set; }
        public decimal? InfoC10R160 { get; set; }
        public decimal? InfoC11R160 { get; set; }
        public decimal? InfoC10R170 { get; set; }
        public decimal? InfoC11R170 { get; set; }
        public decimal? InfoC10R171 { get; set; }
        public decimal? InfoC11R171 { get; set; }
        public decimal? InfoC10R172 { get; set; }
        public decimal? InfoC11R172 { get; set; }
        public decimal? InfoC10R173 { get; set; }
        public decimal? InfoC11R173 { get; set; }
        public decimal? InfoC10R180 { get; set; }
        public decimal? InfoC11R180 { get; set; }
        public decimal? InfoC10R181 { get; set; }
        public decimal? InfoC11R181 { get; set; }
        public decimal? InfoC10R183 { get; set; }
        public decimal? InfoC11R183 { get; set; }
        public decimal? InfoC10R182 { get; set; }
        public decimal? InfoC11R182 { get; set; }
        public decimal? InfoC10R200 { get; set; }
        public decimal? InfoC11R200 { get; set; }
        public decimal? InfoC10R210 { get; set; }
        public decimal? InfoC11R210 { get; set; }
        public decimal? InfoC10R211 { get; set; }
        public decimal? InfoC11R211 { get; set; }
        public decimal? InfoC10R212 { get; set; }
        public decimal? InfoC11R212 { get; set; }
        public decimal? InfoC10R220 { get; set; }
        public decimal? InfoC11R220 { get; set; }
        public decimal? InfoC10R221 { get; set; }
        public decimal? InfoC11R221 { get; set; }
        public decimal? InfoC10R222 { get; set; }
        public decimal? InfoC11R222 { get; set; }
        public decimal? InfoC10R224 { get; set; }
        public decimal? InfoC11R224 { get; set; }
        public decimal? InfoC10R225 { get; set; }
        public decimal? InfoC11R225 { get; set; }
        public decimal? InfoC10R230 { get; set; }
        public decimal? InfoC11R230 { get; set; }
        public decimal? InfoC10R240 { get; set; }
        public decimal? InfoC11R240 { get; set; }
        public decimal? InfoC10R241 { get; set; }
        public decimal? InfoC11R241 { get; set; }
        public string ReorgNameGlava { get; set; }
        public string ReorgGlavaBk { get; set; }

        public virtual ICollection<HfsInfoFrmstr830List> HfsInfoFrmstr830List { get; set; }
        public virtual ICollection<HfsInfoInsdeb830List> HfsInfoInsdeb830List { get; set; }
        public virtual ICollection<HfsInfoInskred830List> HfsInfoInskred830List { get; set; }
        public virtual ICollection<HfsInfoPeriod830List> HfsInfoPeriod830List { get; set; }
        public virtual ICollection<HfsInfoSpequip830List> HfsInfoSpequip830List { get; set; }
        public virtual ICollection<HfsInfoTangaas830List> HfsInfoTangaas830List { get; set; }
    }
}
