using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace SP_Entity
{
    public partial class RepLinesResTmp1Ai
    {
        public decimal? LineId { get; set; }
        public decimal? HeaderId { get; set; }
        public string SectionNumber { get; set; }
        public string Dim1 { get; set; }
        public string Dim2 { get; set; }
        public string Dim3 { get; set; }
        public string Dim4 { get; set; }
        public string Dim5 { get; set; }
        public string Dim6 { get; set; }
        public string Dim7 { get; set; }
        public string Dim8 { get; set; }
        public string Dim9 { get; set; }
        public string Dim10 { get; set; }
        public string Dim11 { get; set; }
        public string Dim12 { get; set; }
        public string Dim13 { get; set; }
        public string Dim14 { get; set; }
        public string Dim15 { get; set; }
        public string Dim16 { get; set; }
        public string Dim17 { get; set; }
        public string Dim18 { get; set; }
        public string Dim19 { get; set; }
        public string Dim20 { get; set; }
        public decimal? DimNum1 { get; set; }
        public decimal? DimNum2 { get; set; }
        public decimal? DimNum3 { get; set; }
        public decimal? DimNum4 { get; set; }
        public decimal? DimNum5 { get; set; }
        public decimal? DimNum6 { get; set; }
        public decimal? DimNum7 { get; set; }
        public decimal? DimNum8 { get; set; }
        public decimal? DimNum9 { get; set; }
        public decimal? DimNum10 { get; set; }
        public decimal? DimNum11 { get; set; }
        public decimal? DimNum12 { get; set; }
        public decimal? DimNum13 { get; set; }
        public decimal? DimNum14 { get; set; }
        public decimal? DimNum15 { get; set; }
        public decimal? DimNum16 { get; set; }
        public decimal? DimNum17 { get; set; }
        public decimal? DimNum18 { get; set; }
        public decimal? DimNum19 { get; set; }
        public decimal? DimNum20 { get; set; }
        public DateTime? DimDate1 { get; set; }
        public DateTime? DimDate2 { get; set; }
        public DateTime? DimDate3 { get; set; }
        public DateTime? DimDate4 { get; set; }
        public DateTime? DimDate5 { get; set; }
        public DateTime? DimDate6 { get; set; }
        public DateTime? DimDate7 { get; set; }
        public DateTime? DimDate8 { get; set; }
        public DateTime? DimDate9 { get; set; }
        public DateTime? DimDate10 { get; set; }
        public DateTime? DimDate11 { get; set; }
        public DateTime? DimDate12 { get; set; }
        public DateTime? DimDate13 { get; set; }
        public DateTime? DimDate14 { get; set; }
        public DateTime? DimDate15 { get; set; }
        public DateTime? DimDate16 { get; set; }
        public DateTime? DimDate17 { get; set; }
        public DateTime? DimDate18 { get; set; }
        public DateTime? DimDate19 { get; set; }
        public DateTime? DimDate20 { get; set; }
        public decimal? Dat1 { get; set; }
        public decimal? Dat2 { get; set; }
        public decimal? Dat3 { get; set; }
        public decimal? Dat4 { get; set; }
        public decimal? Dat5 { get; set; }
        public decimal? Dat6 { get; set; }
        public decimal? Dat7 { get; set; }
        public decimal? Dat8 { get; set; }
        public decimal? Dat9 { get; set; }
        public decimal? Dat10 { get; set; }
        public decimal? Dat11 { get; set; }
        public decimal? Dat12 { get; set; }
        public decimal? Dat13 { get; set; }
        public decimal? Dat14 { get; set; }
        public decimal? Dat15 { get; set; }
        public decimal? Dat16 { get; set; }
        public decimal? Dat17 { get; set; }
        public decimal? Dat18 { get; set; }
        public decimal? Dat19 { get; set; }
        public decimal? Dat20 { get; set; }
        public string DatVc1 { get; set; }
        public string DatVc2 { get; set; }
        public string DatVc3 { get; set; }
        public string DatVc4 { get; set; }
        public string DatVc5 { get; set; }
        public string DatVc6 { get; set; }
        public string DatVc7 { get; set; }
        public string DatVc8 { get; set; }
        public string DatVc9 { get; set; }
        public string DatVc10 { get; set; }
        public string DatVc11 { get; set; }
        public string DatVc12 { get; set; }
        public string DatVc13 { get; set; }
        public string DatVc14 { get; set; }
        public string DatVc15 { get; set; }
        public string DatVc16 { get; set; }
        public string DatVc17 { get; set; }
        public string DatVc18 { get; set; }
        public string DatVc19 { get; set; }
        public string DatVc20 { get; set; }
        public DateTime? DatDate1 { get; set; }
        public DateTime? DatDate2 { get; set; }
        public DateTime? DatDate3 { get; set; }
        public DateTime? DatDate4 { get; set; }
        public DateTime? DatDate5 { get; set; }
        public DateTime? DatDate6 { get; set; }
        public DateTime? DatDate7 { get; set; }
        public DateTime? DatDate8 { get; set; }
        public DateTime? DatDate9 { get; set; }
        public DateTime? DatDate10 { get; set; }
        public DateTime? DatDate11 { get; set; }
        public DateTime? DatDate12 { get; set; }
        public DateTime? DatDate13 { get; set; }
        public DateTime? DatDate14 { get; set; }
        public DateTime? DatDate15 { get; set; }
        public DateTime? DatDate16 { get; set; }
        public DateTime? DatDate17 { get; set; }
        public DateTime? DatDate18 { get; set; }
        public DateTime? DatDate19 { get; set; }
        public DateTime? DatDate20 { get; set; }
        public string SummaryFlag { get; set; }
        public string LineName { get; set; }
        public decimal? Dat100 { get; set; }
        public decimal? IsError { get; set; }
        public decimal? Dat21 { get; set; }
        public decimal? Dat22 { get; set; }
        public decimal? CreatedBy { get; set; }
        public decimal? LastUpdatedBy { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public decimal? LastUpdateLogin { get; set; }
        public DateTime? CreationDate { get; set; }
        public string TerminalId { get; set; }
        public string FormRef { get; set; }
        public string TypeOfSource { get; set; }
        public string SourceCode { get; set; }
        public string DocType { get; set; }
        public string SourceName { get; set; }
        public decimal? FirstLoaded { get; set; }
        public decimal? TotLevel { get; set; }
        public string OrdChr1 { get; set; }
        public string OrdChr2 { get; set; }
        public string OrdChr3 { get; set; }
        public DateTime? ReportDate { get; set; }
        public decimal? Dat23 { get; set; }
        public decimal? Dat24 { get; set; }
        public decimal? Dat25 { get; set; }
        public decimal? Dat26 { get; set; }
        public decimal? Dat27 { get; set; }
        public decimal? Dat28 { get; set; }
        public decimal? Dat29 { get; set; }
        public decimal? Dat30 { get; set; }
        public decimal? Dat31 { get; set; }
        public decimal? Dat32 { get; set; }
        public decimal? Dat33 { get; set; }
        public decimal? Dat34 { get; set; }
        public decimal? Dat35 { get; set; }
        public decimal? Dat36 { get; set; }
        public decimal? Dat37 { get; set; }
        public decimal? Dat38 { get; set; }
        public decimal? Dat39 { get; set; }
        public decimal? Dat40 { get; set; }
        public decimal? Dat41 { get; set; }
        public decimal? Dat42 { get; set; }
        public decimal? Dat43 { get; set; }
        public decimal? Dat44 { get; set; }
        public decimal? Dat45 { get; set; }
        public decimal? Dat46 { get; set; }
        public decimal? Dat47 { get; set; }
        public decimal? Dat48 { get; set; }
        public decimal? Dat49 { get; set; }
        public decimal? Dat50 { get; set; }
        public decimal? Dat51 { get; set; }
        public decimal? Dat52 { get; set; }
        public decimal? Dat53 { get; set; }
        public decimal? Dat54 { get; set; }
        public decimal? Dat55 { get; set; }
        public decimal? Dat56 { get; set; }
        public decimal? Dat57 { get; set; }
        public decimal? Dat58 { get; set; }
        public decimal? Dat59 { get; set; }
        public decimal? Dat60 { get; set; }
        public decimal? Dat61 { get; set; }
        public decimal? Dat62 { get; set; }
        public decimal? Dat63 { get; set; }
        public decimal? Dat64 { get; set; }
        public decimal? Dat65 { get; set; }
        public decimal? Dat66 { get; set; }
        public decimal? Dat67 { get; set; }
        public decimal? Dat68 { get; set; }
        public decimal? Dat69 { get; set; }
        public decimal? Dat70 { get; set; }
        public decimal? Dat71 { get; set; }
        public decimal? Dat72 { get; set; }
        public decimal? Dat73 { get; set; }
        public decimal? Dat74 { get; set; }
        public decimal? Dat75 { get; set; }
        public decimal? Dat76 { get; set; }
        public decimal? Dat77 { get; set; }
        public decimal? Dat78 { get; set; }
        public decimal? Dat79 { get; set; }
        public decimal? Dat80 { get; set; }
        public string TypeItem { get; set; }
        public decimal? OrdNum { get; set; }
        public decimal? IsTotal { get; set; }
        public string Dim21 { get; set; }
        public string Dim22 { get; set; }
        public string Dim23 { get; set; }
        public string Dim24 { get; set; }
        public string Dim25 { get; set; }
        public string Dim26 { get; set; }
        public string Dim27 { get; set; }
        public string Dim28 { get; set; }
        public string Dim29 { get; set; }
        public string Dim30 { get; set; }
        public decimal? DimNum21 { get; set; }
        public decimal? DimNum22 { get; set; }
        public decimal? DimNum23 { get; set; }
        public decimal? DimNum24 { get; set; }
        public decimal? DimNum25 { get; set; }
        public decimal? DimNum26 { get; set; }
        public decimal? DimNum27 { get; set; }
        public decimal? DimNum28 { get; set; }
        public decimal? DimNum29 { get; set; }
        public decimal? DimNum30 { get; set; }
        public DateTime? DimDate21 { get; set; }
        public DateTime? DimDate22 { get; set; }
        public DateTime? DimDate23 { get; set; }
        public DateTime? DimDate24 { get; set; }
        public DateTime? DimDate25 { get; set; }
        public DateTime? DimDate26 { get; set; }
        public DateTime? DimDate27 { get; set; }
        public DateTime? DimDate28 { get; set; }
        public DateTime? DimDate29 { get; set; }
        public DateTime? DimDate30 { get; set; }
        public string Dim31 { get; set; }
        public string Dim32 { get; set; }
        public string Dim33 { get; set; }
        public string Dim34 { get; set; }
        public string Dim35 { get; set; }
        public string Dim36 { get; set; }
        public string Dim37 { get; set; }
        public string Dim38 { get; set; }
        public string Dim39 { get; set; }
        public string Dim40 { get; set; }
        public string Dim41 { get; set; }
        public string Dim42 { get; set; }
        public string Dim43 { get; set; }
        public string Dim44 { get; set; }
        public string Dim45 { get; set; }
        public string Dim46 { get; set; }
        public string Dim47 { get; set; }
        public string Dim48 { get; set; }
        public string Dim49 { get; set; }
        public string Dim50 { get; set; }
        public string Dim51 { get; set; }
        public string Dim52 { get; set; }
        public string Dim53 { get; set; }
        public string Dim54 { get; set; }
        public string Dim55 { get; set; }
        public string Dim56 { get; set; }
        public string Dim57 { get; set; }
        public string Dim58 { get; set; }
        public string Dim59 { get; set; }
        public string Dim60 { get; set; }
        public string Dim61 { get; set; }
        public string Dim62 { get; set; }
        public string Dim63 { get; set; }
        public string Dim64 { get; set; }
        public string Dim65 { get; set; }
        public string Dim66 { get; set; }
        public string Dim67 { get; set; }
        public string Dim68 { get; set; }
        public string Dim69 { get; set; }
        public string Dim70 { get; set; }
        public string Dim71 { get; set; }
        public string Dim72 { get; set; }
        public string Dim73 { get; set; }
        public string Dim74 { get; set; }
        public string Dim75 { get; set; }
        public string Dim76 { get; set; }
        public string Dim77 { get; set; }
        public string Dim78 { get; set; }
        public string Dim79 { get; set; }
        public string Dim80 { get; set; }
    }
}
